const termDictionary: {
  term: string;
  definition: string;
}[] = [
  {
    term: "roll",
    definition: "A random number generated by dice.",
  },
  {
    term: "rolls",
    definition: "Random numbers generated by dice.",
  },
  {
    term: "d20",
    definition: "A 20-sided die.",
  },
  {
    term: "d12",
    definition: "A 12-sided die.",
  },
  {
    term: "d10",
    definition: "A 10-sided die.",
  },
  {
    term: "d8",
    definition: "An 8-sided die.",
  },
  {
    term: "d6",
    definition: "A 6-sided die.",
  },
  {
    term: "d4",
    definition: "A 4-sided die.",
  },
  {
    term: "ability check",
    definition: "A roll to see if you succeed at a task.",
  },
  {
    term: "ability checks",
    definition: "Rolls to see if you succeed at a task.",
  },

  {
    term: "Strength",
    definition: "An ability score that measures a character's physical power.",
  },
  {
    term: "dexterity",
    definition:
      "An ability score that measures a character's agility and reflexes.",
  },
  {
    term: "constitution",
    definition: "An ability score that measures a character's physical health.",
  },
  {
    term: "intelligence",
    definition: "An ability score that measures a character's mental acuity.",
  },
  {
    term: "wisdom",
    definition: "An ability score that measures a character's intuition.",
  },
  {
    term: "charisma",
    definition:
      "An ability score that measures a character's force of personality.",
  },
  {
    term: "proficiency bonus",
    definition:
      "A bonus that is added to any ability check, saving throw, or attack roll that you are proficient in.",
  },
  {
    term: "proficient",
    definition:
      "Every character performs better at certain tasks. They are proficient in those tasks. This allows them to add their proficiency bonus to rolls related to that task. A character also may be proficient with certain equipment, allowing them to use it effectively.",
  },

  {
    term: "saving throw",
    definition: "A roll to resist an effect that would harm you.",
  },
  {
    term: "skill",
    definition:
      "Represents a character's ability to perform a specific task. They are based on ability scores. Proficiency in a skill allows you to add your proficiency bonus to rolls related to that skill. ",
  },
  {
    term: "class features",
    definition:
      "A set of abilities that a character gains from their class when they reach certain levels.",
  },
  {
    term: "levels",
    definition:
      "A measure of how experienced your character is. Higher levels are more powerful. Max is 20.",
  },
  {
    term: "skills",
    definition:
      "Represent a character's ability to perform specific tasks. They are based on ability scores. Proficiency in a skill allows you to add your proficiency bonus to rolls related to that skill. ",
  },
  // {
  //   term: "spell",
  //   definition: "A magical effect that is cast during the game.",
  // },
  {
    term: "spells",
    definition: "Magical effects that are cast during the game.",
  },
  {
    term: "spell slot",
    definition:
      "A resource that is used to cast spells. Represents how many spells of a certain level you can cast before needing to rest.",
  },
  {
    term: "spell slots",
    definition:
      "Resources that are used to cast spells. Represents how many spells you can cast before needing to rest.",
  },
  {
    term: "spellcasting ability",
    definition:
      "The ability score that is used to determine the power of your spells.",
  },
  {
    term: "spell attack modifier",
    definition: "The number that you add to your spell attack rolls.",
  },
  {
    term: "spell attack roll",
    definition:
      "Certain single target spells require an attack roll to see if they hit.",
  },
  {
    term: "spell attack rolls",
    definition:
      "Certain single target spells require an attack roll to see if they hit.",
  },
  {
    term: "attack roll",
    definition:
      "A d20 roll to see if an attack hits. The attack hits if the roll beats the target's armor class.",
  },
  {
    term: "spell save DC",
    definition:
      "Some spells require a saving throw to resist their effects. The DC is the number that must be rolled on a d20 to succeed at the saving throw.",
  },
  {
    term: "spell attack bonus",
    definition: "The number that you add to your spell attack rolls.",
  },
  {
    term: "hit points",
    definition:
      "A measure of how much damage you can take before you are incapacitated.",
  },
  {
    term: "hitpoints",
    definition:
      "A measure of how much damage you can take before you are incapacitated.",
  },
  {
    term: "armor class",
    definition: "A measure of how difficult it is to hit you with an attack.",
  },
  {
    term: "AC",
    definition: "Short for Armor Class.",
  },
  {
    term: "initiative",
    definition: "A roll to determine the order of combat.",
  },
  {
    term: "speed",
    definition: "How far you can move in a turn.",
  },
  {
    term: "alignment",
    definition: "Your character's moral and ethical compass.",
  },
  {
    term: "ability score",
    definition:
      "Numerical values that represent a character's physical and mental attributes. The 6 ability scores are Strength, Dexterity, Constitution, Intelligence, Wisdom, and Charisma.",
  },
  {
    term: "action",
    definition: "A Primary Combat Resource. You can take one per turn.",
  },
  {
    term: "bonus action",
    definition: "A Secondary Combat Resource. You can take one per turn.",
  },
  {
    term: "reaction",
    definition:
      "A Tertiary Combat Resource. You can take one per round of turns.",
  },
  {
    term: "movement",
    definition: "How far you can move in a turn.",
  },
  {
    term: "turn",
    definition:
      "In combat, each creature gets a designated moment to act, based on initiative rolls.",
  },
  {
    term: "initiative",
    definition:
      "A roll to determine the order of combat. Turns are taken based on whoever rolled highest to lowest.",
  },
  {
    term: "round",
    definition: "A full cycle of turns.",
  },
  {
    term: "hit dice",
    definition:
      "A resource that is used to regain hit points during a short rest rolling a die. Also used to determine how many hit points you gain when you level up.",
  },
  {
    term: "hit die",
    definition:
      "A resource that is used to regain hit points during a short rest by rolling a die. Also used to determine how many hit points you gain when you level up.",
  },
  {
    term: "short rest",
    definition: "A period of downtime that lasts at least 1 hour.",
  },
  {
    term: "long rest",
    definition: "A period of downtime that lasts at least 8 hours.",
  },
  {
    term: "experience points",
    definition:
      "A measure of how much you have learned and grown. When you gain enough, you level up.",
  },
  {
    term: "level",
    definition:
      "A measure of how experienced you are. Higher levels are more powerful. Max is 20.",
  },
  {
    term: "class",
    definition:
      "A profession that your character has trained in. Determines your character's abilities through features.",
  },
  {
    term: "subclass",
    definition:
      "A specialization within a class. Your character gains additional features through your subclass.",
  },
  {
    term: "feature",
    definition:
      "An ability that your character gains from their class or subclass once they reach a certain level.",
  },
  {
    term: "features",
    definition:
      "Abilities that your character gains from their class or subclass once they reach a certain level.",
  },
  {
    term: "DC",
    definition: "Short for Difficulty Class. ",
  },
  {
    term: "Difficulty Class",
    definition: "The number that must be rolled on a d20 to succeed at a task.",
  },
  {
    term: "ability modifier",
    definition:
      "A number based of an ability score that is added to skill rolls that use that ability.",
  },
  {
    term: "Armor",
    definition: "Protective gear that increases your Armor Class.",
  },
  {
    term: "Weapon",
    definition:
      "A tool used to deal damage. You must be proficient to use it effectively.",
  },
  {
    term: "weapons",
    definition:
      "Tools used to deal damage. You must be proficient to use them effectively.",
  },
  {
    term: "tool",
    definition:
      "An item that can be used to perform a specific task. You must be proficient to use it effectively.",
  },
  {
    term: "tools",
    definition:
      "Items that can be used to perform specific tasks. You must be proficient to use them effectively.",
  },
  {
    term: "saving throws",
    definition:
      "Rolls to resist an effect that would harm you. You add your proficiency bonus if you are proficient.",
  },
  {
    term: "acrobatics",
    definition:
      "A skill that measures your ability to perform feats of agility. Based on your Dexterity ability score.",
  },
  {
    term: "animal handling",
    definition:
      "A skill that measures your ability to interact with animals. Based on your Wisdom ability score.",
  },
  {
    term: "arcana",
    definition:
      "A skill that measures your knowledge of magical lore. Based on your Intelligence ability score.",
  },
  {
    term: "athletics",
    definition:
      "A skill that measures your ability to perform feats of raw physical power. Based on your Strength ability score.",
  },
  {
    term: "deception",
    definition:
      "A skill that measures your ability to lie and deceive. Based on your Charisma ability score.",
  },
  {
    term: "history",
    definition:
      "A skill that measures your knowledge of historical events. Based on your Intelligence ability score.",
  },
  {
    term: "insight",
    definition:
      "A skill that measures your ability to read people and situations. Based on your Wisdom ability score.",
  },
  {
    term: "intimidation",
    definition:
      "A skill that measures your ability to scare and intimidate others. Based on your Charisma ability score.",
  },
  {
    term: "investigation",
    definition:
      "A skill that measures your ability to solve mysteries and puzzles. Based on your Intelligence ability score.",
  },
  {
    term: "medicine",
    definition:
      "A skill that measures your ability to heal and treat wounds. Based on your Wisdom ability score.",
  },
  {
    term: "nature",
    definition:
      "A skill that measures your knowledge of the natural world. Based on your Intelligence ability score.",
  },
  {
    term: "perception",
    definition:
      "A skill that measures your ability to notice things. Based on your Wisdom ability score.",
  },
  {
    term: "performance",
    definition:
      "A skill that measures your ability to entertain and perform. Based on your Charisma ability score.",
  },
  {
    term: "persuasion",
    definition:
      "A skill that measures your ability to convince and persuade others. Based on your Charisma ability score.",
  },
  {
    term: "religion",
    definition:
      "A skill that measures your knowledge of religious lore. Based on your Intelligence ability score.",
  },
  {
    term: "sleight of hand",
    definition:
      "A skill that measures your ability to perform feats of legerdemain. Based on your Dexterity ability score.",
  },
  {
    term: "stealth",
    definition:
      "A skill that measures your ability to move unseen and unheard. Based on your Dexterity ability score.",
  },
  {
    term: "survival",
    definition:
      "A skill that measures your ability to survive in the wild. Based on your Wisdom ability score.",
  },
  {
    term: "cantrip",
    definition:
      "A spell that can be cast at will. Does not consume a spell slot.",
  },
  {
    term: "cantrips",
    definition: "Spells that can be cast at will. Do not consume spell slots.",
  },
  {
    term: "spell list",
    definition: "A list of spells that a specific class can cast.",
  },
  {
    term: "ritual",
    definition:
      "A spell that can be cast without consuming a spell slot. It takes 10 minutes longer to cast.",
  },
  {
    term: "ritual spell",
    definition:
      "A spell that can be cast without consuming a spell slot. It takes 10 minutes longer to cast.",
  },
  {
    term: "arcane focus",
    definition:
      "A tool used to cast spells. It can be used in place of material components.",
  },
  {
    term: "Equipment",
    definition: "Items that your character carries and utilizes.",
  },
  {
    term: "Material Components",
    definition:
      "Items that are consumed when casting a spell. Some spells require them.",
  },
  {
    term: "Somantic Components",
    definition:
      "Gestures that are required to cast a spell. Some spells require them.",
  },
  {
    term: "Verbal Components",
    definition:
      "Words that are required to cast a spell. Some spells require them.",
  },
  {
    term: "Background",
    definition:
      "A character's history and upbringing. Determines some of your character's starting equipment and abilities.",
  },
  {
    term: "Subrace",
    definition:
      "A more specific heritage based on your race. Grants additional racial traits.",
  },
  {
    term: "Racial trait",
    definition: "An ability that your character gains from their race/subrace.",
  },
  {
    term: "Racial traits",
    definition: "Abilities that your character gains from their race/subrace.",
  },
  {
    term: "Race",
    definition:
      "A character's species. Determines many aspects of your character, including size, age, languages, Ability scores, and racial traits.",
  },
  {
    term: "Size",
    definition:
      "A character's physical size. Determines many aspects of your character, including speed and carrying capacity.",
  },
  {
    term: "Carrying Capacity",
    definition: "The maximum amount of weight that your character can carry.",
  },

  {
    term: "Languages",
    definition: "The languages that your character can speak, read, and write.",
  },
  {
    term: "Age",
    definition: "How old your character is.",
  },
  {
    term: "Ability Scores",
    definition:
      "Numerical values that represent a character's physical and mental attributes.",
  },
  {
    term: "Darkvision",
    definition:
      "The ability to see in the dark. Allows you to see in dim light as if it were bright light and in darkness as if it were dim light.",
  },
];

export default termDictionary;
