import { Prisma } from '@prisma/client';

const SpellSixthLevelSeed: Prisma.SpellCreateManyInput[] = [
  {
    id: '380',
    name: 'Blade Barrier',
    slug: 'blade-barrier',
    description:
      'You create a vertical wall of whirling, razor-sharp blades made of magical energy. The wall appears within range and lasts for the duration. You can make a straight wall up to 100 feet long, 20 feet high, and 5 feet thick, or a ringed wall up to 60 feet in diameter, 20 feet high, and 5 feet thick. The wall provides three-quarters cover to creatures behind it, and its space is difficult terrain.\n\nWhen a creature enters the wall’s area for the first time on a turn or starts its turn there, the creature must make a Dexterity saving throw. On a failed save, the creature takes 6d10 slashing damage. On a successful save, the creature takes half as much damage.\n\n',
    level: 6,
    school: 'EVOCATION',
    castingTime: '1 action',
    range: '90 feet',
    verbal: true,
    somatic: true,
    material: false,
    duration: 'Concentration, up to 10 minutes',
    source: "Player's Handbook",
  },
  {
    id: '382',
    name: 'Chain Lightning',
    slug: 'chain-lightning',
    description:
      'You create a bolt of lightning that arcs toward a target of your choice that you can see within range. Three bolts then leap from that target to as many as three other targets, each of which must be within 30 feet of the first target. A target can be a creature or an object and can be targeted by only one of the bolts.\n\nA target must make a Dexterity saving throw. The target takes 10d8 lightning damage on a failed save, or half as much on a successful one.\n\n',
    level: 6,
    school: 'EVOCATION',
    castingTime: '1 action',
    range: '150 feet',
    verbal: true,
    somatic: true,
    material: true,
    materialCost:
      '(a bit of fur; a piece of amber, glass, or a crystal rod; and three silver pins)',
    duration: 'Instantaneous',
    source: "Player's Handbook",
    upcastInfo:
      'When you cast this spell using a spell slot of 7th level or higher, one additional bolt leaps from the first target to another target for each slot level above 6th.',
  },
  {
    id: '383',
    name: 'Circle of Death',
    slug: 'circle-of-death',
    description:
      'A sphere of negative energy ripples out in a 60-foot-radius sphere from a point within range. Each creature in that area must make a Constitution saving throw. A target takes 8d6 necrotic damage on a failed save, or half as much damage on a successful one.\n\n',
    level: 6,
    school: 'NECROMANCY',
    castingTime: '1 action',
    range: '150 feet',
    verbal: true,
    somatic: true,
    material: true,
    materialCost: '(the powder of a crushed black pearl worth at least 500 gp)',
    duration: 'Instantaneous',
    source: "Player's Handbook",
    upcastInfo:
      'When you cast this spell using a spell slot of 7th level or higher, the damage increases by 2d6 for each slot level above 6th.',
  },
  {
    id: '384',
    name: 'Conjure Fey',
    slug: 'conjure-fey',
    description:
      'You summon a fey creature of challenge rating 6 or lower, or a fey spirit that takes the form of a beast of challenge rating 6 or lower. It appears in an unoccupied space that you can see within range. The fey creature disappears when it drops to 0 hit points or when the spell ends.\n\nThe fey creature is friendly to you and your companions for the duration. Roll initiative for the creature, which has its own turns. It obeys any verbal commands that you issue to it (no action required by you), as long as they don’t violate its alignment. If you don’t issue any commands to the fey creature, it defends itself from hostile creatures but otherwise takes no actions.\n\nIf your concentration is broken, the fey creature doesn’t disappear. Instead, you lose control of the fey creature, it becomes hostile toward you and your companions, and it might attack. An uncontrolled fey creature can’t be dismissed by you, and it disappears 1 hour after you summoned it. The DM has the fey creature’s statistics.\n\n',
    level: 6,
    school: 'CONJURATION',
    castingTime: '1 action',
    range: '90 feet',
    verbal: true,
    somatic: true,
    material: false,
    duration: 'Concentration, up to 1 hour',
    source: "Player's Handbook",
    upcastInfo:
      'When you cast this spell using a spell slot of 7th level or higher, the challenge rating increases by 1 for each slot level above 6th.',
  },
  {
    id: '385',
    name: 'Contingency',
    slug: 'contingency',
    description:
      'Choose a spell of 5th level or lower that you can cast, that has a casting time of 1 action, and that can target you. You cast that spell—called the contingent spell—as part of casting contingency, expending spell slots for both, but the contingent spell doesn’t come into effect. Instead, it takes effect when a certain circumstance occurs. You describe that circumstance when you cast the two spells. For example, a contingency cast with water breathing might stipulate that water breathing comes into effect when you are engulfed in water or a similar liquid.\n\nThe contingent spell takes effect immediately after the circumstance is met for the first time, whether or not you want it to, and then contingency ends.\n\nThe contingent spell takes effect only on you, even if it can normally target others. You can use only one contingency spell at a time. If you cast this spell again, the effect of another contingency spell on you ends. Also, contingency ends on you if its material component is ever not on your person.',
    level: 6,
    school: 'EVOCATION',
    castingTime: '10 minutes',
    range: 'Self',
    verbal: true,
    somatic: true,
    material: true,
    materialCost:
      '(a statuette of yourself carved from ivory and decorated with gems worth at least 1,500 gp)',
    duration: '10 days',
    source: "Player's Handbook",
  },
  {
    id: '387',
    name: 'Create Undead',
    slug: 'create-undead',
    description:
      'You can cast this spell only at night. Choose up to three corpses of Medium or Small humanoids within range. Each corpse becomes a ghoul under your control. The DM has game statistics for these creatures.\n\nAs a bonus action on each of your turns, you can mentally command any creature you animated with this spell if the creature is within 120 feet of you (if you control multiple creatures, you can command any or all of them at the same time, issuing the same command to each one). You decide what action the creature will take and where it will move during its next turn, or you can issue a general command, such as to guard a particular chamber or corridor. If you issue no commands, the creature only defends itself against hostile creatures. Once given an order, the creature continues to follow it until its task is complete.\n\nThe creature is under your control for 24 hours, after which it stops obeying any command you have given it. To maintain control of the creature for another 24 hours, you must cast this spell on the creature before the current 24-hour period ends. This use of the spell reasserts your control over up to three creatures you have animated with this spell, rather than animating new ones.\n\n',
    level: 6,
    school: 'NECROMANCY',
    castingTime: '1 minute',
    range: '10 feet',
    verbal: true,
    somatic: true,
    material: true,
    materialCost:
      '(one clay pot filled with grave dirt, one clay pot filled with brackish water, and one 150 gp black onyx stone for each corpse)',
    duration: 'Instantaneous',
    source: "Player's Handbook",
    upcastInfo:
      'When you cast this spell using a 7th-level spell slot, you can animate or reassert control over four ghouls. When you cast this spell using an 8th-level spell slot, you can animate or reassert control over five ghouls or two ghasts or wights. When you cast this spell using a 9th-level spell slot, you can animate or reassert control over six ghouls, three ghasts or wights, or two mummies.',
  },
  {
    id: '388',
    name: 'Disintegrate',
    slug: 'disintegrate',
    description:
      'A thin green ray springs from your pointing finger to a target that you can see within range. The target can be a creature, an object, or a creation of magical force, such as the wall created by wall of force.\n\nA creature targeted by this spell must make a Dexterity saving throw. On a failed save, the target takes 10d6 + 40 force damage. The target is disintegrated if this damage leaves it with 0 hit points.\n\nA disintegrated creature and everything it is wearing and carrying, except magic items, are reduced to a pile of fine gray dust. The creature can be restored to life only by means of a true resurrection or a wish spell.\n\nThis spell automatically disintegrates a Large or smaller nonmagical object or a creation of magical force. If the target is a Huge or larger object or creation of force, this spell disintegrates a 10-foot-cube portion of it. A magic item is unaffected by this spell.\n\n',
    level: 6,
    school: 'TRANSMUTATION',
    castingTime: '1 action',
    range: '60 feet',
    verbal: true,
    somatic: true,
    material: true,
    materialCost: '(a lodestone and a pinch of dust)',
    duration: 'Instantaneous',
    source: "Player's Handbook",
    upcastInfo:
      'When you cast this spell using a spell slot of 7th level or higher, the damage increases by 3d6 for each slot level above 6th.',
  },
  {
    id: '390',
    name: 'Eyebite',
    slug: 'eyebite',
    description:
      'For the spell’s duration, your eyes become an inky void imbued with dread power. One creature of your choice within 60 feet of you that you can see must succeed on a Wisdom saving throw or be affected by one of the following effects of your choice for the duration. On each of your turns until the spell ends, you can use your action to target another creature but can’t target a creature again if it has succeeded on a saving throw against this casting of eyebite.\n\n',
    level: 6,
    school: 'NECROMANCY',
    castingTime: '1 action',
    range: 'Self',
    verbal: true,
    somatic: true,
    material: false,
    duration: 'Concentration, up to 1 minute',
    source: "Player's Handbook",
    options: [
      'Asleep. The target falls unconscious. It wakes up if it takes any damage or if another creature uses its action to shake the sleeper awake.',
      'Panicked. The target is frightened of you. On each of its turns, the frightened creature must take the Dash action and move away from you by the safest and shortest available route, unless there is nowhere to move. If the target moves to a place at least 60 feet away from you where it can no longer see you, this effect ends.',
      'Sickened. The target has disadvantage on attack rolls and ability checks. At the end of each of its turns, it can make another Wisdom saving throw. If it succeeds, the effect ends.',
    ],
  },
  {
    id: '391',
    name: 'Find the Path',
    slug: 'find-the-path',
    description:
      'This spell allows you to find the shortest, most direct physical route to a specific fixed location that you are familiar with on the same plane of existence. If you name a destination on another plan of existence, a destination that moves (such as a mobile fortress), or a destination that isn’t specific (such as "a green dragon’s lair”), the spell fails.\n\nFor the duration, as long as you are on the same plane of existence as the destination, you know how far it is and in what direction it lies. While you are traveling there, whenever you are presented with a choice of paths along the way, you automatically determine which path is the shortest and most direct route (but not necessarily the safest route) to the destination.\n\n',
    level: 6,
    school: 'DIVINATION',
    castingTime: '1 minute',
    range: 'Self',
    verbal: true,
    somatic: true,
    material: true,
    materialCost:
      '(a set of divinatory tools – such as bones, ivory sticks, cards, teeth, or carved runes – worth 100 gp, and an object from the location you wish to find)',
    duration: 'Concentration, up to 1 day',
    source: "Player's Handbook",
  },
  {
    id: '392',
    name: 'Flesh to Stone',
    slug: 'flesh-to-stone',
    description:
      "You attempt to turn one creature that you can see within range into stone. If the target's body is made of flesh, the creature must make a Constitution saving throw. On a failed save, it is restrained as its flesh begins to harden. On a successful save, the creature isn’t affected.\n\nA creature restrained by this spell must make another Constitution saving throw at the end of each of its turns. If it successfully saves against this spell three times, the spell ends. If it fails saves three times, it is turned to stone and subjected to the petrified condition for the duration. The successes and failures don’t need to be consecutive; keep track of both until the target collects three of a kind.\n\nIf the creature is physically broken while petrified, it suffers from similar deformities if it reverts to its original state. If you maintain your concentration on this spell for the entire possible duration, the creature is turned to stone until the effect is removed.\n\n",
    level: 6,
    school: 'TRANSMUTATION',
    castingTime: '1 action',
    range: '60 feet',
    verbal: true,
    somatic: true,
    material: true,
    materialCost: '(a pinch of lime, water, and earth)',
    duration: 'Concentration, up to 1 minute',
    source: "Player's Handbook",
  },
  {
    id: '393',
    name: 'Forbiddance',
    slug: 'forbiddance',
    description:
      'You create a ward against magical travel that protects up to 40,000 square feet of floor space to a height of 30 feet above the floor. For the duration, creatures can’t teleport into the area or use portals, such as those created by the gate spell, to enter the area. The spell proofs the area against planar travel, and therefore prevents creatures from accessing the area by way of the Astral Plane, Ethereal Plane, Feywild, Shadowfell, or the plane shift spell.\n\nIn addition, the spell damages types of creatures that you choose when you cast it. Choose one or more of the following: celestials, elementals, fey, fiends, and undead. When a chosen creature enters the spell’s area for the first time on a turn or starts its turn there, the creature takes 5d10 radiant or necrotic damage (your choice when you cast this spell).\n\nWhen you cast this spell, you can designate a password. A creature that speaks the password as it enters the area takes no damage from the spell.\n\nThis spell’s area can’t overlap with the area of another forbiddance spell. If you cast forbiddance every day for 30 days in the same location, the spell lasts until it is dispelled, and the material components are consumed on the last casting.\n\n',
    level: 6,
    school: 'ABJURATION',
    castingTime: '10 minutes',
    range: 'Touch',
    verbal: true,
    somatic: true,
    material: true,
    materialCost:
      '(a sprinkling of holy water, rare incense, and powdered ruby worth at least 1,000 gp)',
    duration: '1 day',
    source: "Player's Handbook",
  },
  {
    id: '407',
    name: 'Freezing Sphere',
    slug: 'freezing-sphere',
    description:
      'A frigid globe of cold energy streaks from your fingertips to a point of your choice within range, where it explodes in a 60-foot-radius sphere. Each creature within the area must make a Constitution saving throw. On a failed save, a creature takes 10d6 cold damage. On a successful save, it takes half as much damage.\n\nIf the globe strikes a body of water or a liquid that is principally water (not including water-based creatures), it freezes the liquid to a depth of 6 inches over an area 30 feet square. This ice lasts for 1 minute. Creatures that were swimming on the surface of frozen water are trapped in the ice. A trapped creature can use an action to make a Strength check against your spell save DC to break free.\n\nYou can refrain from firing the globe after completing the spell, if you wish. A small globe about the size of a sling stone, cool to the touch, appears in your hand. At any time, you or a creature you give the globe to can throw the globe (to a range of 40 feet) or hurl it with a sling (to the sling’s normal range). It shatters on impact, with the same effect as the normal casting of the spell. You can also set the globe down without shattering it. After 1 minute, if the globe hasn’t already shattered, it explodes.\n\n',
    level: 6,
    school: 'EVOCATION',
    castingTime: '1 action',
    range: '300 feet',
    verbal: true,
    somatic: true,
    material: true,
    materialCost: '(a small crystal sphere)',
    duration: 'Instantaneous',
    source: "Player's Handbook",
    upcastInfo:
      'When you cast this spell using a spell slot of 7th level or higher, the damage increases by 1d6 for each slot level above 6th.',
  },
  {
    id: '396',
    name: 'Harm',
    slug: 'harm',
    description:
      'You unleash a virulent disease on a creature that you can see within range. The target must make a Constitution saving throw. On a failed save, it takes 14d6 necrotic damage, or half as much damage on a successful save. The damage can’t reduce the target’s hit points below 1. If the target fails the saving throw, its hit point maximum is reduced for 1 hour by an amount equal to the necrotic damage it took. Any effect that removes a disease allows a creature’s hit point maximum to return to normal before that time passes.\n\n',
    level: 6,
    school: 'NECROMANCY',
    castingTime: '1 action',
    range: '60 feet',
    verbal: true,
    somatic: true,
    material: false,
    duration: 'Instantanous',
    source: "Player's Handbook",
  },
  {
    id: '397',
    name: 'Heal',
    slug: 'heal',
    description:
      'Choose a creature that you can see within range. A surge of positive energy washes through the creature, causing it to regain 70 hit points. The spell also ends blindness, deafness, and any diseases affecting the target. This spell has no effect on constructs or undead.\n\n',
    level: 6,
    school: 'EVOCATION',
    castingTime: '1 action',
    range: '60 feet',
    verbal: true,
    somatic: true,
    material: false,
    duration: 'Instantaneous',
    source: "Player's Handbook",
    upcastInfo:
      'When you cast this spell using a spell slot of 7th level or higher, the amount of healing increases by 10 for each slot level above 6th.',
  },
  {
    id: '398',
    name: "Heroes' Feast",
    slug: 'heroes-feast',
    description:
      'You bring forth a great feast, including magnificent food and drink. The feast takes 1 hour to consume and disappears at the end of that time, and the beneficial effects don’t set in until this hour is over. Up to twelve creatures can partake of the feast.\n\nA creature that partakes of the feast gains several benefits. The creature is cured of all diseases and poison, becomes immune to poison and being frightened, and makes all Wisdom saving throws with advantage. Its hit point maximum also increases by 2d10, and it gains the same number of hit points. These benefits last for 24 hours.\n\n',
    level: 6,
    school: 'CONJURATION',
    castingTime: '10 minutes',
    range: '30 feet',
    verbal: true,
    somatic: true,
    material: true,
    materialCost:
      '(a gem-encrusted bowl worth at least 1,000 gp, which the spell consumes)',
    duration: 'Instantaneous',
    source: "Player's Handbook",
  },
  {
    id: '389',
    name: 'Instant Summons',
    slug: 'instant-summons',
    description:
      'You touch an object weighing 10 pounds or less whose longest dimension is 6 feet or less. The spell leaves an invisible mark on its surface and invisibly inscribes the name of the item on the sapphire you use as the material component. Each time you cast this spell, you must use a different sapphire.\n\nAt any time thereafter, you can use your action to speak the item’s name and crush the sapphire. The item instantly appears in your hand regardless of physical or planar distances, and the spell ends. If another creature is holding or carrying the item, crushing the sapphire doesn’t transport the item to you, but instead you learn who the creature possessing the object is and roughly where that creature is located at that moment.\n\nDispel Magic or a similar effect successfully applied to the sapphire ends this spell’s effect.\n\n',
    level: 6,
    school: 'CONJURATION',
    castingTime: '1 minute',
    range: 'Touch',
    verbal: true,
    somatic: true,
    material: true,
    materialCost: '(a sapphire worth 1,000 gp)',
    duration: 'Until dispelled',
    source: "Player's Handbook",
  },
  {
    id: '408',
    name: 'Irresistible Dance',
    slug: 'irresistible-dance',
    description:
      'Choose one creature that you can see within range. The target begins a comic dance in place: shuffling, tapping its feet, and capering for the duration. Creatures that can’t be charmed are immune to this spell.\n\nA dancing creature must use all its movement to dance without leaving its space and has disadvantage on Dexterity saving throws and attack rolls. While the target is affected by this spell, other creatures have advantage on attack rolls against it. As an action, a dancing creature makes a Wisdom saving throw to regain control of itself. On a successful save, the spell ends.\n\n',
    level: 6,
    school: 'ENCHANTMENT',
    castingTime: '1 action',
    range: '30 feet',
    verbal: true,
    somatic: false,
    material: false,
    duration: 'Concentration, up to 1 minute',
    source: "Player's Handbook",
  },
  {
    id: '403',
    name: 'Magic Jar',
    slug: 'magic-jar',
    description:
      'Your body falls into a catatonic state as your soul leaves it and enters the container you used for the spell’s material component. While your soul inhabits the container, you are aware of your surroundings as if you were in the container’s space. You can’t move or use reactions. The only action you can take is to project your soul up to 100 feet out of the container, either returning to your living body (and ending the spell) or attempting to possess a humanoids body.\n\nYou can attempt to possess any humanoid within 100 feet of you that you can see (creatures warded by a protection from evil and good or magic circle spells can’t be possessed). The target must make a Charisma saving throw. On a failure, your soul moves into the target’s body, and the target’s soul becomes trapped in the container. On a success, the target resists your efforts to possess it, and you can’t attempt to possess it again for 24 hours.\n\nOnce you possess a creature’s body, you control it. Your game statistics are replaced by the statistics of the creature though you retain your alignment and your Intelligence, Wisdom, and Charisma scores. You retain the benefit of your own class features. If the target has any class levels, you can’t use any of its class features.\n\nMeanwhile, the possessed creature’s soul can perceive from the container using its own senses, but it can’t move or take actions at all.\n\nWhile possessing a body, you can use your action to return from the host body to the container if it is within 100 feet of you, returning the host creature’s soul to its body. If the host body dies while you’re in it, the creature dies, and you must make a Charisma saving throw against your own spellcasting DC. On a success, you return to the container if it is within 100 feet of you. Otherwise, you die.\n\nIf the container is destroyed or the spell ends, your soul immediately returns to your body. If your body is more than 100 feet away from you, or if your body is dead when you attempt to return to it, you die. If another creature’s soul is in the container when it is destroyed, the creature’s soul returns to its body if the body is alive and within 100 feet. Otherwise, that creature dies.\n\nWhen the spell ends, the container is destroyed.\n\n',
    level: 6,
    school: 'NECROMANCY',
    castingTime: '1 minute',
    range: 'Self',
    verbal: true,
    somatic: true,
    material: true,
    materialCost:
      '(a gem, crystal, reliquary, or some other ornamental container worth at least 500 gp)',
    duration: 'Until dispelled',
    source: "Player's Handbook",
  },

  {
    id: '404',
    name: 'Mass Suggestion',
    slug: 'mass-suggestion',
    description:
      'You suggest a course of activity (limited to a sentence or two) and magically influence up to twelve creatures of your choice that you can see within range and that can hear and understand you. Creatures that can’t be charmed are immune to this effect. The suggestion must be worded in such a manner as to make the course of action sound reasonable. Asking the creature to stab itself, throw itself onto a spear, immolate itself, or do some other obviously harmful act automatically negates the effect of the spell.\n\nEach target must make a Wisdom saving throw. On a failed save, it pursues the course of action you described to the best of its ability. The suggested course of action can continue for the entire duration. If the suggested activity can be completed in a shorter time, the spell ends when the subject finishes what it was asked to do.\n\nYou can also specify conditions that will trigger a special activity during the duration. For example, you might suggest that a group of soldiers give all their money to the first beggar they meet. If the condition isn’t met before the spell ends, the activity isn’t performed.\n\nIf you or any of your companions damage a creature affected by this spell, the spell ends for that creature.\n\n',
    level: 6,
    school: 'ENCHANTMENT',
    castingTime: '1 action',
    range: '60 feet',
    verbal: true,
    somatic: false,
    material: true,
    materialCost:
      '(a snake’s tongue and either a bit of honeycomb or a drop of sweet oil)',
    duration: '24 hours',
    source: "Player's Handbook",
    upcastInfo:
      'When you cast this spell using a 7th-level spell slot, the duration is 10 days. When you use an 8th-level spell slot, the duration is 30 days. When you use a 9th-level spell slot, the duration is a year and a day.',
  },
  {
    id: '406',
    name: 'Move Earth',
    slug: 'move-earth',
    description:
      'Choose an area of terrain no larger than 40 feet on a side within range. You can reshape dirt, sand, or clay in the area in any manner you choose for the duration. You can raise or lower the area’s elevation, create or fill in a trench, erect or flatten a wall, or form a pillar. The extent of any such changes can’t exceed half the area’s largest dimension. So, if you affect a 40-foot square, you can create a pillar up to 20 feet high, raise or lower the square’s elevation by up to 20 feet, dig a trench up to 20 feet deep, and so on. It takes 10 minutes for these changes to complete.\n\nAt the end of every 10 minutes you spend concentrating on the spell, you can choose a new area of terrain to affect.\n\nBecause the terrain’s transformation occurs slowly, creatures in the area can’t usually be trapped or injured by the ground’s movement.\n\nThis spell can’t manipulate natural stone or stone construction. Rocks and structures shift to accommodate the new terrain. If the way you shape the terrain would make a structure unstable, it might collapse.\n\nSimilarly, this spell doesn’t directly affect plant growth. The moved earth carries any plants along with it.\n\n',
    level: 6,
    school: 'TRANSMUTATION',
    castingTime: '1 action',
    range: '120 feet',
    verbal: true,
    somatic: true,
    material: true,
    materialCost:
      '(an iron blade and a small bag containing a mixture of soils –&nbsp;clay, loam, and sand)',
    duration: 'Concentration, up to 2 hours',
    source: "Player's Handbook",
  },
  {
    id: '409',
    name: 'Planar Ally',
    slug: 'planar-ally',
    description:
      'You beseech an otherworldly entity for aid. The being must be known to you: a god, a primordial, a demon prince, or some other being of cosmic power. That entity sends a celestial, an elemental, or a fiend loyal to it to aid you, making the creature appear in an unoccupied space within range. If you know a specific creature’s name, you can speak that name when you cast this spell to request that creature, though you might get a different creature anyway (DM’s choice).\n\nWhen the creature appears, it is under no compulsion to behave in any particular way. You can ask the creature to perform a service in exchange for payment, but it isn’t obliged to do so. The requested task could range from simple (fly us across the chasm, or help us fight a battle) to complex (spy on our enemies, or protect us during our foray into the dungeon). You must be able to communicate with the creature to bargain for its services.\n\nPayment can take a variety of forms. A celestial might require a sizable donation of gold or magic items to an allied temple, while a fiend might demand a living sacrifice or a gift of treasure. Some creatures might exchange their service for a quest undertaken by you.\n\nAs a rule of thumb, a task that can be measured in minutes requires a payment worth 100 gp per minute. A task measured in hours requires 1,000 gp per hour. And a task measured in days (up to 10 days) requires 10,000 gp per day. The DM can adjust these payments based on the circumstances under which you cast the spell. If the task is aligned with the creature’s ethos, the payment might be halved or even waived. Nonhazardous tasks typically require only half the suggested payment, while especially dangerous tasks might require a greater gift. Creatures rarely accept tasks that seem suicidal.\n\nAfter the creature completes the task, or when the agreed-upon duration of service expires, the creature returns to its home plane after reporting back to you, if appropriate to the task and if possible. If you are unable to agree on a price for the creature’s service, the creature immediately returns to its home plane.\n\nA creature enlisted to join your group counts as a member of it, receiving a full share of experience points awarded.\n\n',
    level: 6,
    school: 'CONJURATION',
    castingTime: '10 minutes',
    range: '60 feet',
    verbal: true,
    somatic: true,
    material: false,
    duration: 'Instantaneous',
    source: "Player's Handbook",
  },
  {
    id: '411',
    name: 'Programmed Illusion',
    slug: 'programmed-illusion',
    description:
      'You create an illusion of an object, a creature, or some other visible phenomenon within range that activates when a specific condition occurs. The illusion is imperceptible until then. It must be no larger than a 30-foot cube, and you decide when you cast the spell how the illusion behaves and what sounds it makes. This scripted performance can last up to 5 minutes.\n\nWhen the condition you specify occurs, the illusion springs into existence and performs in the manner you described. Once the illusion finishes performing, it disappears and remains dormant for 10 minutes. After this time, the illusion can be activated again.\n\nThe triggering condition can be as general or as detailed as you like, though it must be based on visual or audible conditions that occur within 30 feet of the area. For example, you could create an illusion of yourself to appear and warn off others who attempt to open a trapped door, or you could set the illusion to trigger only when a creature says the correct word or phrase.\n\nPhysical interaction with the image reveals it to be an illusion, because things can pass through it. A creature that uses its action to examine the image can determine that it is an illusion with a successful Intelligence (Investigation) check against your spell save DC. If a creature discerns the illusion for what it is, the creature can see through the image, and any noise it makes sounds hollow to the creature.\n\n',
    level: 6,
    school: 'ILLUSION',
    castingTime: '1 action',
    range: '120 feet',
    verbal: true,
    somatic: true,
    material: true,
    materialCost: '(a bit of fleece and jade dust worth at least 25 gp)',
    duration: 'Until dispelled',
    source: "Player's Handbook",
  },
  {
    id: '413',
    name: 'Sunbeam',
    slug: 'sunbeam',
    description:
      'A beam of brilliant light flashes out from your hand in a 5-foot-wide, 60-foot-line. Each creature in the line must make a Constitution saving throw. On a failed save, a creature takes 6d8 radiant damage and is blinded until your next turn. On a successful save, it takes half as much damage and isn’t blinded by this spell. Undead and oozes have disadvantage on this saving throw.\n\nYou can create a new line of radiance as your action on any turn until the spell ends.\n\nFor the duration, a mote of brilliant radiance shines in your hand. It sheds bright light in a 30-foot radius and dim light for an additional 30 feet. The light is sunlight.\n\n',
    level: 6,
    school: 'EVOCATION',
    castingTime: '1 action',
    range: 'Self (60-foot line)',
    verbal: true,
    somatic: true,
    material: true,
    materialCost: '(a magnifying glass)',
    duration: 'Concentration, up to 1 minute',
    source: "Player's Handbook",
  },
  {
    id: '416',
    name: 'Transport via Plants',
    slug: 'transport-via-plants',
    description:
      'This spell creates a magical link between a Large or larger inanimate plant within range and another plant, at any distance, on the same plane of existence. You must have seen or touched the destination plant at least once before. For the duration, any creature can step into the target plant and exit from the destination plant by using 5 feet of movement.\n\n',
    level: 6,
    school: 'CONJURATION',
    castingTime: '1 action',
    range: '10 feet',
    verbal: true,
    somatic: true,
    material: false,
    duration: '1 round',
    source: "Player's Handbook",
  },
  {
    id: '417',
    name: 'True Seeing',
    slug: 'true-seeing',
    description:
      'This spell gives the willing creature you touch the ability to see things as they actually are. For the duration, the creature has truesight, notices secret doors hidden by magic, and can see into the Ethereal Plane, all out to a range of 120 feet.\n\n',
    level: 6,
    school: 'DIVINATION',
    castingTime: '1 action',
    range: 'Touch',
    verbal: true,
    somatic: true,
    material: true,
    materialCost:
      '(an ointment for the eyes that costs 25 gp; is made from mushroom powder, saffron, and fat; and is consumed by the spell)',
    duration: '1 hour',
    source: "Player's Handbook",
  },

  {
    id: '418',
    name: 'Wall of Ice',
    slug: 'wall-of-ice',
    description:
      'You create a wall of ice on a solid surface within range. You can form it into a hemispherical dome or a sphere with radius of up to 10 feet, or you can shape a flat surface made up of ten 10-foot-square panels. Each panel must be contiguous with another panel. In any form, the wall is 1 foot thick and lasts for the duration.\n\nIf the wall cuts through a creature’s space when it appears, the creature within its area is pushed to one side of the wall and must make a Dexterity saving throw. On a failed save, the creature takes 10d6 cold damage, or half as much damage on a successful save.\n\nThe wall is an object that can be damaged and thus breached. It has AC 12 and 30 hit points per 10-foot section, and it is vulnerable to fire damage. Reducing a 10-foot section of wall to 0 hit points destroys it and leaves behind a sheet of frigid air in the space the wall occupied. A creature moving through the sheet of frigid air for the first time on a turn must make a Constitution saving throw. The creature takes 5d6 cold damage on a failed save, or half as much damage on a successful one.\n\n',
    level: 6,
    school: 'EVOCATION',
    castingTime: '1 action',
    range: '120 feet',
    verbal: true,
    somatic: true,
    material: true,
    materialCost: '(a small piece of quartz)',
    duration: 'Concentration, up to 10 minutes',
    source: "Player's Handbook",
    upcastInfo:
      'When you cast this spell using a spell slot of 7th level or higher, the damage the wall deals when it appears increases by 2d6, and the damage from passing through the sheet of frigid air increases by 1d6, for each slot level above 6th.',
  },
  {
    id: '419',
    name: 'Wall of Thorns',
    slug: 'wall-of-thorns',
    description:
      'You create a wall of tough, pliable, tangled brush bristling with needle-sharp thorns. The wall appears within range on a solid surface and lasts for the duration. You choose to make the wall up to 60 feet long, 10 feet high, and 5 feet thick or a circle that has a 20-foot diameter and is up to 20 feet high and 5 feet thick. The wall blocks line of sight.\n\nWhen the wall appears, each creature within its area must make a Dexterity saving throw. On a failed save, a creature takes 7d8 piercing damage, or half as much damage on a successful save.\n\nA creature can move through the wall, albeit slowly and painfully. For every 1 foot a creature moves through the wall, it must spend 4 feet of movement. Furthermore, the first time a creature enters the wall on a turn or ends its turn there, the creature must make a Dexterity saving throw. It takes 7d8 slashing damage on a failed save, or half as much on a successful save.\n\n',
    level: 6,
    school: 'CONJURATION',
    castingTime: '1 action',
    range: '120 feet',
    verbal: true,
    somatic: true,
    material: true,
    materialCost: '(a handful of thorns)',
    duration: 'Concentration, up to 10 minutes',
    source: "Player's Handbook",
    upcastInfo:
      'When you cast this spell using a spell slot of 7th level or higher, both types of damage increase by 1d8 for each slot level above 6th.',
  },

  {
    id: '420',
    name: 'Wind Walk',
    slug: 'wind-walk',
    description:
      'You and up to ten willing creatures you can see within range assume a gaseous form for the duration, appearing as wisps of cloud. While in this cloud form, a creature has a flying speed of 300 feet and has resistance to damage from nonmagical weapons. The only actions a creature can take in this form are the Dash action or to revert to its normal form.\n\nReverting takes 1 minute, during which time a creature is incapacitated and can’t move. Until the spell ends, a creature can revert to cloud form, which also requires the 1-minute transformation.\n\nIf a creature is in cloud form and flying when the effect ends, the creature descends 60 feet per round for 1 minute until it lands, which it does safely. If it can’t land after 1 minute, the creature falls the remaining distance.\n\n',
    level: 6,
    school: 'TRANSMUTATION',
    castingTime: '1 minute',
    range: '30 feet',
    verbal: true,
    somatic: true,
    material: true,
    materialCost: '(fire and holy water)',
    duration: '8 hours',
    source: "Player's Handbook",
  },
  {
    id: '421',
    name: 'Word of Recall',
    slug: 'word-of-recall',
    description:
      'You and up to five willing creatures within 5 feet of you instantly teleport to a previously designated sanctuary. You and any creatures that teleport with you appear in the nearest unoccupied space to the spot you designated when you prepared your sanctuary (see below). If you cast this spell without first preparing a sanctuary, the spell has no effect.\n\nYou must designate a sanctuary by casting this spell within a location, such as a temple, dedicated to or strongly linked to your deity. If you attempt to cast the spell in this manner in an area that isn’t dedicated to your deity, the spell has no effect.\n\n',
    level: 6,
    school: 'CONJURATION',
    castingTime: '1 action',
    range: '5 feet',
    verbal: true,
    somatic: false,
    material: false,
    duration: 'Instantaneous',
    source: "Player's Handbook",
  },
];

export default SpellSixthLevelSeed;
