import { Prisma } from '@prisma/client';

const SpellThirdLevelSeed: Prisma.SpellCreateManyInput[] = [
  {
    id: '207',
    name: 'Animate Dead',
    slug: 'animate-dead',
    description:
      'This spell creates an undead servant. Choose a pile of bones or a corpse of a Medium or Small humanoid within range. Your spell imbues the target with a foul mimicry of life, raising it as an undead creature. The target becomes a skeleton if you chose bones or a zombie if you chose a corpse (the DM has the creature’s game statistics).\n\nOn each of your turns, you can use a bonus action to mentally command any creature you made with this spell if the creature is within 60 feet of you (if you control multiple creatures, you can command any or all of them at the same time, issuing the same command to each one). You decide what action the creature will take and where it will move during its next turn, or you can issue a general command, such as to guard a particular chamber or corridor. If you issue no commands, the creature only defends itself against hostile creatures. Once given an order, the creature continues to follow it until its task is complete.\n\nThe creature is under your control for 24 hours, after which it stops obeying any command you’ve given it. To maintain the control of the creature for another 24 hours, you must cast this spell on the creature again before the current 24-hour period ends. This use of the spell reasserts your control over up to four creatures you have animated with this spell, rather than animating a new one.\n\n',
    level: 3,
    school: 'NECROMANCY',
    castingTime: '1 minute',
    range: '10 feet',
    verbal: true,
    somatic: true,
    material: true,
    materialCost:
      '(a drop of blood, a piece of flesh, and a pinch of bone dust)',
    duration: 'Instantaneous',
    source: "Player's Handbook",
    postTableData: '',
    extendedTable: [],
    options: [],
    upcastInfo:
      'When you cast this spell using a spell slot of 4th level or higher, you animate or reassert control over two additional undead creatures for each slot level above 3rd. Each of the creatures must come from a different corpse or pile of bones.',
  },

  {
    id: '211',
    name: 'Bestow Curse',
    slug: 'bestow-curse',
    description:
      'You touch a creature, and that creature must succeed on a Wisdom saving throw or become cursed for the duration of the spell. When you cast this spell, choose the nature of the curse from the following options:\n\n',
    level: 3,
    school: 'NECROMANCY',
    castingTime: '1 action',
    range: 'Touch',
    verbal: true,
    somatic: true,
    material: false,
    materialCost: '',
    duration: 'Concentration, up to 1 minute',
    source: "Player's Handbook",
    postTableData: '',
    extendedTable: [],
    options: [
      'Choose one ability score. While cursed, the target has disadvantage on ability checks and saving throws made with that ability score.',
      'While cursed, the target has disadvantage on attack rolls against you.',
      'While cursed, the target must make a Wisdom saving throw at the start of each of its turns. If it fails, it wastes its action that turn doing nothing.',
      'While the target is cursed, your attacks and spells deal an extra 1d8 necrotic damage to the target.',
    ],
    upcastInfo:
      "If you cast this spell using a spell slot of 4th level or higher, the duration is concentration, up to 10 minutes. If you use a spell slot of 5th level or higher, the duration is 8 hours. If you use a spell slot of 7th level or higher, the duration is 24 hours. If you use a 9th level spell slot, the spell lasts until it is dispelled. Using a spell slot of 5th level or higher grants a duration that doesn't require concentration.",
  },
  {
    id: '213',
    name: 'Blink',
    slug: 'blink',
    description:
      "Roll a d20 at the end of each of your turns for the duration of the spell. On a roll of 11 or higher, you vanish from your current plane of existence and appear in the Ethereal Plane (the spell fails and the casting is wasted if you were already on that plane).\n\nAt the start of your next turn, and when the spell ends if you are on the Ethereal Plane, you return to an unoccupied space of your choice that you can see within 10 feet of the space you vanished from. If no unoccupied space is available within that range, you appear in the nearest unoccupied space (chosen at random if more that one space is equally near). You can dismiss this spell as an action.\n\nWhile on the Ethereal Plane, you can see and hear the plane you originated from, which is cast in shades of gray, and you can't see anything more than 60 feet away. You can only affect and be affected by other creatures on the Ethereal Plane. Creature that aren't there can't perceive you or interact with you, unless they have the ability to do so.\n\n",
    level: 3,
    school: 'TRANSMUTATION',
    castingTime: '1 action',
    range: 'Self',
    verbal: true,
    somatic: true,
    material: false,
    duration: '1 minute',
    source: "Player's Handbook",
  },
  {
    id: '216',
    name: 'Clairvoyance',
    slug: 'clairvoyance',
    description:
      'You create an invisible sensor within range in a location familiar to you (a place you have visited or seen before) or in an obvious location that is unfamiliar to you (such as behind a door, around a corner, or in a grove of trees). The sensor remains in place for the duration, and it can’t be attacked or otherwise interacted with.\n\nWhen you cast the spell, you choose seeing or hearing. You can use the chosen sense through the sensor as if you were in its space. As your action, you can switch between seeing and hearing. A creature that can see the sensor (such as a creature benefitting from see invisibility or truesight) sees a luminous, intangible orb about the size of your fist.\n\n',
    level: 3,
    school: 'DIVINATION',
    castingTime: '10 minutes',
    range: '1 mile',
    verbal: true,
    somatic: true,
    material: true,
    materialCost:
      '(a focus worth at least 100 gp, either a jeweled horn for hearing or a glass eye for seeing)',
    duration: 'Concentration, up to 10 minutes',
    source: "Player's Handbook",
  },
  {
    id: '217',
    name: 'Conjure Animals',
    slug: 'conjure-animals',
    description:
      'You summon fey spirits that take the form of beasts and appear in unoccupied spaces that you can see within range.\n\nChoose one of the following options for what appears:\n\n',
    level: 3,
    school: 'CONJURATION',
    castingTime: '1 action',
    range: '60 feet',
    verbal: true,
    somatic: true,
    material: false,
    duration: 'Concentration, up to 1 hour',
    source: "Player's Handbook",
    postTableData:
      'Each beast is also considered fey, and it disappears when it drops to 0 hit points or when the spell ends.\n\nThe summoned creatures are friendly to you and your companions. Roll initiative for the summoned creatures as a group, which has its own turns. They obey any verbal commands that you issue to them (no action required by you). If you don’t issue any commands to them, they defend themselves from hostile creatures, but otherwise take no actions. The DM has the creatures’ statistics.\n\n',
    options: [
      'One beast of challenge rating 2 or lower',
      'Two beasts of challenge rating 1 or lower',
      'Four beasts of challenge rating 1/2 or lower',
      'Eight beasts of challenge rating 1/4 or lower',
    ],
    upcastInfo:
      'When you cast this spell using certain higher-level spell slots, you choose one of the summoning options above, and more creatures appear: twice as many with a 5th-level slot, three times as many with a 7th-level slot, and four times as many with a 9th-level slot.',
  },
  {
    id: '219',
    name: 'Counterspell',
    slug: 'counterspell',
    description:
      'You attempt to interrupt a creature in the process of casting a spell. If the creature is casting a spell of 3rd level or lower, its spell fails and has no effect. If it is casting a spell of 4th level or higher, make an ability check using your spellcasting ability. The DC equals 10 + the spell’s level. On a success, the creature’s spell fails and has no effect.\n\n',
    level: 3,
    school: 'ABJURATION',
    castingTime:
      '1 reaction, which you take when you see a creature within 60 feet of you casting a spell',
    range: '60 feet',
    verbal: false,
    somatic: true,
    material: false,
    duration: 'Instantaneous',
    source: "Player's Handbook",
    upcastInfo:
      'When you cast this spell using a spell slot of 4th level or higher, the interrupted spell has no effect if its level is less than or equal to the level of the spell slot you used.',
  },
  {
    id: '220',
    name: 'Create Food and Water',
    slug: 'create-food-and-water',
    description:
      'You create 45 pounds of food and 30 gallons of water on the ground or in containers within range, enough to sustain up to fifteen humanoids or five steeds for 24 hours. The food is bland but nourishing, and spoils if uneaten after 24 hours. The water is clean and doesn’t go bad.\n\n',
    level: 3,
    school: 'CONJURATION',
    castingTime: '1 action',
    range: '30 feet',
    verbal: true,
    somatic: true,
    material: false,
    duration: 'Instantaneous',
    source: "Player's Handbook",
  },
  {
    id: '222',
    name: 'Daylight',
    slug: 'daylight',
    description:
      'A 60-foot-radius sphere of light spreads out from a point you choose within range. The sphere is bright light and sheds dim light for an additional 60 feet.\n\nIf you chose a point on an object you are holding or one that isn’t being worn or carried, the light shines from the object with and moves with it. Completely covering the affected object with an opaque object, such as a bowl or a helm, blocks the light.\n\nIf any of this spell’s area overlaps with an area of darkness created by a spell of 3rd level or lower, the spell that created the darkness is dispelled.\n\n',
    level: 3,
    school: 'EVOCATION',
    castingTime: '1 action',
    range: '60 feet',
    verbal: true,
    somatic: true,
    material: false,
    duration: '1 hour',
    source: "Player's Handbook",
  },
  {
    id: '223',
    name: 'Dispel Magic',
    slug: 'dispel-magic',
    description:
      "Choose any creature, object, or magical effect within range. Any spell of 3rd level or lower on the target ends. For each spell of 4th level or higher on the target, make an ability check using your spellcasting ability. The DC equals 10 + the spell's level. On a successful check, the spell ends.\n\n",
    level: 3,
    school: 'ABJURATION',
    castingTime: '1 action',
    range: '120 feet',
    verbal: true,
    somatic: true,
    material: false,
    duration: 'Instantaneous',
    source: "Player's Handbook",
    upcastInfo:
      "When you cast this spell using a spell slot of 4th level or higher, you automatically end the effects of a spell on the target if the spell's level is equal to or less than the level of the spell slot you used.",
  },
  {
    id: '228',
    name: 'Fear',
    slug: 'fear',
    description:
      'You project a phantasmal image of a creature’s worst fears. Each creature in a 30-foot cone must succeed on a Wisdom saving throw or drop whatever it is holding and become frightened for the duration.\n\nWhile frightened by this spell, a creature must take the Dash action and move away from you by the safest available route on each of its turns, unless there is nowhere to move. If the creature ends its turn in a location where it doesn’t have line of sight to you, the creature can make a Wisdom saving throw. On a successful save, the spell ends for that creature.\n\n',
    level: 3,
    school: 'ILLUSION',
    castingTime: '1 action',
    range: 'Self (30-foot cone)',
    verbal: true,
    somatic: true,
    material: true,
    materialCost: '(a white feather or the heart of a hen)',
    duration: 'Concentration, up to 1 minute',
    source: "Player's Handbook",
  },
  {
    id: '230',
    name: 'Fireball',
    slug: 'fireball',
    description:
      'A bright streak flashes from your pointing finger to a point you choose within range then blossoms with a low roar into an explosion of flame. Each creature in a 20-foot radius must make a Dexterity saving throw. A target takes 8d6 fire damage on a failed save, or half as much damage on a successful one. The fire spreads around corners. It ignites flammable objects in the area that aren’t being worn or carried.\n\n',
    level: 3,
    school: 'EVOCATION',
    castingTime: '1 action',
    range: '150 feet',
    verbal: true,
    somatic: true,
    material: true,
    materialCost: '(a tiny ball of bat guano and sulfur)',
    duration: 'Instantaneous',
    source: "Player's Handbook",
    upcastInfo:
      'When you cast this spell using a spell slot of 4th level or higher, the damage increases by 1d6 for each slot level above 3rd.',
  },
  {
    id: '232',
    name: 'Fly',
    slug: 'fly',
    description:
      'You touch a willing creature. The target gains a flying speed of 60 feet for the duration. When the spell ends, the target falls if it is still aloft, unless it can stop the fall.\n\n',
    level: 3,
    school: 'TRANSMUTATION',
    castingTime: '1 action',
    range: 'Touch',
    verbal: true,
    somatic: true,
    material: true,
    materialCost: '(a wing feather from any bird)',
    duration: 'Concentration, up to 10 minutes',
    source: "Player's Handbook",
    upcastInfo:
      'When you cast this spell using a spell slot of 4th level or higher, you can target one additional creature for each slot level above 3rd.',
  },
  {
    id: '234',
    name: 'Gaseous Form',
    slug: 'gasious-form',
    description:
      'You transform a willing creature you touch, along with everything it’s wearing and carrying, into a misty cloud for the duration. The spell ends if the creature drops to 0 hit points. An incorporeal creature isn’t affected.\n\nWhile in this form, the target’s only method of movement is a flying speed of 10 feet. The target can enter and occupy the space of another creature. The target has resistance to nonmagical damage, and it has advantage on Strength, Dexterity, and Constitution saving throws. The target can pass through small holes, narrow openings, and even mere cracks, though it treats liquids as though they were solid surfaces. The target can’t fall and remains hovering in the air even when stunned or otherwise incapacitated.\n\nWhile in the form of a misty cloud, the target can’t talk or manipulate objects, and any objects it was carrying or holding can’t be dropped, used, or otherwise interacted with. The target can’t attack or cast spells.\n\n',
    level: 3,
    school: 'TRANSMUTATION',
    castingTime: '1 action',
    range: 'Touch',
    verbal: true,
    somatic: true,
    material: true,
    materialCost: '(a bit of gauze and a wisp of smoke)',
    duration: 'Concentration, up to 1 hour',
    source: "Player's Handbook",
  },
  {
    id: '235',
    name: 'Glyph of Warding',
    slug: 'glyph-of-warding',
    description:
      'When you cast this spell, you inscribe a glyph that creates a magical effect triggered by other creatures, either upon a surface (such as a table or a section of floor or wall) or within an object that can be closed (such as a book, a scroll, or a treasure chest) to conceal the glyph. The glyph can cover an area no larger than 10 feet in diameter. If the surface or object is moved more than 10 feet from where you cast this spell, the glyph is broken, and the spell ends without being triggered.\n\nThe glyph is nearly invisible and requires a successful Intelligence (Investigation) check against your spell save DC to be found.\n\nYou decide what triggers the glyph when you cast the spell. For glyphs inscribed on a surface, the most typical triggers include touching or standing on the glyph, removing another object covering the glyph, approaching within a certain distance of the glyph, or manipulating the object on which the glyph is inscribed. For glyphs inscribed within an object, the most common triggers include opening that object, approaching within a certain distance of the object, or seeing or reading the glyph. Once a glyph is triggered, this spell ends.\n\nYou can further refine the trigger so the spell activates only under certain circumstances or according to physical characteristics (such as height or weight), creature kind (for example, the ward could be set to affect aberrations or drow), or alignment. You can also set conditions for creatures that don’t trigger the glyph, such as those who say a certain password.\n\nWhen you inscribe the glyph, choose explosive runes or a spell glyph.\n\n',
    level: 3,
    school: 'ABJURATION',
    castingTime: '1 hour',
    range: 'Touch',
    verbal: true,
    somatic: true,
    material: true,
    materialCost:
      '(incense and powdered diamond worth at least 200 gp, which the spell consumes)',
    duration: 'Until dispelled or triggered',
    source: "Player's Handbook",
    upcastInfo:
      'When you cast this spell using a spell slot of 4th level or higher, the damage of an explosive runes glyph increases by 1d8 for each slot level above 3rd. If you create a spell glyph, you can store any spell of up to the same level as the slot you use for the glyph of warding.',
  },
  {
    id: '236',
    name: 'Haste',
    slug: 'haste',
    description:
      'Choose a willing creature that you can see within range. Until the spell ends, the target’s speed is doubled, it gains a +2 bonus to AC, it has advantage on Dexterity saving throws, and it gains an additional action on each of its turns. That action can be used only to take the Attack (one weapon attack only), Dash, Disengage, Hide, or Use an Object action.\n\nWhen the spell ends, the target can’t move or take actions until after its next turn, as a wave of lethargy sweeps over it.\n\n',
    level: 3,
    school: 'TRANSMUTATION',
    castingTime: '1 action',
    range: '30 feet',
    verbal: true,
    somatic: true,
    material: true,
    materialCost: '(a shaving of licorice root)',
    duration: 'Concentration, up to 1 minute',
    source: "Player's Handbook",
  },
  {
    id: '238',
    name: 'Hypnotic Pattern',
    slug: 'hypnotic-pattern',
    description:
      'You create a twisting pattern of colors that weaves through the air inside a 30-foot cube within range. The pattern appears for a moment and vanishes. Each creature in the area who sees the pattern must make a Wisdom saving throw. On a failed save, the creature becomes charmed for the duration. While charmed by this spell, the creature is incapacitated and has a speed of 0.\n\nThe spell ends for an affected creature if it takes any damage or if someone else uses an action to shake the creature out of its stupor.\n\n',
    level: 3,
    school: 'ILLUSION',
    castingTime: '1 action',
    range: '120 feet',
    verbal: false,
    somatic: true,
    material: true,
    materialCost:
      '(a glowing stick of incense or a crystal vial filled with phosphorescent material)',
    duration: 'Concentration, up to 1 minute',
    source: "Player's Handbook",
  },
  {
    id: '244',
    name: 'Lightning Bolt',
    slug: 'lightning-bolt',
    description:
      'A stroke of lightning forming a line of 100 feet long and 5 feet wide blasts out from you in a direction you choose. Each creature in the line must make a Dexterity saving throw. A creature takes 8d6 lightning damage on a failed save, or half as much damage on a successful one.\n\nThe lightning ignites flammable objects in the area that aren’t being worn or carried.\n\n',
    level: 3,
    school: 'EVOCATION',
    castingTime: '1 action',
    range: 'Self (100-foot line)',
    verbal: true,
    somatic: true,
    material: true,
    materialCost: '(a bit of fur and a rod of amber, crystal, or glass)',
    duration: 'Instantaneous',
    source: "Player's Handbook",
    upcastInfo:
      'When you cast this spell using a spell slot of 4th level or higher, the damage increases by 1d6 for each slot level above 3rd.',
  },
  {
    id: '245',
    name: 'Magic Circle',
    slug: 'magic-circle',
    description:
      'You create a 10-foot-radius, 20-foot-tall cylinder of magical energy centered on a point on the ground that you can see within range. Glowing runes appear wherever the cylinder intersects with the floor or other surface.\n\nChoose one or more of the following types of creatures: celestials, elementals, fey, fiends, or undead. The circle affects a creature of the chosen type in the following ways:\n\n',
    level: 3,
    school: 'ABJURATION',
    castingTime: '1 minute',
    range: '10 feet',
    verbal: true,
    somatic: true,
    material: true,
    materialCost:
      '(holy water or powdered silver and iron worth at least 100 gp, which the spell consumes)',
    duration: '1 hour',
    source: "Player's Handbook",
    postTableData:
      'When you cast this spell, you can elect to cause its magic to operate in the reverse direction, preventing a creature of the specified type from leaving the cylinder and protecting targets outside it.\n\n',
    options: [
      'The creature can’t willingly enter the cylinder by nonmagical means. If the creature tries to use teleportation or interplanar travel to do so, it must first succeed on a Charisma saving throw.',
      'The creature has disadvantage on attack rolls against targets within the cylinder.',
      'Targets within the cylinder can’t be charmed, frightened, or possessed by the creature.',
    ],
    upcastInfo:
      'When you cast this spell using a spell slot of 4th level or higher, the duration increases by 1 hour for each slot level above 3rd.',
  },

  {
    id: '247',
    name: 'Mass Healing Word',
    slug: 'mass-healing-word',
    description:
      'As you call out words of restoration, up to six creatures of your choice that you can see within range regain hit points equal to 1d4 + your spellcasting ability modifier. This spell has no effect on undead or constructs.\n\n',
    level: 3,
    school: 'EVOCATION',
    castingTime: '1 bonus action',
    range: '60 feet',
    verbal: true,
    somatic: false,
    material: false,
    duration: 'Instantaneous',
    source: "Player's Handbook",
    upcastInfo:
      'When you cast this spell using a spell slot of 4th level or higher, the healing increases by 1d4 for each slot level above 3rd.',
  },
  {
    id: '248',
    name: 'Meld into Stone',
    slug: 'meld-into-stone',
    description:
      'You step into a stone object or surface large enough to fully contain your body, melding yourself and all the equipment you carry with the stone for the duration. Using your movement, you step into the stone at a point you can touch. Nothing of your presence remains visible or otherwise detectable by nonmagical senses.\n\nWhile merged with the stone, you can’t see what occurs outside it, and any Wisdom (Perception) checks you make to hear sounds outside it are made with disadvantage. You remain aware of the passage of time and can cast spells on yourself while merged in the stone. You can use your movement to leave the stone where you entered it, which ends the spell. You otherwise can’t move.\n\nMinor physical damage to the stone doesn’t harm you, but its partial destruction or a change in its shape (to the extent that you no longer fit within it) expels you and deals 6d6 bludgeoning damage to you. The stone’s complete destruction (or transmutation into a different substance) expels you and deals 50 bludgeoning damage to you. If expelled, you fall prone in an unoccupied space closest to where you first entered.\n\n',
    level: 3,
    school: 'TRANSMUTATION',
    castingTime: '1 action',
    range: 'Touch',
    verbal: true,
    somatic: true,
    material: false,
    duration: '8 hours',
    source: "Player's Handbook",
  },
  {
    id: '251',
    name: 'Nondetection',
    slug: 'non-detection',
    description:
      'For the duration, you hide a target that you touch from divination magic. The target can be a willing creature or a place or an object no larger than 10 feet in any dimension. The target can’t be targeted by any divination magic or perceived through magical scrying sensors.\n\n',
    level: 3,
    school: 'ABJURATION',
    castingTime: '1 action',
    range: 'Touch',
    verbal: true,
    somatic: true,
    material: true,
    materialCost:
      '(a pinch of diamond dust worth 25 gp sprinkled over the target, which the spell consumes)',
    duration: '8 hours',
    source: "Player's Handbook",
  },

  {
    id: '252',
    name: 'Phantom Steed',
    slug: 'phantom-steed',
    description:
      'A Large quasi-real, horselike creature appears on the ground in an unoccupied space of your choice within range. You decide the creature’s appearance, but it is equipped with a saddle, bit, and bridle. Any of the equipment created by the spell vanishes in a puff of smoke if it is carried more than 10 feet away from the steed.\n\nFor the duration, you or a creature you choose can ride the steed. The creature uses the statistics for a riding horse, except it has a speed of 100 feet and can travel 10 miles in an hour, or 13 miles at a fast pace. When the spell ends, the steed gradually fades, giving the rider 1 minute to dismount. The spell ends if you use an action to dismiss it or if the steed takes any damage.\n\n',
    level: 3,
    school: 'ILLUSION',
    castingTime: '1 minute',
    range: '30 feet',
    verbal: true,
    somatic: true,
    material: false,
    duration: '1 hour',
    source: "Player's Handbook",
  },
  {
    id: '253',
    name: 'Plant Growth',
    slug: 'plant-growth',
    description:
      'This spell channels vitality into plants within a specific area. There are two possible uses for the spell, granting either immediate or long-term benefits.\n\nIf you cast this spell using 1 action, choose a point within range. All normal plants in a 100-foot radius centered on that point become thick and overgrown. A creature moving through the area must spend 4 feet of movement for every 1 foot it moves.\n\nYou can exclude one or more areas of any size within the spell’s area from being affected.\n\nIf you cast this spell over 8 hours, you enrich the land. All plants in a half-mile radius centered on a point within range become enriched for 1 year. The plants yield twice the normal amount of food when harvested.\n\n',
    level: 3,
    school: 'TRANSMUTATION',
    castingTime: '1 action or 8 hours',
    range: '150 feet',
    verbal: true,
    somatic: true,
    material: false,
    duration: 'Instantaneous',
    source: "Player's Handbook",
  },
  {
    id: '254',
    name: 'Protection from Energy',
    slug: 'protection-from-energy',
    description:
      'For the duration, the willing creature you touch has resistance to one damage type of your choice: acid, cold, fire, lightning, or thunder.\n\n',
    level: 3,
    school: 'ABJURATION',
    castingTime: '1 action',
    range: 'Touch',
    verbal: true,
    somatic: true,
    material: false,
    duration: 'Concentration, up to 1 hour',
    source: "Player's Handbook",
  },
  {
    id: '256',
    name: 'Remove Curse',
    slug: 'remove-curse',
    description:
      'At your touch, all curses affecting one creature or object end. If the object is a cursed magic item, its curse remains, but the spell breaks its owner’s attunement to the object so it can be removed or discarded.\n\n',
    level: 3,
    school: 'ABJURATION',
    castingTime: '1 action',
    range: 'Touch',
    verbal: true,
    somatic: true,
    material: false,
    duration: 'Instantaneous',
    source: "Player's Handbook",
  },
  {
    id: '257',
    name: 'Revivify',
    slug: 'revivify',
    description:
      'You touch a creature that has died within the last minute. That creature returns to life with 1 hit point. This spell can’t return to life a creature that has died of old age, nor can it restore any missing body parts.\n\n',
    level: 3,
    school: 'NECROMANCY',
    castingTime: '1 action',
    range: 'Touch',
    verbal: true,
    somatic: true,
    material: true,
    materialCost: '(diamonds worth 300 gp, which the spell consumes)',
    duration: 'Instantaneous',
    source: "Player's Handbook",
  },
  {
    id: '258',
    name: 'Sending',
    slug: 'sending',
    description:
      "You send a short message of twenty-five words or less to a creature with which you are familiar. The creature hears the message in its mind, recognizes you as the sender if it knows you, and can answer in a like manner immediately. The spell enables creatures with Intelligence scores of at least 1 to understand the meaning of your message.\n\nYou can send the message across any distance and even to other planes of existence, but if the target is on a different plane than you, there is a 5 percent chance that the message doesn't arrive.\n\n",
    level: 3,
    school: 'EVOCATION',
    castingTime: '1 action',
    range: 'Unlimited',
    verbal: true,
    somatic: true,
    material: true,
    materialCost: '(a short piece of fine copper wire)',
    duration: '1 round',
    source: "Player's Handbook",
  },
  {
    id: '259',
    name: 'Sleet Storm',
    slug: 'sleet-storm',
    description:
      "Until the spell ends, freezing rain and sleet fall in a 20-foot-tall cylinder with a 40-foot radius centered on a point you choose within range. The area is heavily obscured, and exposed flames in the area are doused.\n\nThe ground in the area is covered with slick ice, making it difficult terrain. When a creature enters the spell’s area for the first time on a turn or starts its turn there, it must make a Dexterity saving throw. On a failed save, it falls prone.\n\nIf a creature starts its turn in the spell's area and is concentrating on a spell, the creature must make a successful Constitution saving throw against your spell save DC or lose concentration.\n\n",
    level: 3,
    school: 'CONJURATION',
    castingTime: '1 action',
    range: '120 feet',
    verbal: true,
    somatic: true,
    material: true,
    materialCost: '(a pinch of dust and a few drops of water)',
    duration: 'Concentration, up to 1 minute',
    source: "Player's Handbook",
  },
  {
    id: '260',
    name: 'Slow',
    slug: 'slow',
    description:
      'You alter time around up to six creatures of your choice in a 40-foot cube within range. Each target must succeed on a Wisdom saving throw or be affected by this spell for the duration.\n\nAn affected target’s speed is halved, it takes a -2 penalty to AC and Dexterity saving throws, and it can’t use reactions. On its turn, it can use either an action or a bonus action, not both. Regardless of the creature’s abilities or magic items, it can’t make more than one melee or ranged attack during its turn.\n\nIf the creature attempts to cast a spell with a casting time of 1 action, roll a d20. On an 11 or higher, the spell doesn’t take effect until the creature’s next turn, and the creature must use its action on that turn to complete the spell. If it can’t, the spell is wasted.\n\nA creature affected by this spell makes another Wisdom saving throw at the end of each of its turns. On a successful save, the effect ends for it.\n\n',
    level: 3,
    school: 'TRANSMUTATION',
    castingTime: '1 action',
    range: '120 feet',
    verbal: true,
    somatic: true,
    material: true,
    materialCost: '(a drop of molasses)',
    duration: 'Concentration, up to 1 minute',
    source: "Player's Handbook",
  },
  {
    id: '261',
    name: 'Speak with Dead',
    slug: 'speak-with-dead',
    description:
      'You grant the semblance of life and intelligence to a corpse of your choice within range, allowing it to answer the questions you pose. The corpse must still have a mouth and can’t be undead. The spell fails if the corpse was the target of this spell within the last 10 days.\n\nUntil the spell ends, you can ask the corpse up to five questions. The corpse knows only what it knew in life, including the languages it knew. Answers are usually brief, cryptic, or repetitive, and the corpse is under no compulsion to offer a truthful answer if you are hostile to it or it recognizes you as an enemy. This spell doesn’t return the creature’s soul to its body, only its animating spirit. Thus, the corpse can’t learn new information, doesn’t comprehend anything that has happened since it died, and can’t speculate about future events.\n\n',
    level: 3,
    school: 'NECROMANCY',
    castingTime: '1 action',
    range: '10 feet',
    verbal: true,
    somatic: true,
    material: true,
    materialCost: '(burning incense)',
    duration: '10 minutes',
    source: "Player's Handbook",
  },
  {
    id: '262',
    name: 'Speak with Plants',
    slug: 'speak-with-plants',
    description:
      'You imbue plants within 30 feet of you with limited sentience and animation, giving them the ability to communicate with you and follow your simple commands. You can question plants about events in the spell’s area within the past day, gaining information about creatures that have passed, weather, and other circumstances.\n\nYou can also turn difficult terrain caused by plant growth (such as thickets and undergrowth) into ordinary terrain that lasts for the duration. Or you can turn ordinary terrain where plants are present into difficult terrain that lasts for the duration, causing vines and branches to hinder pursuers, for example.\n\nPlants might be able to perform other tasks on your behalf, at the DM’s discretion. The spell doesn’t enable plants to uproot themselves and move about, but they can freely move branches, tendrils, and stalks.\n\nIf a plant creature is in the area, you can communicate with it as if you share a common language, but you gain no magical ability to influence it.\n\nThis spell can cause the plants created by the entangle spell to release a restrained creature.\n\n',
    level: 3,
    school: 'TRANSMUTATION',
    castingTime: '1 action',
    range: 'Self (30-foot radius)',
    verbal: true,
    somatic: true,
    material: false,
    duration: '10 minutes',
    source: "Player's Handbook",
  },
  {
    id: '263',
    name: 'Spirit Guardians',
    slug: 'spirit-guardians',
    description:
      'You call forth spirits to protect you. They flit around you to a distance of 15 feet for the duration. If you are good or neutral, their spectral form appears angelic or fey (your choice). If you are evil, they appear fiendish.\n\nWhen you cast this spell, you can designate any number of creatures you can see to be unaffected by it. An affected creature’s speed is halved in the area, and when the creature enters the area for the first time on a turn or starts its turn there, it must make a Wisdom saving throw. On a failed save, the creature takes 3d8 radiant damage (if you are good or neutral) or 3d8 necrotic damage (if you are evil). On a successful save, the creature takes half as much damage.\n\n',
    level: 3,
    school: 'CONJURATION',
    castingTime: '1 action',
    range: 'Self (15-foot-radius)',
    verbal: true,
    somatic: true,
    material: true,
    materialCost: '(a holy symbol)',
    duration: 'Concentration, up to 10 minutes',
    source: "Player's Handbook",
    upcastInfo:
      'When you cast this spell using a spell slot of 4th level or higher, the damage increases by 1d8 for each slot level above 3rd.',
  },
  {
    id: '265',
    name: 'Stinking Cloud',
    slug: 'stinking-cloud',
    description:
      'You create a 20-foot-radius sphere of yellow, nauseating gas centered on a point within range. The cloud spreads around corners, and its area is heavily obscured. The cloud lingers in the air for the duration.\n\nEach creature that is completely within the cloud at the start of its turn must make a Constitution saving throw against poison. On a failed save, the creature spends its action that turn retching and reeling. Creatures that don’t need to breathe or are immune to poison automatically succeed on this saving throw.\n\nA moderate wind (at least 10 miles per hour) disperses the cloud after 4 rounds. A strong wind (at least 20 miles per hour) disperses it after 1 round.\n\n',
    level: 3,
    school: 'CONJURATION',
    castingTime: '1 action',
    range: '90 feet',
    verbal: true,
    somatic: true,
    material: true,
    materialCost: '(a rotten egg or several skunk cabbage leaves)',
    duration: 'Concentration, up to 1 minute',
    source: "Player's Handbook",
  },
  {
    id: '241',
    name: 'Tiny Hut',
    slug: 'tiny-hut',
    description:
      "A 10-foot-radius immobile dome of force springs into existence around and above you and remains stationary for the duration. The spell ends if you leave its area.\n\nNine creatures of Medium size or smaller can fit inside the dome with you. The spell fails if its area includes a larger creature or more than nine creatures. Creatures and objects within the dome when you cast this spell can move through it freely. All other creatures and objects are barred from passing through it. Spells and other magical effects can't extend through the dome or be cast through it. The atmosphere inside the space is comfortable and dry, regardless of the weather outside.\n\nUntil the spell ends, you can command the interior to become dimly lit or dark. The dome is opaque from the outside, of any color you choose, but it is transparent from the inside.\n\n",
    level: 3,
    school: 'EVOCATION',
    castingTime: '1 minute',
    range: 'Self (10-foot-radius hemisphere)',
    verbal: true,
    somatic: true,
    material: true,
    materialCost: '(a small crystal bead)',
    duration: '8 hours',
    source: "Player's Handbook",
  },
  {
    id: '268',
    name: 'Tongues',
    slug: 'tongues',
    description:
      'This spell grants the creature you touch the ability to understand any spoken language it hears. Moreover, when the target speaks, any creature that knows at least one language and can hear the target understands what it says.\n\n',
    level: 3,
    school: 'DIVINATION',
    castingTime: '1 action',
    range: 'Touch',
    verbal: true,
    somatic: false,
    material: true,
    materialCost: '(a small clay model of a ziggurat)',
    duration: '1 hour',
    source: "Player's Handbook",
  },
  {
    id: '269',
    name: 'Vampiric Touch',
    slug: 'varpiric-touch',
    description:
      'The touch of your shadow-wreathed hand can siphon force from others to heal your wounds. Make a melee spell attack against a creature within your reach. On a hit, the target takes 3d6 necrotic damage, and you regain hit points equal to half the amount of necrotic damage dealt. Until the spell ends, you can make the attack again on each of your turns as an action.\n\n',
    level: 3,
    school: 'NECROMANCY',
    castingTime: '1 action',
    range: 'Self',
    verbal: true,
    somatic: true,
    material: false,
    duration: 'Concentration, up to 1 minute',
    source: "Player's Handbook",
    upcastInfo:
      'When you cast this spell using a spell slot of 4th level or higher, the damage increases by 1d6 for each slot level above 3rd.',
  },

  {
    id: '272',
    name: 'Water Breathing',
    slug: 'water-breathing',
    description:
      'This spell grants up to ten willing creatures you can see within range the ability to breathe underwater until the spell ends. Affected creatures also retain their normal mode of respiration.\n\n',
    level: 3,
    school: 'TRANSMUTATION',
    castingTime: '1 action',
    range: '30 feet',
    verbal: true,
    somatic: true,
    material: true,
    materialCost: '(a short reed or piece of straw)',
    duration: '24 hours',
    source: "Player's Handbook",
  },

  {
    id: '273',
    name: 'Water Walk',
    slug: 'water-walk',
    description:
      'This spell grants the ability to move across any liquid surface – such as water, acid, mud, snow, quicksand, or lava – as if it were harmless solid ground (creatures crossing molten lava can still take damage from the heat). Up to ten willing creatures you can see within range gain this ability for the duration.\n\nIf you target a creature submerged in a liquid, the spell carries the target to the surface of the liquid at a rate of 60 feet per round.\n\n',
    level: 3,
    school: 'TRANSMUTATION',
    castingTime: '1 action',
    range: '30 feet',
    verbal: true,
    somatic: true,
    material: true,
    materialCost: '(a piece of cork)',
    duration: '1 hour',
    source: "Player's Handbook",
  },

  {
    id: '274',
    name: 'Wind Wall',
    slug: 'wind-wall',
    description:
      'A wall of strong wind rises from the ground at a point you choose within range. You can make the wall up to 50 feet long, 15 feet high, and 1 foot thick. You can shape the wall in any way you choose so long as it makes one continuous path along the ground. The wall lasts for the duration.\n\nWhen the wall appears, each creature within its area must make a Strength saving throw. A creature takes 3d8 bludgeoning damage on a failed save, or half as much damage on a successful one.\n\nThe strong wind keeps fog, smoke, and other gases at bay. Small or smaller flying creatures or objects can’t pass through the wall. Loose, lightweight materials brought into the wall fly upward. Arrows, bolts, and other ordinary projectiles launched at targets behind the wall are deflected upward and automatically miss. (Boulders hurled by giants or siege engines, and similar projectiles, are unaffected.) Creatures in gaseous form can’t pass through it.\n\n',
    level: 3,
    school: 'EVOCATION',
    castingTime: '1 action',
    range: '120 feet',
    verbal: true,
    somatic: true,
    material: true,
    materialCost: '(a tiny fan and a feather of exotic origin)',
    duration: 'Concentration, up to 1 minute',
    source: "Player's Handbook",
  },
];

export default SpellThirdLevelSeed;
