import { src } from '@/lib/types/types';
import {
  Ability,
  DamageTypes,
  Prisma,
  SpellAttackRollType,
  SpellScaleType,
  SpellTargetType,
} from '@prisma/client';

const SpellSecondLevelSeed: Prisma.SpellCreateManyInput[] = [
  {
    id: '175',
    name: 'Acid Arrow',
    slug: 'acid-arrow',
    description:
      'A shimmering green arrow streaks toward a target within range and bursts in a spray of acid. Make a ranged spell attack against the target. On a hit, the target takes 4d4 acid damage immediately and 2d4 acid damage at the end of its next turn. On a miss, the arrow splashes the target with acid for half as much of the initial damage and no damage at the end of its next turn.\n\n',
    level: 2,
    spellScaleType: SpellScaleType.SPELL_LEVEL,
    spellTargetType: SpellTargetType.LINE,
    damageType: DamageTypes.ACID,
    spellTargetMaxAmount: 1,
    spellAttackRoll: SpellAttackRollType.RANGED,
    savingThrowAbility: Ability.DEX,
    levelScalingFormulas: [
      {
        description: 'Initial Damage',
        formulas: [
          {
            level: 2,
            formula: '4d4',
          },
          {
            level: 3,
            formula: '5d4',
          },
          {
            level: 4,
            formula: '6d4',
          },
          {
            level: 5,
            formula: '7d4',
          },
          {
            level: 6,
            formula: '8d4',
          },
          {
            level: 7,
            formula: '9d4',
          },
          {
            level: 8,
            formula: '10d4',
          },
          {
            level: 9,
            formula: '11d4',
          },
        ],
      },
      {
        description: 'Later Damage',
        formulas: [
          {
            level: 2,
            formula: '2d4',
          },
          {
            level: 3,
            formula: '3d4',
          },
          {
            level: 4,
            formula: '4d4',
          },
          {
            level: 5,
            formula: '5d4',
          },
          {
            level: 6,
            formula: '6d4',
          },
          {
            level: 7,
            formula: '7d4',
          },
          {
            level: 8,
            formula: '8d4',
          },
          {
            level: 9,
            formula: '9d4',
          },
        ],
      },
    ],
    school: 'EVOCATION',
    castingTime: '1 action',
    range: '90 feet',
    verbal: true,
    somatic: true,
    material: true,
    materialCost: '(powdered rhubarb leaf and an adder’s stomach)',
    duration: 'Instantaneous',
    source: src.SRD,
    upcastInfo:
      'When you cast this spell using a spell slot of 3rd level or higher, the damage (both initial and later) increases by 1d4 for each slot level above 2nd.',
  },
  {
    id: '125',
    name: 'Aid',
    slug: 'aid',
    description:
      'Your spell bolsters your allies with toughness and resolve. Choose up to three creatures within range. Each target’s hit point maximum and current hit points increase by 5 for the duration.\n\n',
    spellTargetMaxAmount: 3,
    spellTargetType: SpellTargetType.RANGE,
    level: 2,
    school: 'ABJURATION',
    castingTime: '1 action',
    range: '30 feet',
    verbal: true,
    somatic: true,
    material: true,
    materialCost: '(a tiny strip of white cloth)',
    duration: '8 hours',
    source: "Player's Handbook",
    spellScaleType: SpellScaleType.SPELL_LEVEL,
    spellScaleResultType: 'DAMAGE_OR_HEALING',
    levelScalingFormulas: [
      {
        description: 'Hit Points',
        formulas: [
          {
            level: 2,
            formula: '5',
          },
          {
            level: 3,
            formula: '10',
          },
          {
            level: 4,
            formula: '15',
          },
          {
            level: 5,
            formula: '20',
          },
          {
            level: 6,
            formula: '25',
          },
          {
            level: 7,
            formula: '30',
          },
          {
            level: 8,
            formula: '35',
          },
          {
            level: 9,
            formula: '40',
          },
        ],
      },
    ],

    upcastInfo:
      'When you cast this spell using a spell slot of 3rd level or higher, a target’s hit points increase by an additional 5 for each slot level above 2nd.',
  },
  {
    id: '127',
    name: 'Alter Self',
    slug: 'alter-self',
    unimplemented: true,
    description:
      'You assume a different form. When you cast the spell, choose one of the following options, the effects of which last for the duration of the spell. While the spell lasts, you can end one option as an action to gain the benefits of a different one.\n\n',
    level: 2,
    school: 'TRANSMUTATION',
    castingTime: '1 action',
    range: 'Self',
    verbal: true,
    somatic: true,
    material: false,
    duration: 'Concentration, up to 1 hour',
    source: "Player's Handbook",
  },

  {
    id: '128',
    name: 'Animal Messenger',
    slug: 'animal-messenger',
    description:
      'By means of this spell, you use an animal to deliver a message. Choose a Tiny beast you can see within range, such as a squirrel, a blue jay, or a bat. You specify a location, which you must have visited, and a recipient who matches a general description, such as “a man or woman dressed in the uniform of the town guard” or “a red-haired dwarf wearing a pointed hat.” You also speak a message of up to twenty-five words. The target beast travels for the duration of the spell toward the specified location, covering about 50 miles per 24 hours for a flying messenger, or 25 miles for other animals.\n\nWhen the messenger arrives, it delivers your message to the creature that you described, replicating the sound of your voice. The messenger speaks only to a creature matching the description you gave. If the messenger doesn’t reach its destination before the spell ends, the message is lost, and the beast makes its way back to where you cast this spell.\n\n',
    level: 2,
    school: 'ENCHANTMENT',
    castingTime: '1 action',
    range: '30 feet',
    spellTargetCreatureType: 'BEAST',
    verbal: true,
    somatic: true,
    material: true,
    materialCost: '(a morsel of food)',
    duration: '24 hours',
    source: "Player's Handbook",
    spellScaleResultType: 'DURATION',
    spellScaleType: 'SPELL_LEVEL',
    savingThrowAbility: 'WIS',
    upcastInfo:
      'If you cast this spell using a spell slot of 3rd level or higher, the duration of the spell increases by 48 hours for each slot level above 2nd.',
  },

  {
    id: '129',
    name: 'Arcane Lock',
    slug: 'arcane-lock',
    description:
      'You touch a closed door, window, gate, chest, or other entryway, and it becomes locked for the duration.\n\nWhile affected by this spell, the object is more difficult to break or force open; the DC to break it or pick any locks on it increases by 10.\n\n',
    level: 2,
    school: 'ABJURATION',
    castingTime: '1 action',
    range: 'Touch',
    verbal: true,
    somatic: true,
    material: true,
    materialCost: '(gold dust worth at least 25 gp, which the spell consumes)',
    duration: 'Until dispelled',
    source: "Player's Handbook",
  },
  {
    id: '180',
    name: "Arcanist's Magic Aura",
    slug: 'arcanists-magic-aura',
    description:
      'You place an illusion on a creature or an object you touch so that divination spells reveal false information about it. The target can be a willing creature or an object that isn’t being carried or worn by another creature.\n\nWhen you cast the spell, choose one or both of the following effects. The effect lasts for the duration. If you cast this spell on the same creature or object every day for 30 days, placing the same effect on it each time, the illusion lasts until it is dispelled.\n\n',
    level: 2,
    school: 'ILLUSION',
    castingTime: '1 action',
    range: 'Touch',
    verbal: true,
    somatic: true,
    material: true,
    materialCost: '(a small square of silk)',
    duration: '24 hours',
    source: "Player's Handbook",
  },

  {
    id: '130',
    name: 'Augury',
    slug: 'augury',
    description:
      'By casting gem-inlaid sticks, rolling dragon bones, laying out ornate cards, or employing some other divining tool, you receive an omen from an otherworldly entity about the results of a specific course of action that you plan to take within the next 30 minutes. The DM chooses from the following possible omens:\n\n',
    level: 2,
    school: 'DIVINATION',
    castingTime: '1 minute',
    range: 'Self',
    verbal: true,
    somatic: true,
    material: true,
    materialCost:
      '(specially marked sticks, bones, or similar tokens worth at least 25 gp)',
    duration: 'Instantaneous',
    source: "Player's Handbook",
    postTableData:
      'The spell doesn’t take into account any possible circumstances that might change the outcome, such as the casting of additional spells or the loss or gain of a companion. If you cast the spell two or more times before completing your next long rest, there is a cumulative 25 percent chance for each casting after the first that you get a random reading. The DM makes this roll in secret.\n\n',
    extendedTable: [],
    options: [
      'Weal, for good results',
      'Woe, for bad results',
      'Weal and woe, for both good and bad results',
      'Nothing, for results that aren’t especially good or bad',
    ],
    upcastInfo: '',
  },

  {
    id: '131',
    name: 'Barkskin',
    slug: '',
    description:
      'You touch a willing creature. Until the spell ends, the target’s skin has a rough, bark-like appearance, and the target’s AC can’t be less than 16, regardless of what kind of armor it is wearing.\n\n',
    level: 2,
    school: 'TRANSMUTATION',
    castingTime: '1 action',
    range: 'Touch',
    verbal: true,
    somatic: true,
    material: true,
    materialCost: '(a handful of oak bark)',
    duration: 'Concentration, up to 1 hour',
    source: "Player's Handbook",
    postTableData: '',
    extendedTable: [],
    options: [],
    upcastInfo: '',
  },
  {
    id: '133',
    name: 'Blindness/Deafness',
    slug: 'blindness-deafness',
    description:
      'You can blind or deafen a foe. Choose one creature that you can see within range to make a Constitution saving throw. If it fails, the target is either blinded or deafened (your choice) for the duration. At the end of each of its turns, the target can make a Constitution saving throw. On a success, the spell ends.\n\n',
    level: 2,
    school: 'NECROMANCY',
    castingTime: '1 action',
    range: '30 feet',
    verbal: true,
    somatic: false,
    material: false,
    duration: '1 minute',
    source: "Player's Handbook",

    upcastInfo:
      'When you cast this spell using a spell slot of 3rd level or higher, you can target one additional creature for each slot level above 2nd.',
  },

  {
    id: '134',
    name: 'Blur',
    slug: 'blur',
    description:
      "Your body becomes blurred, shifting and wavering to all who can see you. For the duration, any creature has disadvantage on attack rolls against you. An attacker is immune to this effect if it doesn't rely on sight, as with blindsight, or can see through illusions, as with truesight.\n\n",
    level: 2,
    school: 'ILLUSION',
    castingTime: '1 action',
    range: 'Self',
    verbal: true,
    somatic: false,
    material: false,
    duration: 'Concentration, up to 1 minute',
    source: "Player's Handbook",
  },

  {
    id: '137',
    name: 'Calm Emotions',
    slug: 'calm-emotions',
    description:
      'You attempt to suppress strong emotions in a group of people. Each humanoid in a 20-foot-radius sphere centered on a point you choose within range must make a Charisma saving throw; a creature can choose to fail this saving throw if it wishes. If a creature fails its saving throw, choose one of the following two effects. You can suppress any effect causing a target to be charmed or frightened. When this spell ends, any suppressed effect resumes, provided that its duration has not expired in the meantime.\n\nAlternatively, you can make a target indifferent about creatures of your choice that it is hostile toward. This indifference ends if the target is attacked or harmed by a spell or if it witnesses any of its friends being harmed. When the spell ends, the creature becomes hostile again, unless the DM rules otherwise.\n\n',
    level: 2,
    school: 'ENCHANTMENT',
    castingTime: '1 action',
    range: '60 feet',
    verbal: true,
    somatic: true,
    material: false,
    duration: 'Concentration, up to 1 minute',
    source: "Player's Handbook",
  },
  {
    id: '139',
    name: 'Continual Flame',
    slug: 'continual-flame',
    description:
      'A flame, equivalent in brightness to a torch, springs forth from an object that you touch. The effect looks like a regular flame, but it creates no heat and doesn’t use oxygen. A continual flame can be covered or hidden but not smothered or quenched.\n\n',
    level: 2,
    school: 'EVOCATION',
    castingTime: '1 action',
    range: 'Touch',
    verbal: true,
    somatic: true,
    material: true,
    materialCost: '(ruby dust worth 50 gp, which the spell consumes)',
    duration: 'Until dispelled',
    source: "Player's Handbook",
  },
  {
    id: '142',
    name: 'Darkness',
    slug: 'darkness',
    description:
      'Magical darkness spreads from a point you choose within range to fill a 15-foot radius sphere for the duration. The darkness spreads around corners. A creature with darkvision can’t see through this darkness, and nonmagical light can’t illuminate it.\n\nIf the point you choose is on an object you are holding or one that isn’t being worn or carried, the darkness emanates from the object and moves with it. Completely covering the source of the darkness with an opaque object, such as a bowl or a helm, blocks the darkness.\n\nIf any of this spell’s area overlaps with an area of light created by a spell of 2nd level or lower, the spell that created the light is dispelled.\n\n',
    level: 2,
    school: 'EVOCATION',
    castingTime: '1 action',
    range: '60 feet',
    verbal: true,
    somatic: false,
    material: true,
    materialCost: '(bat fur and a drop of pitch or piece of coal)',
    duration: 'Concentration, up to 10 minutes',
    source: "Player's Handbook",
  },
  {
    id: '143',
    name: 'Darkvision',
    slug: 'darkvision',
    description:
      'You touch a willing creature to grant it the ability to see in the dark. For the duration, that creature has darkvision out to a range of 60 feet.\n\n',
    level: 2,
    school: 'TRANSMUTATION',
    castingTime: '1 action',
    range: 'Touch',
    verbal: true,
    somatic: true,
    material: true,
    materialCost: '(either a pinch of dried carrot or an agate)',
    duration: '8 hours',
    source: "Player's Handbook",
  },
  {
    id: '144',
    name: 'Detect Thoughts',
    slug: 'detect-thoughts',
    description:
      'For the duration, you can read the thoughts of certain creatures. When you cast the spell and as your action on each turn until the spell ends, you can focus your mind on any one creature that you can see within 30 feet of you. If the creature you choose has an Intelligence of 3 or lower or doesn’t speak any language, the creature is unaffected.\n\nYou initially learn the surface thoughts of the creature—what is most on its mind in that moment. As an action, you can either shift your attention to another creature’s thoughts or attempt to probe deeper into the same creature’s mind. If you probe deeper, the target must make a Wisdom saving throw. If it fails, you gain insight into its reasoning (if any), its emotional state, and something that loom s large in its mind (such as something it worries over, loves, or hates). If it succeeds, the spell ends. Either way, the target knows that you are probing into its mind, and unless you shift your attention to another creature’s thoughts, the creature can use its action on its turn to make an Intelligence check contested by your Intelligence check; if it succeeds, the spell ends.\n\nQuestions verbally directed at the target creature naturally shape the course of its thoughts, so this spell is particularly effective as part of an interrogation.\n\nYou can also use this spell to detect the presence of thinking creatures you can’t see. When you cast the spell or as your action during the duration, you can search for thoughts within 30 feet of you. The spell can penetrate barriers, but 2 feet of rock, 2 inches of any metal other than lead, or a thin sheet of lead blocks you. You can’t detect a creature with an Intelligence of 3 or lower or one that doesn’t speak any language.\n\nOnce you detect the presence of a creature in this way, you can read its thoughts for the rest of the duration as described above, even if you can’t see it, but it must still be within range.\n\n',
    level: 2,
    school: 'DIVINATION',
    castingTime: '1 action',
    range: 'Self',
    verbal: true,
    somatic: true,
    material: true,
    materialCost: '(a copper piece)',
    duration: 'Concentration, up to 1 minute',
    source: "Player's Handbook",
  },
  {
    id: '148',
    name: 'Enhance Ability',
    slug: 'enhance-ability',
    description:
      'You touch a creature and bestow upon it a magical enhancement. Choose one of the following effects; the target gains the effect until the spell ends.\n\n',
    level: 2,
    school: 'TRANSMUTATION',
    castingTime: '1 action',
    range: 'Touch',
    verbal: true,
    somatic: true,
    material: true,
    materialCost: '(fur or a feather from a beast)',
    duration: 'Concentration, up to 1 hour',
    source: "Player's Handbook",
    options: [
      'Bear’s Endurance. The target has advantage on Constitution checks. It also gains 2d6 temporary hit points, which are lost when the spell ends.',
      'Bull’s Strength. The target has advantage on Strength checks, and their carrying capacity doubles.',
      'Cat’s Grace. The target has advantage on Dexterity checks. It also doesn’t take damage from falling 20 feet or less if it isn’t incapacitated.',
      'Eagle’s Splendor. The target has advantage on Charisma checks.',
      'Fox’s Cunning. The target has advantage on Intelligence checks.',
      'Owl’s Wisdom. The target has advantage on Wisdom checks.',
    ],
    upcastInfo:
      'When you cast this spell using a spell slot of 3rd level or higher, you can target one additional creature for each slot level above 2nd.',
  },
  {
    id: '149',
    name: 'Enlarge/Reduce',
    slug: 'enlarge-reduce',
    description:
      'You cause a creature or an object you can see within range to grow larger or smaller for the duration. Choose either a creature or an object that is neither worn nor carried. If the target is unwilling, it can make a Constitution saving throw. On a success, the spell has no effect.\n\nIf the target is a creature, everything it is wearing and carrying changes size with it. Any item dropped by an affected creature returns to normal size at once.\n\n',
    level: 2,
    school: 'TRANSMUTATION',
    castingTime: '1 action',
    range: '30 feet',
    verbal: true,
    somatic: true,
    material: true,
    materialCost: '(a pinch of powdered iron)',
    duration: 'Concentration, up to 1 minute',
    source: "Player's Handbook",
  },
  {
    id: '150',
    name: 'Enthrall',
    slug: 'enthrall',
    description:
      'You weave a distracting string of words, causing creatures of your choice that you can see within range and that can hear you to make a Wisdom saving throw. Any creature that can’t be charmed succeeds on this saving throw automatically, and if you or your companions are fighting a creature, it has advantage on the save. On a failed save, the target has disadvantage on Wisdom (Perception) checks made to perceive any creature other than you until the spell ends or until the target can no longer hear you. The spell ends if you are incapacitated or can no longer speak.\n\n',
    level: 2,
    school: 'ENCHANTMENT',
    castingTime: '1 action',
    range: '60 feet',
    verbal: true,
    somatic: true,
    material: false,
    duration: '1 minute',
    source: "Player's Handbook",
  },
  {
    id: '151',
    name: 'Find Steed',
    slug: 'find-steed',
    description:
      'You summon a spirit that assumes the form of an unusually intelligent, strong, and loyal steed, creating a long-lasting bond with it. Appearing in an unoccupied space within range, the steed takes on a form that you choose: a warhorse, a pony, a camel, an elk, or a mastiff. (Your DM might allow other animals to be summoned as steeds.) The steed has the statistics of the chosen form, though it is a celestial, fey, or fiend (your choice) instead of its normal type. Additionally, if your steed has an Intelligence of 5 or less, its Intelligence becomes 6, and it gains the ability to understand one language of your choice that you speak.\n\nYour steed serves you as a mount, both in combat and out, and you have an instinctive bond with it that allows you to fight as a seamless unit. While mounted on your steed, you can make any spell you cast that targets only you also target your steed.\n\nWhen the steed drops to 0 hit points, it disappears, leaving behind no physical form. You can also dismiss your steed at any time as an action, causing it to disappear. In either case, casting this spell again summons the same steed, restored to its hit point maximum.\n\nWhile your steed is within 1 mile of you, you can communicate with each other telepathically. You can’t have more than one steed bonded by this spell at a time. As an action, you can release the steed from its bond at any time, causing it to disappear.\n\n',
    level: 2,
    school: 'CONJURATION',
    castingTime: '10 minutes',
    range: '30 feet',
    verbal: true,
    somatic: true,
    material: false,
    duration: 'Instantaneous',
    source: "Player's Handbook",
  },
  {
    id: '152',
    name: 'Find Traps',
    slug: 'find-traps',
    description:
      'You sense the presence of any trap within range that is within line of sight.\n\nA trap, for the purpose of this spell, includes anything that would inflict a sudden or unexpected effect you consider harmful or undesirable, which was specifically intended as such by its creator. Thus, the spell would sense an area affected by the alarm spell, a glyph of warding, or a mechanical pit trap, but it would not reveal a natural weakness in the floor, an unstable ceiling, or a hidden sinkhole.\n\nThis spell merely reveals that a trap is present. You don’t learn the location of each trap, but you do learn the general nature of the danger posed by a trap you sense.\n\n',
    level: 2,
    school: 'DIVINATION',
    castingTime: '1 action',
    range: '120 feet',
    verbal: true,
    somatic: true,
    material: false,
    duration: 'Instantaneous',
    source: "Player's Handbook",
  },
  {
    id: '153',
    name: 'Flame Blade',
    slug: 'flame-blade',
    description:
      'You evoke a fiery blade in your free hand. The blade is similar in size and shape to a scimitar, and it lasts for the duration. If you let go of the blade, it disappears, but you can evoke the blade again as a bonus action.\n\nYou can use your action to make a melee spell attack with the fiery blade. On a hit, the target takes 3d6 fire damage. The flaming blade sheds bright light in a 10-foot radius and dim light for an additional 10 feet.\n\n',
    level: 2,
    school: 'EVOCATION',
    castingTime: '1 bonus action',
    range: 'Self',
    verbal: true,
    somatic: true,
    material: true,
    materialCost: '(a leaf of sumac)',
    duration: 'Concentration, up to 10 minutes',
    source: "Player's Handbook",
    upcastInfo:
      'When you cast this spell using a spell slot of 4th level or higher, the damage increases by 1d6 for every two slot levels above 2nd.',
  },
  {
    id: '154',
    name: 'Flaming Sphere',
    slug: 'flaming-sphere',
    description:
      'A 5-foot-diameter sphere of fire appears in an unoccupied space of your choice within range and lasts for the duration. Any creature that ends its turn within 5 feet of the sphere must make a Dexterity saving throw. The creature takes 2d6 fire damage on a failed save, or half as much damage on a successful one.\n\nAs a bonus action, you can move the sphere up to 30 feet. If you ram the sphere into a creature, that creature must make the saving throw against the sphere’s damage, and the sphere stops moving this turn.\n\nWhen you move the sphere, you can direct it over barriers up to 5 feet tall and jump it across pits up to 10 feet wide. The sphere ignites flammable objects not being worn or carried, and it sheds bright light in a 20-foot radius and dim light for an additional 20 feet.\n\n',
    level: 2,
    school: 'CONJURATION',
    castingTime: '1 action',
    range: '60 feet',
    verbal: true,
    somatic: true,
    material: true,
    materialCost:
      '(a bit of tallow, a pinch of brimstone, and a dusting of powdered iron)',
    duration: 'Concentration, up to 1 minute',
    source: "Player's Handbook",
    upcastInfo:
      'When you cast this spell using a spell slot of 3rd level or higher, the damage increases by 1d6 for each slot level above 2nd.',
  },
  {
    id: '157',
    name: 'Gentle Repose',
    slug: 'gentle-repose',
    description:
      'You touch a corpse or other remains. For the duration, the target is protected from decay and can’t become undead.\n\nThe spell also effectively extends the time limit on raising the target from the dead, since days spent under the influence of this spell don’t count against the time limit of spells such as raise dead.\n\n',
    level: 2,
    school: 'NECROMANCY',
    castingTime: '1 action',
    range: 'Touch',
    verbal: true,
    somatic: true,
    material: true,
    materialCost:
      '(a pinch of salt and one copper piece placed on each of the corpse’s eyes, which must remain there for the duration)',
    duration: '10 days',
    source: "Player's Handbook",
  },
  {
    id: '159',
    name: 'Gust of Wind',
    slug: 'gust-of-wind',
    description:
      'A line of strong wind 60 feet long and 10 feet wide blasts from you in a direction you choose for the spell’s duration. Each creature that starts its turn in the line must succeed on a Strength saving throw or be pushed 15 feet away from you in a direction following the line.\n\nAny creature in the line must spend 2 feet of movement for every 1 foot it moves when moving closer to you.\n\nThe gust disperses gas or vapor, and it extinguishes candles, torches, and similar unprotected flames in the area. It causes protected flames, such as those of lanterns, to dance wildly and has a 50 percent chance to extinguish them.\n\nAs a bonus action on each of your turns before the spell ends, you can change the direction in which the line blasts from you.\n\n',
    level: 2,
    school: 'EVOCATION',
    castingTime: '1 action',
    range: 'Self (60-foot line)',
    verbal: true,
    somatic: true,
    material: true,
    materialCost: '(a legume seed)',
    duration: 'Concentration, up to 1 minute',
    source: "Player's Handbook",
  },
  {
    id: '161',
    name: 'Heat Metal',
    slug: 'heat metal',
    description:
      'Choose a manufactured metal object, such as a metal weapon or a suit of heavy or medium metal armor, that you can see within range. You cause the object to glow red-hot. Any creature in physical contact with the object takes 2d8 fire damage when you cast the spell. Until the spell ends, you can use a bonus action on each of your subsequent turns to cause this damage again.\n\nIf a creature is holding or wearing the object and takes the damage from it, the creature must succeed on a Constitution saving throw or drop the object if it can. If it doesn’t drop the object, it has disadvantage on attack rolls and ability checks until the start of your next turn.\n\n',
    level: 2,
    school: 'TRANSMUTATION',
    castingTime: '1 action',
    range: '60 feet',
    verbal: true,
    somatic: true,
    material: true,
    materialCost: '(a piece of iron and a flame)',
    duration: 'Concentration, up to 1 minute',
    source: "Player's Handbook",
    upcastInfo:
      'When you cast this spell using a spell slot of 3rd level or higher, the damage increases by 1d8 for each slot level above 2nd.',
  },
  {
    id: '162',
    name: 'Hold Person',
    slug: 'hold-person',
    description:
      'Choose a humanoid that you can see within range. The target must succeed on a Wisdom saving throw or be paralyzed for the duration. At the end of each of its turns, the target can make another Wisdom saving throw. On a success, the spell ends on the target.\n\n',
    level: 2,
    school: 'ENCHANTMENT',
    castingTime: '1 action',
    range: '60 feet',
    verbal: true,
    somatic: true,
    material: true,
    materialCost: '(a small, straight piece of iron)',
    duration: 'Concentration, up to 1 minute',
    source: "Player's Handbook",
    upcastInfo:
      'When you cast this spell using a spell slot of 3rd level or higher, you can target one additional humanoid for each slot level above 2nd. The humanoids must be within 30 feet of each other when you target them.',
  },
  {
    id: '164',
    name: 'Invisibility',
    slug: 'invisibility',
    description:
      'A creature you touch becomes invisible until the spell ends. Anything the target is wearing or carrying is invisible as long as it is on the target’s person. The spell ends for a target that attacks or casts a spell.\n\n',
    level: 2,
    school: 'ILLUSION',
    castingTime: '1 action',
    range: 'Touch',
    verbal: true,
    somatic: true,
    material: true,
    materialCost: '(an eyelash encased in gum arabic)',
    duration: 'Concentration, up to 1 hour',
    source: "Player's Handbook",
    upcastInfo:
      'When you cast this spell using a spell slot of 3rd level or higher, you can target one additional creature for each slot level above 2nd.',
  },
  {
    id: '167',
    name: 'Knock',
    slug: 'knock',
    description:
      'Choose an object that you can see within range. The object can be a door, a box, a chest, a set of manacles, a padlock, or another object that contains a mundane or magical means that prevents access.\n\nA target that is held shut by a mundane lock or that is stuck or barred becomes unlocked, unstuck, or unbarred. If the object has multiple locks, only one of them is unlocked.\n\nIf you choose a target that is held shut with Arcane Lock, that spell is suppressed for 10 minutes, during which time the target can be opened and shut normally.\n\nWhen you cast the spell, a loud knock, audible from as far away as 300 feet, emanates from the target object.\n\n',
    level: 2,
    school: 'TRANSMUTATION',
    castingTime: '1 action',
    range: '60 feet',
    verbal: true,
    somatic: false,
    material: false,
    duration: 'Instantaneous',
    source: "Player's Handbook",
  },
  {
    id: '168',
    name: 'Lesser Restoration',
    slug: 'lesser-restoration',
    description:
      'You touch a creature and can end either one disease or one condition afflicting it. The condition can be blinded, deafened, paralyzed, or poisoned.\n\n',
    level: 2,
    school: 'ABJURATION',
    castingTime: '1 action',
    range: 'Touch',
    verbal: true,
    somatic: true,
    material: false,
    duration: 'Instantaneous',
    source: "Player's Handbook",
  },
  {
    id: '169',
    name: 'Levitate',
    slug: 'levitate',
    description:
      'One creature or loose object of your choice that you can see within range rises vertically, up to 20 feet, and remains suspended there for the duration. The spell can levitate a target that weighs up to 500 pounds. An unwilling creature that succeeds on a Constitution saving throw is unaffected.\n\nThe target can move only by pushing or pulling against a fixed object or surface within reach (such as a wall or a ceiling), which allows it to move as if it were climbing. You can change the target’s altitude by up to 20 feet in either direction on your turn. If you are the target, you can move up or down as part of your move. Otherwise, you can use your action to move the target, which must remain within the spell’s range.\n\nWhen the spell ends, the target floats gently to the ground if it is still aloft.\n\n',
    level: 2,
    school: 'TRANSMUTATION',
    castingTime: '1 action',
    range: '60 feet',
    verbal: true,
    somatic: true,
    material: true,
    materialCost:
      '(either a small leather loop or a piece of golden wire bent into a cup shape with a long shank on one end)',
    duration: 'Concentration, up to 10 minutes',
    source: "Player's Handbook",
  },
  {
    id: '170',
    name: 'Locate Animals or Plants',
    slug: 'locate-animals-or-plants',
    description:
      'Describe or name a specific kind of beast or plant. Concentrating on the voice of nature in your surroundings, you learn the direction and distance to the closest creature or plant of that kind within 5 miles, if any are present.\n\n',
    level: 2,
    school: 'DIVINATION',
    castingTime: '1 action',
    range: 'Self',
    verbal: true,
    somatic: true,
    material: true,
    materialCost: '(a bit of fur from a bloodhound)',
    duration: 'Instantaneous',
    source: "Player's Handbook",
  },
  {
    id: '171',
    name: 'Locate Object',
    slug: 'locate-object',
    description:
      'Describe or name an object that is familiar to you. You sense the direction to the object’s location, as long as that object is within 1,000 feet of you. If the object is in motion, you know the direction of its movement.\n\nThe spell can locate a specific object known to you, as long as you have seen it up close – within 30 feet – at least once. Alternatively, the spell can locate the nearest object of a particular kind, such as a certain kind of apparel, jewelry, furniture, tool, or weapon.\n\nThis spell can’t locate an object if any thickness of lead, even a thin sheet, blocks a direct path between you and the object.\n\n',
    level: 2,
    school: 'DIVINATION',
    castingTime: '1 action',
    range: 'Self',
    verbal: true,
    somatic: true,
    material: true,
    materialCost: '(a forked twig)',
    duration: 'Concentration, up to 10 minutes',
    source: "Player's Handbook",
  },
  {
    id: '172',
    name: 'Magic Mouth',
    slug: 'magic-mouth',
    description:
      'You implant a message within an object in range, a message that is uttered when a trigger condition is met. Choose an object that you can see and that isn’t being worn or carried by another creature. Then speak the message, which must be 25 words or less, though it can be delivered over as long as 10 minutes. Finally, determine the circumstance that will trigger the spell to deliver your message.\n\nWhen that circumstance occurs, a magical mouth appears on the object and recites the message in your voice and at the same volume you spoke. If the object you chose has a mouth or something that looks like a mouth (for example, the mouth of a statue), the magical mouth appears there so that words appear to come from the object’s mouth. When you cast this spell, you can have the spell end after it delivers its message, or it can remain and repeats its message whenever the trigger occurs.\n\nThe triggering circumstance can be as general or as detailed as you like, though it must be based on visual or audible conditions that occur within 30 feet of the object. For example, you could instruct the mouth to speak when any creature moves within 30 feet of the object or when a silver bell rings within 30 feet of it.\n\n',
    level: 2,
    school: 'ILLUSION',
    castingTime: '1 minute',
    range: '30 feet',
    verbal: true,
    somatic: true,
    material: true,
    materialCost:
      '(a small bit of honeycomb and jade dust worth at least 10 gp, which the spell consumes)',
    duration: 'Until dispelled',
    source: "Player's Handbook",
  },

  {
    id: '173',
    name: 'Magic Weapon',
    slug: 'magic-weapon',
    description:
      'You touch a nonmagical weapon. Until the spell ends, that weapon becomes a magic weapon with a +1 bonus to attack rolls and damage rolls.\n\n',
    level: 2,
    school: 'TRANSMUTATION',
    castingTime: '1 bonus action',
    range: 'Touch',
    verbal: true,
    somatic: true,
    material: false,
    duration: 'Concentration, up to 1 hour',
    source: "Player's Handbook",
    upcastInfo:
      'When you cast this spell using a spell slot of 4th level or higher, the bonus increases to +2. When you use a spell slot of 6th level or higher, the bonus increases to +3.',
  },
  {
    id: '177',
    name: 'Mirror Image',
    slug: 'mirror-image',
    description:
      'Three illusory duplicates of yourself appear in your space. Until the spell ends, the duplicates move with you and mimic your actions, shifting position so it’s impossible to track which image is real. You can use your action to dismiss the illusory duplicates.\n\nEach time a creature targets you with an attack during the spell’s duration, roll a d20 to determine whether the attack instead targets one of your duplicates.\n\nIf you have three duplicates, you must roll a 6 or higher to change the attack’s target to a duplicate. With two duplicates, you must roll an 8 or higher. With one duplicate, you must roll an 11 or higher.\n\nA duplicate’s AC equals 10 + your Dexterity modifier. If an attack hits a duplicate, the duplicate is destroyed. A duplicate can be destroyed only by an attack that hits it. It ignores all other damage and effects. The spell ends when all three duplicates are destroyed.\n\nA creature is unaffected by this spell if it can’t see, if it relies on senses other than sight, such as blindsight, or if it can perceive illusions as false, as with truesight.\n\n',
    level: 2,
    school: 'ILLUSION',
    castingTime: '1 action',
    range: 'Self',
    verbal: true,
    somatic: true,
    material: false,
    duration: '1 minute',
    source: "Player's Handbook",
  },
  {
    id: '178',
    name: 'Misty Step',
    slug: 'misty-step',
    description:
      'Briefly surrounded by silvery mist, you teleport up to 30 feet to an unoccupied space that you can see.\n\n',
    level: 2,
    school: 'CONJURATION',
    castingTime: '1 bonus action',
    range: 'Self',
    verbal: true,
    somatic: false,
    material: false,
    duration: 'Instantaneous',
    source: "Player's Handbook",
  },
  {
    id: '179',
    name: 'Moonbeam',
    slug: 'moonbeam',
    description:
      'A silvery beam of pale light shines down in a 5-foot radius, 40-foot-high cylinder centered on a point within range. Until the spell ends, dim light fills the cylinder.\n\nWhen a creature enters the spell’s area for the first time on a turn or starts its turn there, it is engulfed in ghostly flames that cause searing pain, and it must make a Constitution saving throw. It takes 2d10 radiant damage on a failed save, or half as much damage on a successful one.\n\nA shapechanger makes its saving throw with disadvantage. If it fails, it also instantly reverts to its original form and can’t assume a different form until it leaves the spell’s light.\n\nOn each of your turns after you cast this spell, you can use an action to move the beam up to 60 feet in any direction.\n\n',
    level: 2,
    school: 'EVOCATION',
    castingTime: '1 action',
    range: '120 feet',
    verbal: true,
    somatic: true,
    material: true,
    materialCost:
      '(several seeds of any moonseed plant and a piece of opalescent feldspar)',
    duration: 'Concentration, up to 1 minute',
    source: "Player's Handbook",
    upcastInfo:
      'When you cast this spell using a spell slot of 3rd level or higher, the damage increases by 1d10 for each slot level above 2nd.',
  },
  {
    id: '181',
    name: 'Pass Without Trace',
    slug: 'pass-without-trace',
    description:
      'A veil of shadows and silence radiates from you, masking you and your companions from detection. For the duration, each creature you choose within 30 feet of you (including you) has a +10 bonus to Dexterity (Stealth) checks and can’t be tracked except by magical means. A creature that receives this bonus leaves behind no tracks or other traces of its passage.\n\n',
    level: 2,
    school: 'ABJURATION',
    castingTime: '1 action',
    range: 'Self',
    verbal: true,
    somatic: true,
    material: true,
    materialCost:
      '(ashes from a burned leaf of mistletoe and a sprig of spruce)',
    duration: 'Concentration, up to 1 hour',
    source: "Player's Handbook",
  },
  {
    id: '183',
    name: 'Prayer of Healing',
    slug: 'prayer-of-healing',
    description:
      'Up to six creatures of your choice that you can see within range each regain hit points equal to 2d8 + your spellcasting ability modifier. This spell has no effect on undead or constructs.\n\n',
    level: 2,
    school: 'EVOCATION',
    castingTime: '10 minutes',
    range: '30 feet',
    verbal: true,
    somatic: false,
    material: false,
    duration: 'Instantaneous',
    source: "Player's Handbook",
    upcastInfo:
      'When you cast this spell using a spell slot of 3rd level or higher, the healing increases by 1d8 for each slot level above 2nd.',
  },
  {
    id: '184',
    name: 'Protection from Poison',
    slug: 'protection-from-poison',
    description:
      'You touch a creature. If it is poisoned, you neutralize the poison. If more than one poison afflicts the target, you neutralize one poison that you know is present, or you neutralize one at random.\n\nFor the duration, the target has advantage on saving throws against being poisoned, and it has resistance to poison damage.\n\n',
    level: 2,
    school: 'ABJURATION',
    castingTime: '1 action',
    range: 'Touch',
    verbal: true,
    somatic: true,
    material: false,
    duration: '1 hour',
    source: "Player's Handbook",
  },
  {
    id: '185',
    name: 'Ray of Enfeeblement',
    slug: 'ray-of-enfeeblement',
    description:
      'A black beam of enervating energy springs from your finger toward a creature within range. Make a ranged spell attack against the target. On a hit, the target deals only half damage with weapon attacks that use Strength until the spell ends.\n\nAt the end of each of the target’s turns, it can make a Constitution saving throw against the spell. On a success, the spell ends.\n\n',
    level: 2,
    school: 'NECROMANCY',
    castingTime: '1 action',
    range: '60 feet',
    verbal: true,
    somatic: true,
    material: false,
    duration: 'Concentration, up to 1 minute',
    source: "Player's Handbook",
  },
  {
    id: '187',
    name: 'Rope Trick',
    slug: 'rope-trick',
    description:
      'You touch a length of rope that is up to 60 feet long. One end of the rope then rises into the air until the whole rope hangs perpendicular to the ground. At the upper end of the rope, an invisible entrance opens to an extradimensional space that lasts until the spell ends.\n\nThe extradimensional space can be reached by climbing to the top of the rope. The space can hold as many as eight Medium or smaller creatures. The rope can be pulled into the space, making the rope disappear from view outside the space.\n\nAttacks and spells can’t cross through the entrance into or out of the extradimensional space, but those inside can see out of it as if through a 3-foot-by-5-foot window centered on the rope.\n\nAnything inside the extradimensional space drops out when the spell ends.\n\n',
    level: 2,
    school: 'TRANSMUTATION',
    castingTime: '1 action',
    range: 'Touch',
    verbal: true,
    somatic: true,
    material: true,
    materialCost: '(powdered corn extract and a twisted loop of parchment)',
    duration: '1 hour',
    source: "Player's Handbook",
  },
  {
    id: '188',
    name: 'Scorching Ray',
    slug: 'scorching-ray',
    description:
      'You create three rays of fire and hurl them at targets within range. You can hurl them at one target or several. Make a ranged spell attack for each ray. On a hit, the target takes 2d6 fire damage.\n\n',
    level: 2,
    school: 'EVOCATION',
    castingTime: '1 action',
    range: '120 feet',
    verbal: true,
    somatic: true,
    material: false,
    duration: 'Instantaneous',
    source: "Player's Handbook",
    upcastInfo:
      'When you cast this spell using a spell slot of 3rd level or higher, you create one additional ray for each slot level above 2nd.',
  },
  {
    id: '189',
    name: 'See Invisibility',
    slug: 'see-invisibility',
    description:
      'For the duration, you see invisible creatures and objects as if they were visible, and you can see into the Ethereal Plane. Ethereal creatures and objects appear ghostly and translucent.\n\n',
    level: 2,
    school: 'DIVINATION',
    castingTime: '1 action',
    range: 'Self',
    verbal: true,
    somatic: true,
    material: true,
    materialCost: '(a pinch of talc and a small sprinkling of powdered silver)',
    duration: '1 hour',
    source: "Player's Handbook",
  },
  {
    id: '191',
    name: 'Shatter',
    slug: 'shatter',
    description:
      'A sudden loud ringing noise, painfully intense, erupts from a point of your choice within range. Each creature in a 10-foot-radius sphere centered on that point must make a Constitution saving throw. A creature takes 3d8 thunder damage on a failed save, or half as much damage on a successful one. A creature made of inorganic material such as stone, crystal, or metal has disadvantage on this saving throw.\n\nA nonmagical object that isn’t being worn or carried also takes the damage if it’s in the spell’s area.\n\n',
    level: 2,
    school: 'EVOCATION',
    castingTime: '1 action',
    range: '60 feet',
    verbal: true,
    somatic: true,
    material: true,
    materialCost: '(a chip of mica)',
    duration: 'Instantaneous',
    source: "Player's Handbook",
    upcastInfo:
      'When you cast this spell using a spell slot of 3rd level or higher, the damage increases by 1d8 for each slot level above 2nd.',
  },
  {
    id: '192',
    name: 'Silence',
    slug: 'silence',
    description:
      'For the duration, no sound can be created within or pass through a 20-foot-radius sphere centered on a point you choose within range. Any creature or object entirely inside the sphere is immune to thunder damage, and creatures are deafened while entirely inside it. Casting a spell that includes a verbal component is impossible there.\n\n',
    level: 2,
    school: 'ILLUSION',
    castingTime: '1 action',
    range: '120 feet',
    verbal: true,
    somatic: true,
    material: false,
    duration: 'Concentration, up to 10 minutes',
    source: "Player's Handbook",
  },
  {
    id: '195',
    name: 'Spider Climb',
    slug: 'spider-climb',
    description:
      'Until the spell ends, one willing creature you touch gains the ability to move up, down, and across vertical surfaces and upside down along ceilings, while leaving its hands free. The target also gains a climbing speed equal to its walking speed.\n\n',
    level: 2,
    school: 'TRANSMUTATION',
    castingTime: '1 action',
    range: 'Touch',
    verbal: true,
    somatic: true,
    material: true,
    materialCost: '(a drop of bitumen and a spider)',
    duration: 'Concentration, up to 1 hour',
    source: "Player's Handbook",
  },
  {
    id: '196',
    name: 'Spike Growth',
    slug: 'spike-growth',
    description:
      'The ground in a 20-foot radius centered on a point within range twists and sprouts hard spikes and thorns. The area becomes difficult terrain for the duration. When a creature moves into or within the area, it takes 2d4 piercing damage for every 5 feet it travels.\n\nThe transformation of the ground is camouflaged to look natural. Any creature that can’t see the area at the time the spell is cast must make a Wisdom (Perception) check against your spell save DC to recognize the terrain as hazardous before entering it.\n\n',
    level: 2,
    school: 'TRANSMUTATION',
    castingTime: '1 action',
    range: '150 feet',
    verbal: true,
    somatic: true,
    material: true,
    materialCost:
      '(seven sharp thorns or seven small twigs, each sharpened to a point)',
    duration: 'Concentration, up to 10 minutes',
    source: "Player's Handbook",
  },
  {
    id: '197',
    name: 'Spiritual Weapon',
    slug: 'spiritual-weapon',
    description:
      'You create a floating, spectral weapon within range that lasts for the duration or until you cast this spell again.\n\nWhen you cast the spell, you can make a melee spell attack against a creature within 5 feet of the weapon. On a hit, the target takes force damage equal to 1d8 + your spellcasting ability modifier.\n\nAs a bonus action on your turn, you can move the weapon up to 20 feet and repeat the attack against a creature within 5 feet of it.\n\nThe weapon can take whatever form you choose. Clerics of deities who are associated with a particular weapon (as St. Cuthbert is known for his mace and Thor for his hammer) make this spell’s effect resemble that weapon.\n\n',
    level: 2,
    school: 'EVOCATION',
    castingTime: '1 bonus action',
    range: '60 feet',
    verbal: true,
    somatic: true,
    material: false,
    materialCost: '',
    duration: '1 minute',
    source: "Player's Handbook",
    upcastInfo:
      'When you cast this spell using a spell slot of 3rd level or higher, the damage increases by 1d8 for every two slot levels above the 2nd.',
  },
  {
    id: '198',
    name: 'Suggestion',
    slug: 'suggestion',
    description:
      'You suggest a course of activity (limited to a sentence or two) and magically influence a creature you can see within range that can hear and understand you. Creatures that can’t be charmed are immune to this effect. The suggestion must be worded in such a manner as to make the course of action sound reasonable. Asking the creature to stab itself, throw itself onto a spear, immolate itself, or do some other obviously harmful act ends the spell.\n\nThe target must make a Wisdom saving throw. On a failed save, it purses the course of action you described to the best of its ability. The suggested course of action can continue for the entire duration. If the suggested activity can be completed in a shorter time, the spell ends when the subject finishes what it was asked to do.\n\nYou can also specify conditions that will trigger a special activity during the duration. For example, you might suggest that a knight give her warhorse to the first beggar she meets. If the condition isn’t met before the spell expires, the activity isn’t preformed.\n\nIf you or any of your companions damage the target, the spell ends.\n\n',
    level: 2,
    school: 'ENCHANTMENT',
    castingTime: '1 action',
    range: '30 feet',
    verbal: true,
    somatic: false,
    material: true,
    materialCost:
      '(a snake’s tongue and either a bit of honeycomb or a drop of sweet oil)',
    duration: 'Concentration, up to 8 hours',
    source: "Player's Handbook",
  },

  {
    id: '201',
    name: 'Warding Bond',
    slug: 'warding-bond',
    description:
      'This spell wards a willing creature you touch and creates a mystic connection between you and the target until the spell ends.\n\nWhile the target is within 60 feet of you, it gains a +1 bonus to AC and saving throws, and it has resistance to all damage. Also, each time it takes damage, you take the same amount of damage.\n\nThe spell ends if you drop to 0 hit points or if you and the target become separated by more than 60 feet. It also ends if the spell is cast again on either of the connected creatures. You can also dismiss the spell as an action.\n\n',
    level: 2,
    school: 'ABJURATION',
    castingTime: '1 action',
    range: 'Touch',
    verbal: true,
    somatic: true,
    material: true,
    materialCost:
      '(a pair of platinum rings worth at least 50 gp each, which you and target must wear for the duration)',
    duration: '1 hour',
    source: "Player's Handbook",
  },

  {
    id: '203',
    name: 'Web',
    slug: 'web',
    description:
      'You conjure a mass of thick, sticky webbing at a point of your choice within range. The webs fill a 20-foot cube from that point for the duration. The webs are difficult terrain and lightly obscure their area.\n\nIf the webs aren’t anchored between two solid masses (such as walls or trees) or layered across a floor, wall, or ceiling, the conjured web collapses on itself, and the spell ends at the start of your next turn. Webs layered over a flat surface have a depth of 5 feet.\n\nEach creature that starts its turn in the webs or that enters them during its turn must make a Dexterity saving throw. On a failed save, the creature is restrained as long as it remains in the webs or until it breaks free.\n\nA creature restrained by the webs can use its action to make a Strength check against your spell save DC. If it succeeds, it is no longer restrained.\n\nThe webs are flammable. Any 5-foot cube of webs exposed to fire burns away in 1 round, dealing 2d4 fire damage to any creature that starts its turn in the fire.\n\n',
    level: 2,
    school: 'CONJURATION',
    castingTime: '1 action',
    range: '60 feet',
    verbal: true,
    somatic: true,
    material: true,
    materialCost: '(a bit of spiderweb)',
    duration: 'Concentration, up to 1 hour',
    source: "Player's Handbook",
  },
  {
    id: '206',
    name: 'Zone of Truth',
    slug: 'zone-of-truth',
    description:
      'You create a magical zone that guards against deception in a 15-foot-radius sphere centered on a point of your choice within range. Until the spell ends, a creature that enters the spell’s area for the first time on a turn or starts its turn there must make a Charisma saving throw. On a failed save, a creature can’t speak a deliberate lie while in the radius. You know whether each creature succeeds or fails on its saving throw.\n\nAn affected creature is aware of the spell and can thus avoid answering questions to which it would normally respond with a lie. Such creatures can be evasive in its answers as long as it remains within the boundaries of the truth.\n\n',
    level: 2,
    school: 'ENCHANTMENT',
    castingTime: '1 action',
    range: '60 feet',
    verbal: true,
    somatic: true,
    material: false,
    duration: '10 minutes',
    source: "Player's Handbook",
  },
];

export default SpellSecondLevelSeed;
