import { Ability, DamageTypes, Prisma, SpellScaleType } from '@prisma/client';

const cantripsSeed: Prisma.SpellCreateManyInput[] = [
  {
    id: '0',
    name: 'Acid Splash',
    slug: 'acid-splash',
    savingThrowAbility: Ability.DEX,
    spellScaleType: SpellScaleType.CHARACTER_LEVEL,
    levelScalingFormulas: [
      {
        description: 'Acid Damage',
        formulas: [
          {
            level: 1,
            formula: '1d6',
          },
          {
            level: 5,
            formula: '2d6',
          },
          {
            level: 11,
            formula: '3d6',
          },
          {
            level: 17,
            formula: '4d6',
          },
        ],
      },
    ],
    description:
      'You hurl a bubble of acid. Choose one creature you can see within range, or choose two creatures you can see within range that are within 5 feet of each other. A target must succeed on a Dexterity saving throw or take 1d6 acid damage.\n\n',
    level: 0,
    school: 'CONJURATION',
    castingTime: '1 action',
    range: '60 feet',
    verbal: true,
    somatic: true,
    material: false,
    damageType: DamageTypes.ACID,
    duration: 'Instantaneous',
    source: "Player's Handbook",
    spellScaleResultType: 'DAMAGE_OR_HEALING',
    upcastInfo:
      'This spell’s damage increases by 1d6 when you reach 5th level (2d6), 11th level (3d6), and 17th level (4d6).',
  },
  {
    id: '3',
    name: 'Chill Touch',
    slug: 'chill-touch',
    description:
      'You create a ghostly, skeletal hand in the space of a creature within range. Make a ranged spell attack against the creature to assail it with the chill of the grave. On a hit, the target takes 1d8 necrotic damage, and it can’t regain hit points until the start of your next turn. Until then, the hand clings to the target. If you hit an undead target, it also has disadvantage on attack rolls against you until the end of your next turn.\n\n',
    level: 0,
    school: 'NECROMANCY',
    castingTime: '1 action',
    range: '120 feet',
    verbal: true,
    somatic: true,
    material: false,
    duration: '1 round',
    source: "Player's Handbook",
    upcastInfo:
      'This spell’s damage increases by 1d8 when you reach 5th level (2d8), 11th level (3d8), and 17th level (4d8).',
  },
  {
    id: '6',
    name: 'Dancing Lights',
    slug: 'dance-lights',
    description:
      'You create up to four torch-sized lights within range, making them appear as torches, lanterns, or glowing orbs that hover in the air for the duration. You can also combine the four lights into one glowing vaguely humanoid form of Medium size. Whichever form you choose, each light sheds dim light in a 10-foot radius.\n\nAs a bonus action on your turn, you can move the lights up to 60 feet to a new spot within range. A light must be within 20 feet of another light created by this spell, and a light winks out if it exceeds the spell’s range.\n\n',
    level: 0,
    school: 'EVOCATION',
    castingTime: '1 action',
    range: '120 feet',
    verbal: true,
    somatic: true,
    material: true,
    materialCost: '(a bit of phosphorus or wychwood, or a glowworm)',
    duration: 'Concentration, up to 1 minute',
    source: "Player's Handbook",
  },

  {
    id: '7',
    name: 'Druidcraft',
    slug: 'druidcraft',
    description:
      'Whispering to the spirits of nature, you create one of the following effects within range:\n\n',
    level: 0,
    school: 'TRANSMUTATION',
    castingTime: '1 action',
    range: '30 feet',
    verbal: true,
    somatic: true,
    material: false,
    duration: 'Instantaneous',
    source: "Player's Handbook",
    options: [
      'You create a tiny, harmless sensory effect that predicts what the weather will be at your location for the next 24 hours. The effect might manifest as a golden orb for clear skies, a cloud for rain, falling snowflakes for snow, and so on. This effect persists for 1 round.',
      'You instantly make a flower blossom, a seed pod open, or a leaf bud bloom.',
      'You create an instantaneous, harmless sensory effect, such as falling leaves, a puff of wind, the sound of a small animal, or the faint odor of skunk. The effect must fit in a 5-foot cube.',
      'You instantly light or snuff out a candle, a torch, or a small campfire.',
    ],
  },

  {
    id: '8',
    name: 'Eldritch Blast',
    slug: 'eldritch-blast',
    description:
      'A beam of crackling energy streaks toward a creature within range. Make a ranged spell attack against the target. On a hit, the target takes 1d10 force damage.\n\n',
    level: 0,
    school: 'EVOCATION',
    castingTime: '1 action',
    range: '120 feet',
    verbal: true,
    somatic: true,
    material: false,
    duration: 'Instantaneous',
    source: "Player's Handbook",
    upcastInfo:
      'The spell creates more than one beam when you reach higher levels: two beams at 5th level, three beams at 11th level, and four beams at 17th level. You can direct the beams at the same target or at different ones. Make a separate attack roll for each beam.',
  },
  {
    id: '10',
    name: 'Fire Bolt',
    slug: 'fire-bolt',
    description:
      'You hurl a mote of fire at a creature or object within range. Make a ranged spell attack against the target. On a hit, the target takes 1d10 fire damage. A flammable object hit by this spell ignites if it isn’t being worn or carried.\n\n',
    level: 0,
    school: 'EVOCATION',
    castingTime: '1 action',
    range: '120 feet',
    verbal: true,
    somatic: true,
    material: false,
    duration: 'Instantaneous',
    source: "Player's Handbook",
    upcastInfo:
      'This spell’s damage increases by 1d10 when you reach 5th level (2d10), 11th level (3d10), and 17th level (4d10).',
  },
  {
    id: '14',
    name: 'Guidance',
    slug: 'guidance',
    description:
      'You touch one willing creature. Once before the spell ends, the target can roll a d4 and add the number rolled to one ability check of its choice. It can roll the die before or after making the ability check. The spell then ends.\n\n',
    level: 0,
    school: 'DIVINATION',
    castingTime: '1 action',
    range: 'Touch',
    verbal: true,
    somatic: true,
    material: false,
    duration: 'Concentration, up to 1 minute',
    source: "Player's Handbook",
  },
  {
    id: '17',
    name: 'Light',
    slug: 'light',
    description:
      'You touch one object that is no larger than 10 feet in any dimension. Until the spell ends, the object sheds bright light in a 20-foot radius and dim light for an additional 20 feet. The light can be colored as you like. Completely covering the object with something opaque blocks the light. The spell ends if you cast it again or dismiss it as an action.\n\nIf you target an object held or worn by a hostile creature, that creature must succeed on a Dexterity saving throw to avoid the spell.\n\n',
    level: 0,
    school: 'EVOCATION',
    castingTime: '1 action',
    range: 'Touch',
    verbal: true,
    somatic: false,
    material: true,
    materialCost: '(a firefly or phosphorescent moss)',
    duration: '1 hour',
    source: "Player's Handbook",
  },
  {
    id: '21',
    name: 'Mending',
    slug: 'mending',
    description:
      'This spell repairs a single break or tear in an object you touch, such as a broken chain link, two halves of a broken key, a torn cloak, or a leaking wineskin. As long as the break or tear is no larger than 1 foot in any dimension, you mend it, leaving no trace of the former damage.\n\nThis spell can physically repair a magic item or construct, but the spell can’t restore magic to such an object.\n\n',
    level: 0,
    school: 'TRANSMUTATION',
    castingTime: '1 minute',
    range: 'Touch',
    verbal: true,
    somatic: true,
    material: true,
    materialCost: '(two lodestones)',
    duration: 'Instantaneous',
    source: "Player's Handbook",
  },
  {
    id: '22',
    name: 'Message',
    slug: 'message',
    description:
      'You point your finger toward a creature within range and whisper a message. The target (and only the target) hears the message and can reply in a whisper that only you can hear.\n\nYou can cast this spell through solid objects if you are familiar with the target and know it is beyond the barrier. Magical silence, 1 foot of stone, 1 inch of common metal, a thin sheet of lead, or 3 feet of wood blocks the spell. The spell doesn’t have to follow a straight line and can travel freely around corners or through openings.\n\n',
    level: 0,
    school: 'TRANSMUTATION',
    castingTime: '1 action',
    range: '120 feet',
    verbal: true,
    somatic: true,
    material: true,
    materialCost: '(a short piece of copper wire)',
    duration: '1 round',
    source: "Player's Handbook",
  },
  {
    id: '24',
    name: 'Minor Illusion',
    slug: 'minor-illusion',
    description:
      'You create a sound or an image of an object within range that lasts for the duration. The illusion also ends if you dismiss it as an action or cast this spell again.\n\nIf you create a sound, its volume can range from a whisper to a scream. It can be your voice, someone else’s voice, a lion’s roar, a beating of drums, or any other sound you choose. The sound continues unabated throughout the duration, or you can make discrete sounds at different times before the spell ends.\n\nIf you create an image of an object—such as a chair, muddy footprints, or a small chest—it must be no larger than a 5-foot cube. The image can’t create sound, light, smell, or any other sensory effect. Physical interaction with the image reveals it to be an illusion, because things can pass through it.\n\nIf a creature uses its action to examine the sound or image, the creature can determine that it is an illusion with a successful Intelligence (Investigation) check against your spell save DC. If a creature discerns the illusion for what it is, the illusion becomes faint to the creature.\n\n',
    level: 0,
    school: 'ILLUSION',
    castingTime: '1 action',
    range: '30 feet',
    verbal: false,
    somatic: true,
    material: true,
    materialCost: '(a bit of fleece)',
    duration: '1 minute',
    source: "Player's Handbook",
  },
  {
    id: '27',
    name: 'Prestidigitation',
    slug: 'prestidigitation',
    description:
      'This spell is a minor magical trick that novice spellcasters use for practice. You create one of the following magical effects within range:\n\n',
    level: 0,
    school: 'TRANSMUTATION',
    castingTime: '1 action',
    range: '10 feet',
    verbal: true,
    somatic: true,
    material: false,
    duration: 'Up to 1 hour',
    source: "Player's Handbook",
    postTableData:
      'If you cast this spell multiple times, you can have up to three of its non-instantaneous effects active at a time, and you can dismiss such an effect as an action.\n\n',
    options: [
      'You create an instantaneous, harmless sensory effect, such as a shower of sparks, a puff of wind, faint musical notes, or an odd odor.',
      'You instantaneously light or snuff out a candle, a torch, or a small campfire.',
      'You instantaneously clean or soil an object no larger than 1 cubic foot.',
      'You chill, warm, or flavor up to 1 cubic foot of nonliving material for 1 hour.',
      'You make a color, a small mark, or a symbol appear on an object or a surface for 1 hour.',
      'You create a nonmagical trinket or an illusory image that can fit in your hand and that lasts until the end of your next turn.',
    ],
  },
  {
    id: '29',
    name: 'Produce Flame',
    slug: 'produce-flame',
    description:
      'A flickering flame appears in your hand. The flame remains there for the duration and harms neither you nor your equipment. The flame sheds bright light in a 10-foot radius and dim light for an additional 10 feet. The spell ends if you dismiss it as an action or if you cast it again.\n\nYou can also attack with the flame, although doing so ends the spell. When you cast this spell, or as an action on a later turn, you can hurl the flame at a creature within 30 feet of you. Make a ranged spell attack. On a hit, the target takes 1d8 fire damage.\n\n',
    level: 0,
    school: 'CONJURATION',
    castingTime: '1 action',
    range: 'Self',
    verbal: true,
    somatic: true,
    material: false,
    duration: '10 minutes',
    source: "Player's Handbook",
    upcastInfo:
      'This spell’s damage increases by 1d8 when you reach 5th level (2d8), 11th level (3d8), and 17th level (4d8).',
  },
  {
    id: '30',
    name: 'Ray of Frost',
    slug: 'ray-of-frost',
    description:
      'A frigid beam of blue-white light streaks toward a creature within range. Make a ranged spell attack against the target. On a hit, it takes 1d8 cold damage, and its speed is reduced by 10 feet until the start of your next turn.\n\n',
    level: 0,
    school: 'EVOCATION',
    castingTime: '1 action',
    range: '60 feet',
    verbal: true,
    somatic: true,
    material: false,
    duration: 'Instantaneous',
    source: "Player's Handbook",
    upcastInfo:
      'The spell’s damage increases by 1d8 when you reach 5th level (2d8), 11th level (3d8), and 17th level (4d8).',
  },
  {
    id: '31',
    name: 'Resistance',
    slug: 'resistance',
    description:
      'You touch one willing creature. Once before the spell ends, the target can roll a d4 and add the number rolled to one saving throw of its choice. It can roll the die before or after the saving throw. The spell then ends.\n\n',
    level: 0,
    school: 'ABJURATION',
    castingTime: '1 action',
    range: 'Touch',
    verbal: true,
    somatic: true,
    material: true,
    materialCost: '(a miniature cloak)',
    duration: 'Concentration, up to 1 minute',
    source: "Player's Handbook",
  },
  {
    id: '32',
    name: 'Sacred Flame',
    slug: 'sacred-flame',
    description:
      'Flame-like radiance descends on a creature that you can see within range. The target must succeed on a Dexterity saving throw or take 1d8 radiant damage. The target gains no benefit from cover for this saving throw.\n\n',
    level: 0,
    school: 'EVOCATION',
    castingTime: '1 action',
    range: '60 feet',
    verbal: true,
    somatic: true,
    material: false,
    duration: 'Instantaneous',
    source: "Player's Handbook",
    upcastInfo:
      'The spell’s damage increases by 1d8 when you reach 5th level (2d8), 11th level (3d8), and 17th level (4d8).',
  },
  {
    id: '35',
    name: 'Shillelagh',
    slug: 'shillelagh',
    description:
      'The wood of a club or quarterstaff you are holding is imbued with nature’s power. For the duration, you can use your spellcasting ability instead of Strength for the attack and damage rolls of melee attacks using that weapon, and the weapon’s damage die becomes a d8. The weapon also becomes magical, if it isn’t already. The spell ends if you cast it again or if you let go of the weapon.\n\n',
    level: 0,
    school: 'TRANSMUTATION',
    castingTime: '1 bonus action',
    range: 'Touch',
    verbal: true,
    somatic: true,
    material: true,
    materialCost: '(mistletoe, a shamrock leaf, and a club or quarterstaff)',
    duration: '1 minute',
    source: "Player's Handbook",
  },
  {
    id: '36',
    name: 'Shocking Grasp',
    slug: 'shocking-grasp',
    description:
      'Lightning springs from your hand to deliver a shock to a creature you try to touch. Make a melee spell attack against the target. You have advantage on the attack roll if the target is wearing armor made of metal. On a hit, the target takes 1d8 lightning damage, and it can’t take reactions until the start of its next turn.\n\n',
    level: 0,
    school: 'EVOCATION',
    castingTime: '1 action',
    range: 'Touch',
    verbal: true,
    somatic: true,
    material: false,
    duration: 'Instantaneous',
    source: "Player's Handbook",
    upcastInfo:
      'The spell’s damage increases by 1d8 when you reach 5th level (2d8), 11th level (3d8), and 17th level (4d8).',
  },
  {
    id: '37',
    name: 'Spare the Dying',
    slug: 'spare-the-dying',
    description:
      'You touch a living creature that has 0 hit points. The creature becomes stable. This spell has no effect on undead or constructs.\n\n',
    level: 0,
    school: 'NECROMANCY',
    castingTime: '1 action',
    range: 'Touch',
    verbal: true,
    somatic: true,
    material: false,
    duration: 'Instantaneous',
    source: "Player's Handbook",
  },
  {
    id: '39',
    name: 'Thaumaturgy',
    slug: 'thaumaturgy',
    description:
      'You manifest a minor wonder, a sign of supernatural power, within range. You create one of the following magical effects within range:\n\n',
    level: 0,
    school: 'TRANSMUTATION',
    castingTime: '1 action',
    range: '30 feet',
    verbal: true,
    somatic: false,
    material: false,
    duration: 'Up to 1 minute',
    source: "Player's Handbook",
    postTableData:
      'If you cast this spell multiple times, you can have up to three of its 1-minute effects active at a time, and you can dismiss such an effect as an action.\n\n',
    options: [
      'Your voice booms up to three times as loud as normal for 1 minute.',
      'You cause flames to flicker, brighten, dim, or change color for 1 minute.',
      'You cause harmless tremors in the ground for 1 minute.',
      'You create an instantaneous sound that originates from a point of your choice within range, such as a rumble of thunder, the cry of a raven, or ominous whispers.',
      'You instantaneously cause an unlocked door or window to fly open or slam shut.',
      'You alter the appearance of your eyes for 1 minute.',
    ],
  },
  {
    id: '43',
    name: 'True Strike',
    slug: 'true-strike',
    description:
      'You extend your hand and point a finger at a target in range. Your magic grants you a brief insight into the target’s defenses. On your next turn, you gain advantage on your first attack roll against the target, provided that this spell hasn’t ended.\n\n',
    level: 0,
    school: 'DIVINATION',
    castingTime: '1 action',
    range: '30 feet',
    verbal: false,
    somatic: true,
    material: false,
    duration: 'Concentration, up to 1 round',
    source: "Player's Handbook",
  },
  {
    id: '44',
    name: 'Vicious Mockery',
    slug: 'vicious-mockery',
    description:
      'You unleash a string of insults laced with subtle enchantments at a creature you can see within range. If the target can hear you (though it need not understand you), it must succeed on a Wisdom saving throw or take 1d4 psychic damage and have disadvantage on the next attack roll it makes before the end of its next turn.\n\n',
    level: 0,
    school: 'ENCHANTMENT',
    castingTime: '1 action',
    range: '60 feet',
    verbal: true,
    somatic: false,
    material: false,
    duration: 'Instantaneous',
    source: "Player's Handbook",
    upcastInfo:
      'This spell’s damage increases by 1d4 when you reach 5th level (2d4), 11th level (3d4), and 17th level (4d4).',
  },
];

export default cantripsSeed;
