import { Prisma } from '@prisma/client';

const SpellFourthLevelSeed: Prisma.SpellCreateManyInput[] = [
  {
    id: '275',
    name: 'Arcane Eye',
    slug: 'arcane-eye',
    description:
      'You create an invisible, magical eye within range that hovers in the air for the duration. You mentally receive visual information from the eye, which has normal vision and darkvision out to 30 feet. The eye can look in every direction.\n\nAs an action, you can move the eye up to 30 feet in any direction. There is no limit to how far away from you the eye can move, but it can’t enter another plane of existence. A solid barrier blocks the eye’s movement, but the eye can pass through an opening as small as 1 inch in diameter.\n\n',
    level: 4,
    school: 'DIVINATION',
    castingTime: '1 action',
    range: '30 feet',
    verbal: true,
    somatic: true,
    material: true,
    materialCost: '(a bit of bat fur)',
    duration: 'Concentration, up to 1 hour',
    source: "Player's Handbook",
    postTableData: '',
    extendedTable: [],
    options: [],
    upcastInfo: '',
  },
  {
    id: '278',
    name: 'Banishment',
    slug: 'banishment',
    description:
      'You attempt to send one creature that you can see within range to another place of existence. The target must succeed on a Charisma saving throw or be banished.\n\nIf the target is native to the plane of existence you’re on, you banish the target to a harmless demiplane. While there, the target is incapacitated. The target remains there until the spell ends, at which point the target reappears in the space it left or in the nearest unoccupied space if that space is occupied.\n\nIf the target is native to a different plane of existence that the one you’re on, the target is banished with a faint popping noise, returning to its home plane. If the spell ends before 1 minute has passed, the target reappears in the space it left or in the nearest unoccupied space if that space is occupied. Otherwise, the target doesn’t return.\n\n',
    level: 4,
    school: 'ABJURATION',
    castingTime: '1 action',
    range: '60 feet',
    verbal: true,
    somatic: true,
    material: true,
    materialCost: '(an item distasteful to the target)',
    duration: 'Concentration, up to 1 minute',
    source: "Player's Handbook",
    upcastInfo:
      'When you cast this spell using a spell slot of 5th level or higher, you can target one additional creature for each slot level above 4th.',
  },
  {
    id: '210',
    name: 'Beacon of Hope',
    slug: 'beacon-of-hope',
    description:
      'This spell bestows hope and vitality. Choose any number of creatures within range. For the duration, each target has advantage on Wisdom saving throws and death saving throws, and regains the maximum number of hit points possible from any healing.\n\n',
    level: 3,
    school: 'ABJURATION',
    castingTime: '1 action',
    range: '30 feet',
    verbal: true,
    somatic: true,
    material: false,
    materialCost: '',
    duration: 'Concentration, up to 1 minute',
    source: "Player's Handbook",
    postTableData: '',
    extendedTable: [],
    options: [],
    upcastInfo: '',
  },
  {
    id: '291',
    name: "Evard's Black Tentacles",
    slug: 'evards-black-tentacles',
    description:
      'Squirming, ebony tentacles fill a 20-foot square on ground that you can see within range. For the duration, these tentacles turn the ground in the area into difficult terrain.\n\nWhen a creature enters the affected area for the first time on a turn or starts its turn there, the creature must succeed on a Dexterity saving throw or take 3d6 bludgeoning damage and be restrained by the tentacles until the spell ends. A creature that starts its turn in the area and is already restrained by the tentacles takes 3d6 bludgeoning damage.\n\nA creature restrained by the tentacles can use its action to make a Strength or Dexterity check (its choice) against your spell save DC. On a success, it frees itself.\n\n',
    level: 4,
    school: 'CONJURATION',
    castingTime: '1 action',
    range: '90 feet',
    verbal: true,
    somatic: true,
    material: true,
    materialCost: '(a piece of tentacle from a giant octopus or a giant squid)',
    duration: 'Concentration, up to 1 minute',
    source: "Player's Handbook",
  },

  {
    id: '279',
    name: 'Blight',
    slug: 'blight',
    description:
      'Necromantic energy washes over a creature of your choice that you can see within range, draining moisture and vitality from it. The target must make a Constitution saving throw. The target takes 8d8 necrotic damage on a failed save, or half as much damage on a successful one. This spell has no effect on undead or constructs.\n\nIf you target a plant creature or a magical plant, it makes the saving throw with disadvantage, and the spell deals maximum damage to it. If you target a nonmagical plant that isn’t a creature, such as a tree or shrub, it doesn’t make a saving throw; it simply withers and dies.\n\n',
    level: 4,
    school: 'NECROMANCY',
    castingTime: '1 action',
    range: '30 feet',
    verbal: true,
    somatic: true,
    material: false,
    duration: 'Instantaneous',
    source: "Player's Handbook",

    upcastInfo:
      'When you cast this spell using a spell slot of 5th level or higher, the damage increases by 1d8 for each slot level above 4th.',
  },
  {
    id: '281',
    name: 'Compulsion',
    slug: 'compulsion',
    description:
      'Creatures of your choice that you can see within range and that can hear you must make a Wisdom saving throw. A target automatically succeeds on this saving throw if it can’t be charmed. On a failed save, a target is affected by this spell. Until the spell ends, you can use a bonus action on each of your turns to designate a direction that is horizontal to you. Each affected target must use as much of its movement as possible to move in that direction on its next turn. It can take its action before it moves. After moving in this way, it can make another Wisdom saving throw to try to end the effect.\n\nA target isn’t compelled to move into an obviously deadly hazard, such as a fire pit, but it will provoke opportunity attacks to move in the designated direction.\n\n',
    level: 4,
    school: 'ENCHANTMENT',
    castingTime: '1 action',
    range: '30 feet',
    verbal: true,
    somatic: true,
    material: false,
    duration: 'Concentration, up to 1 minute',
    source: "Player's Handbook",
  },
  {
    id: '282',
    name: 'Confusion',
    slug: 'confusion',
    description:
      'This spell assaults and twists creatures’ minds, spawning delusions and provoking uncontrolled actions. Each creature in a 10-foot-radius sphere centered on a point you choose within range must succeed on a Wisdom saving throw when you cast this spell or be affected by it.\n\nAn affected target can’t take reactions and must roll a d10 at the start of each of its turns to determine its behavior for that turn.\n\nAt the end of its turns, an affected target can make a Wisdom saving throw. If it succeeds, this effect ends for that target.\n\n',
    level: 4,
    school: 'ENCHANTMENT',
    castingTime: '1 action',
    range: '90 feet',
    verbal: true,
    somatic: true,
    material: true,
    materialCost: '(three nut shells)',
    duration: 'Concentration, up to 1 minute',
    source: "Player's Handbook",
    extendedTable: [
      {
        '': {
          headers: ['d10', 'Behavior'],
          data: [
            {
              d10: '1',
              Behavior:
                'The creature uses all its movement to move in a random direction. To determine the direction, roll a d8 and assign a direction to each die face. The creature doesn’t take an action this turn.',
            },
            {
              d10: '2-6',
              Behavior: 'The creature doesn’t move or take actions this turn.',
            },
            {
              d10: '7-8',
              Behavior:
                'The creature uses its action to make a melee attack against a randomly determined creature within its reach. If there is no creature within its reach, the creature does nothing this turn.',
            },
            {
              d10: '9-10',
              Behavior: 'The creature can act and move normally.',
            },
          ],
        },
      },
    ],
    upcastInfo:
      'When you cast this spell using a spell slot of 5th level or higher, the radius of the sphere increases by 5 feet for each slot level above 4th.',
  },
  {
    id: '283',
    name: 'Conjure Minor Elementals',
    slug: 'conjure-minor-elementals',
    description:
      'You summon elementals that appear in unoccupied spaces that you can see within range. You choose one the following options for what appears:\n\n',
    level: 4,
    school: 'CONJURATION',
    castingTime: '1 minute',
    range: '90 feet',
    verbal: true,
    somatic: true,
    material: false,
    duration: 'Concentration, up to 1 hour',
    source: "Player's Handbook",
    postTableData:
      'An elemental summoned by this spell disappears when it drops to 0 hit points or when the spell ends.\n\nThe summoned creatures are friendly to you and your companions. Roll initiative for the summoned creatures as a group, which has its own turns. They obey any verbal commands that you issue to them (no action required by you). If you don’t issue any commands to them, they defend themselves from hostile creatures, but otherwise take no actions. The DM has the creatures’ statistics.\n\n',
    options: [
      'One elemental of challenge rating 2 or lower',
      'Two elementals of challenge rating 1 or lower',
      'Four elementals of challenge rating 1/2 or lower',
      'Eight elementals of challenge rating 1/4 or lower',
    ],
    upcastInfo:
      'When you cast this spell using certain higher-level spell slots, you choose one of the summoning options above, and more creatures appear: twice as many with a 6th-level slot and three times as many with an 8th-level slot.',
  },

  {
    id: '284',
    name: 'Conjure Woodland Beings',
    slug: 'conjure-woodland-beings',
    description:
      'You summon fey creatures that appear in unoccupied spaces that you can see within range. Choose one of the following options for what appears:\n\n',
    level: 4,
    school: 'CONJURATION',
    castingTime: '1 action',
    range: '60 feet',
    verbal: true,
    somatic: true,
    material: true,
    materialCost: '(one holly berry per creature summoned)',
    duration: 'Concentration, up to 1 hour',
    source: "Player's Handbook",
    postTableData:
      'A summoned creature disappears when it drops to 0 hit points or when the spell ends.\n\nThe summoned creatures are friendly to you and your companions. Roll initiative for the summoned creatures as a group, which have their own turns. They obey any verbal commands that you issue to them (no action required by you). If you don’t issue any commands to them, they defend themselves from hostile creatures, but otherwise take no actions. The DM has the creatures’ statistics.\n\n',
    extendedTable: [],
    options: [
      'One fey creature of challenge rating 2 or lower',
      'Two fey creatures of challenge rating 1 or lower',
      'Four fey creatures of challenge rating 1/2 or lower',
      'Eight fey creatures of challenge rating 1/4 or lower',
    ],
    upcastInfo:
      'When you cast this spell using certain higher-level spell slots, you choose one of the summoning options above, and more creatures appear: twice as many with a 6th-level slot, and three times as many with an 8th-level slot.',
  },
  {
    id: '285',
    name: 'Control Water',
    slug: 'control-water',
    description:
      'Until the spell ends, you control any freestanding water inside an area you choose that is a cube up to 100 feet on a side. You can choose from any of the following effects when you cast this spell. As an action on your turn, you can repeat the same effect or choose a different one.\n\nWhen a creature enters the vortex for the first time on a turn or starts its turn there, it must make a Strength saving throw. On a failed save, the creature takes 2d8 bludgeoning damage and is caught in the vortex until the spell ends. On a successful save, the creature takes half damage, and isn’t caught in the vortex. A creature caught in the vortex can use its action to try to swim away from the vortex as described above, but has disadvantage on the Strength (Athletics) check to do so.\n\nThe first time each turn that an object enters the vortex, the object takes 2d8 bludgeoning damage, this damage occurs each round it remains in the vortex.\n\n',
    level: 4,
    school: 'TRANSMUTATION',
    castingTime: '1 action',
    range: '300 feet',
    verbal: true,
    somatic: true,
    material: true,
    materialCost: '(a drop of water and a pinch of dust)',
    duration: 'Concentration, up to 10 minutes',
    source: "Player's Handbook",
  },
  {
    id: '286',
    name: 'Death Ward',
    slug: 'death-ward',
    description:
      'You touch a creature and grant it a measure of protection from death. The first time the target would drop to 0 hit points as a result of taking damage, the target instead drops to 1 hit point, and the spell ends. If the spell is still in effect when the target is subjected to an effect that would kill it instantaneously without dealing damage, that effect is instead negated against the target, and the spells ends.\n\n',
    level: 4,
    school: 'ABJURATION',
    castingTime: '1 action',
    range: 'Touch',
    verbal: true,
    somatic: true,
    material: false,
    duration: '8 hours',
    source: "Player's Handbook",
  },
  {
    id: '287',
    name: 'Dimension Door',
    slug: 'dimension-door',
    description:
      'You teleport yourself from your current location to any other spot within range. You arrive at exactly the spot desired. It can be a place you can see, one you can visualize, or one you can describe by stating distance and direction, such as "200 feet straight downward" or "upward to the northwest at a 45-degree angle, 300 feet".\n\nYou can bring along objects as long as their weight doesn’t exceed what you can carry. You can also bring one willing creature of your size or smaller who is carrying gear up to its carrying capacity. The creature must be within 5 feet of you when you cast this spell.\n\nIf you would arrive in a place already occupied by an object or a creature, you and any creature traveling with you each take 4d6 force damage, and the spell fails to teleport you.\n\n',
    level: 4,
    school: 'CONJURATION',
    castingTime: '1 action',
    range: '500 feet',
    verbal: true,
    somatic: false,
    material: false,
    duration: 'Instantaneous',
    source: "Player's Handbook",
  },
  {
    id: '288',
    name: 'Divination',
    slug: 'divination',
    description:
      'Your magic and an offering put you in contact with a god or a god’s servants. You ask a single question concerning a specific goal, event, or activity to occur within 7 days. The DM offers a truthful reply. The reply might be a short phrase, a cryptic rhyme, or an omen.\n\nThe spell doesn’t take into account any possible circumstances that might change the outcome, such as the casting of additional spells or the loss or gain of a companion.\n\nIf you cast this spell two or more times before finishing your next long rest, there is a cumulative 25 percent chance for each casting after the first that you get a random reading. The DM makes this roll in secret.\n\n',
    level: 4,
    school: 'DIVINATION',
    castingTime: '1 action',
    range: 'Self',
    verbal: true,
    somatic: true,
    material: true,
    materialCost:
      '(incense and a sacrificial offering appropriate to your religion, together worth at least 25 gp, which the spell consumes)',
    duration: 'Instantaneous',
    source: "Player's Handbook",
  },

  {
    id: '289',
    name: 'Dominate Beast',
    slug: 'dominate-beast',
    description:
      'You attempt to beguile a beast that you can see within range. It must succeed on a Wisdom saving throw or be charmed by you for the duration. If you or creatures that are friendly to you are fighting it, it has advantage on the saving throw.\n\nWhile the beast is charmed, you have a telepathic link with it as long as the two of you are on the same plane of existence. You can use this telepathic link to issue commands to the creature while you are conscious (no action required), which it does its best to obey. You can specify a simple and general course of action, such as “Attack that creature,” “Run over there,” or “Fetch that object.” If the creature completes the order and doesn’t receive further direction from you, it defends and preserves itself to the best of its ability.\n\nYou can use your action to take total and precise control of the target. Until the end of your next turn, the creature takes only the actions you choose, and doesn’t do anything that you don’t allow it to do. During this time, you can also cause the creature to use a reaction, but this requires you to use your own reaction as well.\n\nEach time the target takes damage, it makes a new Wisdom saving throw against the spell. If the saving throw succeeds, the spell ends.\n\n',
    level: 4,
    school: 'ENCHANTMENT',
    castingTime: '1 action',
    range: '60 feet',
    verbal: true,
    somatic: true,
    material: false,
    duration: 'Concentration, up to 1 minute',
    source: "Player's Handbook",
    upcastInfo:
      'When you cast this spell with a 5th-level spell slot, the duration is concentration, up to 10 minutes. When you use a 6th-level spell slot, the duration is concentration, up to 1 hour. When you use a spell slot of 7th level or higher, the duration is concentration, up to 8 hours',
  },
  {
    id: '292',
    name: 'Fabricate',
    slug: 'fabricate',
    description:
      'You convert raw materials into products of the same material. For example, you can fabricate a wooden bridge from a clump of trees, a rope from a patch of hemp, and clothes from flax or wool.\n\nChoose raw materials that you can see within range. You can fabricate a Large or smaller object (contained within a 10-foot cube, or eight connected 5-foot cubes), given a sufficient quantity of raw material. If you are working with metal, stone, or another mineral substance, however, the fabricated object can be no larger than Medium (contained within a single 5-foot cube). The quality of objects made by the spell is commensurate with the quality of the raw materials.\n\nCreatures or magic items can’t be created or transmuted by this spell. You also can’t use it to create items that ordinarily require a high degree of craftsmanship, such as jewelry, weapons, glass, or armor, unless you have proficiency with the type of artisan’s tools used to craft such objects.\n\n',
    level: 4,
    school: 'TRANSMUTATION',
    castingTime: '10 minutes',
    range: '120 feet',
    verbal: true,
    somatic: true,
    material: false,
    duration: 'Instantaneous',
    source: "Player's Handbook",
  },
  {
    id: '306',
    name: 'Faithful Hound',
    slug: 'faithful-hound',
    description:
      'You conjure a phantom watchdog in an unoccupied space that you can see within range, where it remains for the duration, until you dismiss it as an action, or until you move more than 100 feet away from it.\n\nThe hound is invisible to all creatures except you and can’t be harmed. When a Small or larger creature comes within 30 feet of it without first speaking the password that you specify when you cast this spell, the hound starts barking loudly. The hound sees invisible creatures and can see into the Ethereal Plane. It ignores illusions.\n\nAt the start of each of your turns, the hound attempts to bite one creature within 5 feet of it that is hostile to you. The hound’s attack bonus is equal to your spellcasting ability modifier + your proficiency bonus. On a hit, it deals 4d8 piercing damage.\n\n',
    level: 4,
    school: 'CONJURATION',
    castingTime: '1 action',
    range: '30 feet',
    verbal: true,
    somatic: true,
    material: true,
    materialCost: '(a tiny silver whistle, a piece of bone, and a thread)',
    duration: '8 hours',
    source: "Player's Handbook",
  },
  {
    id: '294',
    name: 'Fire Shield',
    slug: 'fire-shield',
    description:
      'Thin and wispy flames wreathe your body for the duration, shedding bright light in a 10-foot radius and dim light for an additional 10 feet. You can end the spell early by using an action to dismiss it.\n\nThe flames provide you with a warm shield or a chill shield, as you choose. The warm shield grants you resistance to cold damage, and the chill shield grants you resistance to fire damage.\n\nIn addition, whenever a creature within 5 feet of you hits you with a melee attack, the shield erupts with flame. The attacker takes 2d8 fire damage from a warm shield, or 2d8 cold damage from a cold shield.\n\n',
    level: 4,
    school: 'EVOCATION',
    castingTime: '1 action',
    range: 'Self',
    verbal: true,
    somatic: true,
    material: true,
    materialCost: '(a bit of phosphorus or a firefly)',
    duration: '10 minutes',
    source: "Player's Handbook",
  },
  {
    id: '295',
    name: 'Freedom of Movement',
    slug: 'freedom-of-movement',
    description:
      'You touch a willing creature. For the duration, the target’s movement is unaffected by difficult terrain, and spells and other magical effects can neither reduce the target’s speed nor cause the target to be paralyzed or restrained.\n\nThe target can also spend 5 feet of movement to automatically escape from nonmagical restraints, such as manacles or a creature that has it grappled. Finally, being underwater imposes no penalties on the target’s movement or attacks.\n\n',
    level: 4,
    school: 'ABJURATION',
    castingTime: '1 action',
    range: 'Touch',
    verbal: true,
    somatic: true,
    material: true,
    materialCost:
      '(a leather strap, bound around the arm or a similar appendage)',
    duration: '1 hour',
    source: "Player's Handbook",
  },
  {
    id: '297',
    name: 'Giant Insect',
    slug: 'giant-insect',
    description:
      'You transform up to ten centipedes, three spiders, five wasps, or one scorpion within range into giant versions of their natural forms for the duration. A centipede becomes a giant centipede, a spider becaomes a giant spider, a wasp becomes a giant wasp, and a scorpion becomes a giant scorpion.\n\nEach creature obeys your verbal commands, and in combat, they act on your turn each round. The DM has the statistics for these creatures and resolves their actions and movement.\n\nA creature remains in its giant size for the duration, until it drops to 0 hit points, or until you use an action to dismiss the effect on it.\n\nThe DM might allow you to choose different targets. For example, if you transform a bee, its giant version might have the same statistics as a giant wasp.\n\n',
    level: 4,
    school: 'TRANSMUTATION',
    castingTime: '1 action',
    range: '30 feet',
    verbal: true,
    somatic: true,
    material: false,
    duration: 'Concentration, up to 10 minutes',
    source: "Player's Handbook",
  },
  {
    id: '300',
    name: 'Greater Invisibility',
    slug: 'greater-invisibility',
    description:
      'You or a creature you touch becomes invisible until the spell ends. Anything the target is wearing or carrying is invisible as long as it is on the target’s person.\n\n',
    level: 4,
    school: 'ILLUSION',
    castingTime: '1 action',
    range: 'Touch',
    verbal: true,
    somatic: true,
    material: false,
    duration: 'Concentration, up to 1 minute',
    source: "Player's Handbook",
  },
  {
    id: '301',
    name: 'Guardian of Faith',
    slug: 'guardian-of-faith',
    description:
      'A Large spectral guardian appears and hovers for the duration in an unoccupied space of your choice that you can see within range. The guardian occupies that space and is indistinct except for a gleaming sword and shield emblazoned with the symbol of your deity.\n\nAny creature hostile to you that moves to a space within 10 feet of the guardian for the first time on a turn must succeed on a Dexterity saving throw. The creature takes 20 radiant damage on a failed save, or half as much damage on a successful one. The guardian vanishes when it has dealt a total of 60 damage.\n\n',
    level: 4,
    school: 'CONJURATION',
    castingTime: '1 action',
    range: '30 feet',
    verbal: true,
    somatic: false,
    material: false,
    duration: '8 hours',
    source: "Player's Handbook",
  },
  {
    id: '302',
    name: 'Hallucinatory Terrain',
    slug: 'hallucinatory-terrain',
    description:
      'You make natural terrain in a 150-foot cube in range look, sound, and smell like some other sort of natural terrain. Thus, open fields or a road can be made to resemble a swamp, hill, crevasse, or some other difficult or impassable terrain. A pond can be made to seem like a grassy meadow, a precipice like a gentle slope, or a rock-strewn gully like a wide and smooth road. Manufactured structures, equipment, and creatures within the area aren’t changed in appearance.\n\nThe tactile characteristics of the terrain are unchanged, so creatures entering the area are likely to see through the illusion. If the difference isn’t obvious by touch, a creature carefully examining the illusion can attempt an Intelligence (Investigation) check against your spell save DC to disbelieve it. A creature who discerns the illusion for what it is, sees it as a vague image superimposed on the terrain.\n\n',
    level: 4,
    school: 'ILLUSION',
    castingTime: '10 minutes',
    range: '300 feet',
    verbal: true,
    somatic: true,
    material: true,
    materialCost: '(a stone, a twig, and a bit of green plant)',
    duration: '24 hours',
    source: "Player's Handbook",
  },
  {
    id: '303',
    name: 'Ice Storm',
    slug: 'ice-storm',
    description:
      'A hail of rock-hard ice pounds to the ground in a 20-foot-radius, 40-foot-high cylinder centered on a point within range. Each creature in the cylinder must make a Dexterity saving throw. A creature takes 2d8 bludgeoning damage and 4d6 cold damage on a failed save, or half as much damage on a successful one.\n\nHailstones turn the storm’s area of effect into difficult terrain until the end of your next turn.\n\n',
    level: 4,
    school: 'EVOCATION',
    castingTime: '1 action',
    range: '300 feet',
    verbal: true,
    somatic: true,
    material: true,
    materialCost: '(a pinch of dust and a few drops of water)',
    duration: 'Instantaneous',
    source: "Player's Handbook",
    upcastInfo:
      'When you cast this spell using a spell slot of 5th level or higher, the bludgeoning damage increases by 1d8 for each slot level above 4th.',
  },
  {
    id: '305',
    name: 'Locate Creature',
    slug: 'locate-creature',
    description:
      'Describe or name a creature that is familiar to you. You sense the direction to the creature’s location, as long as that creature is within 1,000 feet of you. If the creature is moving, you know the direction of its movement.\n\nThe spell can locate a specific creature known to you, or the nearest creature of a specific kind (such as a human or a unicorn), so long as you have seen such a creature up close – within 30 feet – at least once. If the creature you described or named is in a different form, such as being under the effects of a polymorph spell, this spell doesn’t locate the creature.\n\nThis spell can’t locate a creature if running water at least 10 feet wide blocks a direct path between you and the creature.\n\n',
    level: 4,
    school: 'DIVINATION',
    castingTime: '1 action',
    range: 'Self',
    verbal: true,
    somatic: true,
    material: true,
    materialCost: '(a bit of fur from a bloodhound)',
    duration: 'Concentration, up to 1 hour',
    source: "Player's Handbook",
  },
  {
    id: '309',
    name: 'Phantasmal Killer',
    slug: 'phantasmal-killer',
    description:
      'You tap into the nightmares of a creature you can see within range and create an illusory manifestation of its deepest fears, visible only to that creature.\n\nThe target must make a Wisdom saving throw. On a failed save, the target becomes frightened for the duration. At the end of each of the target’s turns before the spell ends, the target must succeed on a Wisdom saving throw or take 4d10 psychic damage. On a successful save, the spell ends.\n\n',
    level: 4,
    school: 'ILLUSION',
    castingTime: '1 action',
    range: '120 feet',
    verbal: true,
    somatic: true,
    material: false,
    duration: 'Concentration, up to 1 minute',
    source: "Player's Handbook",
    upcastInfo:
      'When you cast this spell using a spell slot of 5th level or higher, the damage increases by 1d10 for each slot level above 4th.',
  },
  {
    id: '310',
    name: 'Polymorph',
    slug: 'polymorph',
    description:
      'This spell transforms a creature that you can see within range into a new form. An unwilling creature must make a Wisdom saving throw to avoid the effect. A shapechanger automatically succeeds on this saving throw.\n\nThe transformation lasts for the duration, or until the target drops to 0 hit points or dies. The new form can be any beast whose challenge rating is equal to or less than the target’s (or the target’s level, if it doesn’t have a challenge rating). The target’s game statistics, including mental ability scores, are replaced by the statistics of the chosen beast. It retains its alignment and personality.\n\nThe target assumes the hit points of its new form. When it reverts to its normal form, the creature returns to the number of hit points it had before it transformed. If it reverts as a result of dropping to 0 hit points, any excess damage carries over to its normal form. As long as the excess damage doesn’t reduce the creature’s normal form to 0 hit points, it isn’t knocked unconscious.\n\nThe creature is limited in the actions it can perform by the nature of its new form, and it can’t speak, cast spells, or take any other action that requires hands or speech.\n\nThe target’s gear melds into the new form. The creature can’t activate, use, wield, or otherwise benefit from any of its equipment. This spell can’t affect a target that has 0 hit points.\n\n',
    level: 4,
    school: 'TRANSMUTATION',
    castingTime: '1 action',
    range: '60 feet',
    verbal: true,
    somatic: true,
    material: true,
    materialCost: '(a caterpillar cocoon)',
    duration: 'Concentration, up to 1 hour',
    source: "Player's Handbook",
  },
  {
    id: '307',
    name: 'Private Sanctum',
    slug: 'private-sanctum',
    description:
      'You make an area within range magically secure. The area is a cube that can be as small as 5 feet to as large as 100 feet on each side. The spell lasts for the duration or until you use an action to dismiss it.\n\nWhen you cast the spell, you decide what sort of security the spell provides, choosing any or all of the following properties:\n\n',
    level: 4,
    school: 'ABJURATION',
    castingTime: '10 minutes',
    range: '120 feet',
    verbal: true,
    somatic: true,
    material: true,
    materialCost:
      '(a thin sheet of lead, a piece of opaque glass, a wad of cotton or cloth, and powdered chrysolite)',
    duration: '24 hours',
    source: "Player's Handbook",
    postTableData:
      'Casting this spell on the same spot every day for a year makes this effect permanent.\n\n',
    options: [
      'Sound can’t pass through the barrier at the edge of the warded area.',
      'The barrier of the warded area appears dark and foggy, preventing vision (including darkvision) through it.',
      'Sensors created by divination spells can’t appear inside the protected area or pass through the barrier at its perimeter.',
      'Creatures in the area can’t be targeted by divination spells.',
      'Nothing can teleport into or out of the warded area.',
      'Planar travel is blocked within the warded area.',
    ],
    upcastInfo:
      'When you cast this spell using a spell slot of 5th level or higher, you can increase the size of the cube by 100 feet for each slot level beyond 4th. Thus you could protect a cube that can be up to 200 feet on one side by using a spell slot of 5th level.',
  },
  {
    id: '308',
    name: 'Resilient Sphere',
    slug: 'resilient-sphere',
    description:
      'A sphere of shimmering force encloses a creature or object of Large size or smaller within range. An unwilling creature must make a Dexterity saving throw. On a failed save, the creature is enclosed for the duration.\n\nNothing –&nbsp;not physical objects, energy, or other spell effects – can pass through the barrier, in or out, though a creature in the sphere can breathe there. The sphere is immune to all damage, and a creature or object inside can’t be damaged by attacks or effects originating from outside, nor can a creature inside the sphere damage anything outside it.\n\nThe sphere is weightless and just large enough to contain the creature or object inside. An enclosed creature can use its action to push against the sphere’s walls and thus roll the sphere at up to half the creature’s speed. Similarly, the globe can be picked up and moved by other creatures.\n\nA Disintegrate spell targeting the globe destroys it without harming anything inside it.\n\n',
    level: 4,
    school: 'EVOCATION',
    castingTime: '1 action',
    range: '30 feet',
    verbal: true,
    somatic: true,
    material: true,
    materialCost:
      '(a hemispherical piece of clear crystal and a matching hemispherical piece of gum arabic)',
    duration: 'Concentration, up to 1 minute',
    source: "Player's Handbook",
  },
  {
    id: '304',
    name: 'Secret Chest',
    slug: 'secret-chest',
    description:
      'You hide a chest, and all its contents, on the Ethereal Plane. You must touch the chest and the miniature replica that serves as a material component for the spell. The chest can contain up to 12 cubic feet of nonliving material (3 feet by 2 feet by 2 feet).\n\nWhile the chest remains on the Ethereal Plane, you can use an action and touch the replica to recall the chest. It appears in an unoccupied space on the ground within 5 feet of you. You can send the chest back to the Ethereal Plane by using an action and touching both the chest and the replica.\n\nAfter 60 days, there is a cumulative 5 percent chance per day that the spell’s effect ends. This effect ends if you cast this spell again, if the smaller replica chest is destroyed, or if you choose to end the spell as an action. If the spell ends and the larger chest is on the Ethereal Plane, it is irretrievably lost.\n\n',
    level: 4,
    school: 'CONJURATION',
    castingTime: '1 action',
    range: 'Touch',
    verbal: true,
    somatic: true,
    material: true,
    materialCost:
      '(an exquisite chest, 3 feet by 2 feet by 2 feet, constructed from rare materials worth at least 5,000 gp, and a Tiny replica made from the same materials worth at least 50 gp)',
    duration: 'Instantaneous',
    source: "Player's Handbook",
  },
  {
    id: '315',
    name: 'Stone Shape',
    slug: 'stone-shape',
    description:
      'You touch a stone object of Medium size or smaller or a section of stone no more than 5 feet in any dimension and form it into any shape that suits your purpose. So, for example, you could shape a large rock into a weapon, idol, or coffer, or make a small passage through a wall, as long as the wall is less than 5 feet thick. You could also shape a stone door or its frame to seal the door shut. The object you create can have up to two hinges and a latch, but finer mechanical detail isn’t possible.\n\n',
    level: 4,
    school: 'TRANSMUTATION',
    castingTime: '1 action',
    range: 'Touch',
    verbal: true,
    somatic: true,
    material: true,
    materialCost:
      '(soft clay, which must be worked into roughly the desired shape of the stone object)',
    duration: 'Instantaneous',
    source: "Player's Handbook",
  },
  {
    id: '316',
    name: 'Stoneskin',
    slug: 'stoneskin',
    description:
      'This spell turns the flesh of a willing creature you touch as hard as stone. Until the spell ends, the target has resistance to nonmagical bludgeoning, piercing, and slashing damage.\n\n',
    level: 4,
    school: 'ABJURATION',
    castingTime: '1 action',
    range: 'Touch',
    verbal: true,
    somatic: true,
    material: true,
    materialCost: '(diamond dust worth 100 gp, which the spell consumes)',
    duration: 'Concentration, up to 1 hour',
    source: "Player's Handbook",
  },
];

export default SpellFourthLevelSeed;
