import { Prisma } from '@prisma/client';

const SpellFifthLevelSeed: Prisma.SpellCreateManyInput[] = [
  {
    id: '322',
    name: 'Animate Objects',
    slug: 'animate-objects',
    description:
      'Objects come to life at your command. Choose up to ten nonmagical objects within range that are not being worn or carried. Medium targets count as two objects, Large targets count as four objects, Huge targets count as eight objects. You can’t animate any object larger than Huge. Each target animates and becomes a creature under your control until the spell ends or until reduced to 0 hit points.\n\nAs a bonus action, you can mentally command any creature you made with this spell if the creature is within 500 feet of you (if you control multiple creatures, you can command any or all of them at the same time, issuing the same command to each one). You decide what action the creature will take and where it will move during its next turn, or you can issue a general command, such as to guard a particular chamber or corridor. If you issue no commands, the creature only defends itself against hostile creatures. Once given an order, the creature continues to follow it until its task is complete.\n\nAn animated object is a construct with AC, hit points, attacks, Strength, and Dexterity determine by its size. Its Constitution is 10 and its Intelligence and Wisdom are 3, and its Charisma is 1. Its speed is 30 feet; if the objects lack legs or other appendages it can use for locomotion, it instead has a flying speed of 30 feet and can hover. If the object is securely attached to a surface or larger object, such as a chain bolted to a wall, its speed is 0. It has blindsight with a radius of 30 feet and is blind beyond that distance. When the animated object drops to 0 hit points, it reverts to its original object form, and any remaining damage carries over to its original object form.\n\nIf you command an object to attack, it can make a single melee attack against a creature within 5 feet of it. It makes a slam attack with an attack bonus and bludgeoning damage determine by its size. The DM might rule that a specific object inflicts slashing or piercing damage based on its form.\n\n',
    level: 5,
    school: 'TRANSMUTATION',
    castingTime: '1 action',
    range: '120 feet',
    verbal: true,
    somatic: true,
    material: false,
    materialCost: '',
    duration: 'Concentration, up to 1 minute',
    source: "Player's Handbook",
    postTableData: '',
    extendedTable: [
      {
        '': {
          headers: ['Animated Object Statistics'],
          data: [
            { 'Animated Object Statistics': 'Size' },
            { 'Animated Object Statistics': 'Tiny' },
            { 'Animated Object Statistics': 'Small' },
            { 'Animated Object Statistics': 'Medium' },
            { 'Animated Object Statistics': 'Large' },
            { 'Animated Object Statistics': 'Huge' },
          ],
        },
      },
    ],
    options: [],
    upcastInfo:
      'If you cast this spell using a spell slot of 6th level or higher, you can animate two additional objects for each slot level above 5th.',
  },
  {
    id: '323',
    name: 'Antilife Shell',
    slug: 'antilife-shell',
    description:
      'A shimmering barrier extends out from you in a 10-foot radius and moves with you, remaining centered on you and hedging out creatures other than undead and constructs.\n\nThe barrier lasts for the duration. The barrier prevents an affected creature from passing or reaching through. An affected creature can cast spells or make attacks with ranged or reach weapons through the barrier.\n\nIf you move so that an affected creature is forced to pass through the barrier, the spell ends.\n\n',
    level: 5,
    school: 'ABJURATION',
    castingTime: '1 action',
    range: 'Self (10-foot radius)',
    verbal: true,
    somatic: true,
    material: false,
    materialCost: '',
    duration: 'Concentration, up to 1 hour',
    source: "Player's Handbook",
    postTableData: '',
    extendedTable: [],
    options: [],
    upcastInfo: '',
  },
  {
    id: '326',
    name: 'Arcane Hand',
    slug: 'arcane-hand',
    description:
      'You create a Large hand of shimmering, translucent force in an unoccupied space that you can see within range. The hand lasts for the spell’s duration, and it moves at your command, mimicking the movements of your own hand.\n\nThe hand is an object that has AC 20 and hit points equal to your hit point maximum. If it drops to 0 hit points, the spell ends. It has a Strength of 26 (+8) and a Dexterity of 10 (+0). The hand doesn’t fill its space.\n\nWhen you cast the spell and as a bonus action on your subsequent turns, you can move the hand up to 60 feet and then cause one of the following effects with it.\n\n',
    level: 5,
    school: 'EVOCATION',
    castingTime: '1 action',
    range: '120 feet',
    verbal: true,
    somatic: true,
    material: true,
    materialCost: '(an eggshell and a snakeskin glove)',
    duration: 'Concentration, up to 1 minute',
    source: "Player's Handbook",
    options: [
      'Clenched Fist. The hand strikes one creature or object within 5 feet of it. Make a melee spell attack for the hand using your game statistics. On a hit, the target takes 4d8 force damage.',
      'Forceful Hand. The hand attempts to push a creature within 5 feet of it in a direction you choose. Make a check with the hand’s Strength contested by the Strength (Athletics) check of the target. If the target is Medium or smaller, you have advantage on the check. If you succeed, the hand pushes the target up to 5 feet plus a number of feet equal to five times your spellcasting ability modifier. The hand moves with the target to remain within 5 feet of it.',
      'Grasping Hand. The hand attempts to grapple a Huge or smaller creature within 5 feet of it. You use the hand’s Strength score to resolve the grapple. If the target is Medium or smaller, you have advantage on the check. While the hand is grappling the target, you can use a bonus action to have the hand crush it. When you do so, the target takes bludgeoning damage equal to 2d6 + your spellcasting ability modifier.',
      'Interposing Hand. The hand interposes itself between you and a creature you choose until you give the hand a different command. The hand moves to stay between you and the target, providing you with half cover against the target. The target can’t move through the hand’s space if its Strength score is less than or equal to the hand’s Strength score. If its Strength score is higher than the hand’s Strength score, the target can move toward you through the hand’s space, but that space is difficult terrain for the target.',
    ],
    upcastInfo:
      'When you cast this spell using a spell slot of 6th level or higher, the damage from the clenched fist option increases by 2d8 and the damage from the grasping hand increases by 2d6 for each slot level above 5th.',
  },
  {
    id: '328',
    name: 'Cloudkill',
    slug: 'cloudkill',
    description:
      'You create a 20-foot-radius sphere of poisonous, yellow-green fog centered on a point you choose within range. The fog spreads around corners. It lasts for the duration or until strong wind disperses the fog, ending the spell. Its area is heavily obscured.\n\nWhen a creature enters the spell’s area for the first time on a turn or starts its turn there, that creature must make a Constitution saving throw. The creature takes 5d8 poison damage on a failed save, or half as much damage on a successful one. Creatures are affected even if they hold their breath or don’t need to breathe.\n\nThe fog moves 10 feet away from you at the start of each of your turns, rolling along the surface of the ground. The vapors, being heavier than air, sink to the lowest level of the land, even pouring down openings.\n\n',
    level: 5,
    school: 'CONJURATION',
    castingTime: '1 action',
    range: '120 feet',
    verbal: true,
    somatic: true,
    material: false,
    duration: 'Concentration, up to 10 minutes',
    source: "Player's Handbook",
    upcastInfo:
      'When you cast this spell using a spell slot of 6th level or higher, the damage increases by 1d8 for each slot level above 5th.',
  },
  {
    id: '330',
    name: 'Commune with Nature',
    slug: 'commune-with-nature',
    description:
      'You briefly become one with nature and gain knowledge of the surrounding territory. In the outdoors, the spell gives you knowledge of the land within 3 miles of you. In caves and other natural underground settings, the radius is limited to 300 feet. The spell doesn’t function where nature has been replaced by construction, such as in dungeons and towns.\n\nYou instantly gain knowledge of up to three facts of your choice about any of the following subjects as they relate to the area:\n\n',
    level: 5,
    school: 'DIVINATION',
    castingTime: '1 minute',
    range: 'Self',
    verbal: true,
    somatic: true,
    material: false,
    materialCost: '',
    duration: 'Instantaneous',
    source: "Player's Handbook",
    postTableData:
      'For example, you could determine the location of powerful undead in the area, the location of major sources of safe drinking water, and the location of any nearby towns.\n\n',
    options: [
      'terrain and bodies of water',
      'prevalent plants, minerals, animals, or peoples',
      'powerful celestials, fey, fiends, elementals, or undead',
      'influence from other planes of existence',
      'buildings',
    ],
  },
  {
    id: '331',
    name: 'Cone of Cold',
    slug: 'cone-of-cold',
    description:
      'A blast of cold air erupts from your hands. Each creature in a 60-foot cone must make a Constitution saving throw. A creature takes 8d8 cold damage on a failed save, or half as much damage on a successful one. A creature killed by this spell becomes a frozen statue until it thaws.\n\n',
    level: 5,
    school: 'EVOCATION',
    castingTime: '1 action',
    range: 'Self (60-foot cone)',
    verbal: true,
    somatic: true,
    material: true,
    materialCost: '(a small crystal or glass cone)',
    duration: 'Instantaneous',
    source: "Player's Handbook",
    upcastInfo:
      'When you cast this spell using a spell slot of 6th level or higher, the damage increases by 1d8 for each slot level above 5th.',
  },
  {
    id: '332',
    name: 'Conjure Elemental',
    slug: 'conjure-elemental',
    description:
      'You call forth an elemental servant. Choose an area of air, earth, fire, or water that fills a 10-foot cube within range. An elemental of challenge rating 5 or lower appropriate to the area you chose appears in an unoccupied space within 10 feet of it. For example, a fire elemental emerges from a bonfire, and an earth elemental rises up from the ground. The elemental disappears when it drops to 0 hit points or when the spell ends.\n\nThe elemental is friendly to you and your companions for the duration. Roll initiative for the elemental, which has its own turns. It obeys any verbal commands that you issue to it (no action required by you). If you don’t issue any commands to the elemental, it defends itself from hostile creatures but otherwise takes no actions.\n\nIf your concentration is broken, the elemental doesn’t disappear. Instead, you lose control of the elemental, it becomes hostile toward you and your companions, and it might attack. An uncontrolled elemental can’t be dismissed by you, and it disappears 1 hour after you summoned it. The DM has the elemental’s statistics.\n\n',
    level: 5,
    school: 'CONJURATION',
    castingTime: '1 minute',
    range: '90 feet',
    verbal: true,
    somatic: true,
    material: true,
    materialCost:
      '(burning incense for air, soft clay for earth, sulfur and phosphorus for fire, or water and sand for water)',
    duration: 'Concentration, up to 1 hour',
    source: "Player's Handbook",
    upcastInfo:
      'When you cast this spell using a spell slot of 6th level or higher, the challenge rating increases by 1 for each slot level above 5th.',
  },
  {
    id: '334',
    name: 'Contact Other Plane',
    slug: 'contact-other-plane',
    description:
      'You mentally contact a demigod, the spirit of a long-dead sage, or some other mysterious entity from another plane. Contacting this extraplanar intelligence can strain or even break your mind. When you cast this spell, make a DC 15 Intelligence saving throw. On a failure, you take 6d6 psychic damage and are insane until you finish a long rest. While insane, you can’t take actions, can’t understand what other creatures say, can’t read, and speak only in gibberish. A Greater Restoration spell cast on you ends this effect.\n\nOn a successful save, you can ask the entity up to five questions. You must ask your questions before the spell ends. The DM answers each question with one word, such as "yes," "no," "maybe," "never," "irrelevant," or "unclear" (if the entity doesn’t know the answer to the question). If a one-word answer would be misleading, the DM might instead offer a short phrase as an answer.\n\n',
    level: 5,
    school: 'DIVINATION',
    castingTime: '1 minute',
    range: 'Self',
    verbal: true,
    somatic: false,
    material: false,
    duration: '1 minute',
    source: "Player's Handbook",
  },
  {
    id: '335',
    name: 'Contagion',
    slug: 'contagion',
    description:
      'Your touch inflicts disease. Make a melee spell attack against a creature within your reach. On a hit, the target is poisoned.\n\nAt the end of each of the poisoned target’s turns, the target must make a Constitution saving throw. If the target succeeds on three of these saves, it is no longer poisoned, and the spell ends. If the target fails three of these saves, the target is no longer poisoned, but choose one of the diseases below. The target is subjected to the chosen disease for the spell’s duration.\n\nSince this spell induces a natural disease in its target, any effect that removes a disease or otherwise ameliorates a disease’s effects apply to it.\n\n',
    level: 5,
    school: 'NECROMANCY',
    castingTime: '1 action',
    range: 'Touch',
    verbal: true,
    somatic: true,
    material: false,
    duration: '7 days',
    source: "Player's Handbook",
    options: [
      'Blinding Sickness. Pain grips the creature’s mind, and its eyes turn milky white. The creature has disadvantage on Wisdom checks and Wisdom saving throws and is blinded.',
      'Filth Fever. A raging fever sweeps through the creature’s body. The creature has disadvantage on Strength checks, Strength saving throws, and attack rolls that use Strength.',
      'Flesh Rot. The creature’s flesh decays. The creature has disadvantage on Charisma checks and vulnerability to all damage.',
      'Mindfire. The creature’s mind becomes feverish. The creature has disadvantage on Intelligence checks and Intelligence saving throws, and the creature behaves as if under the effects of the confusion spell during combat.',
      'Seizure. The creature is overcome with shaking. The creature has disadvantage on Dexterity checks, Dexterity saving throws, and attack rolls that use Dexterity.',
      'Slimy Doom. The creature begins to bleed uncontrollably. The creature has disadvantage on Constitution checks and Constitution saving throws. In addition, whenever the creature takes damage, it is stunned until the end of its next turn.',
    ],
  },
  {
    id: '338',
    name: 'Creation',
    slug: 'creation',
    description:
      'You pull wisps of shadow material from the Shadowfell to create a nonliving object of vegetable matter within range: soft goods, rope, wood, or something similar. You can also use this spell to create mineral objects such as stone, crystal, or metal. The object created must be no larger than a 5-foot cube, and the object must be of a form and material that you have seen before.\n\nThe duration depends on the object’s material. If the object is composed of multiple materials, use the shortest duration.\n\nUsing any material created by this spell as another spell’s material component causes that spell to fail.\n\n',
    level: 5,
    school: 'ILLUSION',
    castingTime: '1 minute',
    range: '30 feet',
    verbal: true,
    somatic: true,
    material: true,
    materialCost:
      '(a tiny piece of matter of the same type of the item you plan to create)',
    duration: 'Special',
    source: "Player's Handbook",
    extendedTable: [
      {
        '': {
          headers: ['Material', 'Duration'],
          data: [
            { Material: 'Vegetable matter', Duration: '1 day' },
            { Material: 'Stone, crystal', Duration: '12 hours' },
            { Material: 'Precious metals', Duration: '1 hour' },
            { Material: 'Gems', Duration: '10 minutes' },
            { Material: 'Adamantine, Mithral', Duration: '1 minute' },
          ],
        },
      },
    ],
    upcastInfo:
      'When you cast this spell using a spell slot of 6th level or higher, the cube increases by 5 feet for each slot level above 5th.',
  },
  {
    id: '342',
    name: 'Dispel Evil and Good',
    slug: 'dispel-evil-and-good',
    description:
      'Shimmering energy surrounds and protects you from fey, undead, and creatures originating from beyond the Material Plane. For the duration, celestials, elementals, fey, fiends, and undead have disadvantage on attack rolls against you. You can end the spell early by using either of the following special functions.\n\n',
    level: 5,
    school: 'ABJURATION',
    castingTime: '1 action',
    range: 'Self',
    verbal: true,
    somatic: true,
    material: true,
    materialCost: '(holy water or powdered silver and iron)',
    duration: 'Concentration, up to 1 minute',
    source: "Player's Handbook",
    options: [
      'Break Enchantment. As your action, you touch a creature you can reach that is charmed, frightened, or possessed by a celestial, an elemental, a fey, a fiend, or an undead. The creature you touch is no longer charmed, frightened, or possessed by such creatures.',
      'Dismissal. As your action, make a melee spell attack against a celestial, an elemental, a fey, a fiend, or an undead you can reach. On a hit, you attempt to drive the creature back to its home plane. The creature must succeed on a Charisma saving throw or be sent back to its home plane (if it isn’t there already). If they are already on their home plane, undead are sent to the Shadowfell, and fey are sent to the Feywild.',
    ],
  },

  {
    id: '343',
    name: 'Dominate Person',
    slug: 'dominate-person',
    description:
      'You attempt to beguile a humanoid that you can see within range. It must succeed on a Wisdom saving throw or be charmed by you for the duration. If you or creatures that are friendly to you are fighting it, it has advantage on the saving throw.\n\nWhile the target is charmed, you have a telepathic link with it as long as the two of you are on the same plane of existence. You can use this telepathic link to issue commands to the creature while you are conscious (no action required), which it does its best to obey. You can specify a simple and general course of action, such as "Attack that creature", "Run over there", or "Fetch that object". If the creature completes the order and doesn’t receive further direction from you, it defends and preserves itself to the best of its ability.\n\nYou can use your action to take total and precise control of the target. Until the end of your next turn, the creature takes only the actions you choose, and doesn’t do anything that you don’t allow it to do. During this time you can also cause the creature to use a reaction, but this requires you to use your own reaction as well.\n\nEach time the target takes damage, it makes a new Wisdom saving throw against the spell. If the saving throw succeeds, the spell ends.\n\n',
    level: 5,
    school: 'ENCHANTMENT',
    castingTime: '1 action',
    range: '60 feet',
    verbal: true,
    somatic: true,
    material: false,
    duration: 'Concentration, up to 1 minute',
    source: "Player's Handbook",
    upcastInfo:
      'When you cast this spell using a 6th-level spell slot, the duration is concentration, up to 10 minutes. When you use a 7th-level spell slot, the duration is concentration, up to 1 hour. When you use a spell slot of 8th level or higher, the duration is concentration, up to 8 hours.',
  },

  {
    id: '344',
    name: 'Dream',
    slug: 'dream',
    description:
      'This spell shapes a creature’s dreams. Choose a creature known to you as the target of this spell. The target must be on the same plane of existence as you. Creatures that don’t sleep, such as elves, can’t be contacted by this spell. You, or a willing creature you touch, enters a trance state, acting as a messenger. While in the trance, the messenger is aware of their surroundings, but can’t take actions or move.\n\nIf the target is asleep, the messenger appears in the target’s dreams and can converse with the target as long as it remains asleep, through the duration of the spell. The messenger can also shape the environment of the dream, creating landscapes, objects, and other images. The messenger can emerge from the trance at any time, ending the effect of the spell early. The target recalls the dream perfectly upon waking. If the target is awake when you cast the spell, the messenger knows it, and can either end the trance (and the spell) or wait for the target to fall asleep, at which point the messenger appears in the target’s dreams.\n\nYou can make the messenger appear monstrous and terrifying to the target. If you do, the messenger can deliver a message of no more than ten words and then the target must make a Wisdom saving throw. On a failed save, echoes of the phantasmal monstrosity spawn a nightmare that lasts the duration of the target’s sleep and prevents the target from gaining any benefit from that rest. In addition, when the target wakes up, it takes 3d6 psychic damage.\n\nIf you have a body part, lock of hair, clipping from a nail, or similar portion of the target’s body, the target makes its saving throw with disadvantage.\n\n',
    level: 5,
    school: 'ILLUSION',
    castingTime: '1 minute',
    range: 'Special',
    verbal: true,
    somatic: true,
    material: true,
    materialCost:
      '(a handful of sand, a dab of ink, and a writing quill plucked from a sleeping bird)',
    duration: '8 hours',
    source: "Player's Handbook",
  },
  {
    id: '347',
    name: 'Flame Strike',
    slug: 'flame-strike',
    description:
      'A vertical column of divine fire roars down from the heavens in a location you specify. Each creature in a 10-foot radius, 40-foot-high cylinder centered on a point within range must make a Dexterity saving throw. A creature takes 4d6 fire damage and 4d6 radiant damage on a failed save, or half as much damage on a successful one.\n\n',
    level: 5,
    school: 'EVOCATION',
    castingTime: '1 action',
    range: '60 feet',
    verbal: true,
    somatic: true,
    material: true,
    materialCost: '(pinch of sulfur)',
    duration: 'Instantaneous',
    source: "Player's Handbook",
    upcastInfo:
      'When you cast this spell using a spell slot of 6th level or higher, the fire damage or the radiant damage (your choice) increases by 1d6 for each slot level above 5th.',
  },
  {
    id: '348',
    name: 'Geas',
    slug: 'geas',
    description:
      'You place a magical command on a creature that you can see within range, forcing it to carry out some service or refrain from some action or course of activity as you decide.\n\nIf the creature can understand you, it must succeed on a Wisdom saving throw or become charmed by you for the duration. While the creature is charmed by you, it takes 5d10 psychic damage each time it acts in a manner directly counter to your instructions, but no more than once each day. A creature that can’t understand you is unaffected by the spell.\n\nYou can issue any command you choose, short of an activity that would result in certain death. Should you issue a suicidal command, the spell ends. You can end the spell early by using an action to dismiss it. A Remove Curse, Greater Restoration, or Wish spell also ends it.\n\n',
    level: 5,
    school: 'ENCHANTMENT',
    castingTime: '1 minute',
    range: '60 feet',
    verbal: true,
    somatic: false,
    material: false,
    duration: '30 days',
    source: "Player's Handbook",
    upcastInfo:
      'When you cast this spell using a spell slot of 7th or 8th level, the duration is 1 year. When you cast this spell using a spell slot of 9th level, the spell lasts until it is ended by one of the spells mentioned above.',
  },
  {
    id: '349',
    name: 'Greater Restoration',
    slug: 'greater-restoration',
    description:
      'You imbue a creature you touch with positive energy to undo a debilitating effect. You can reduce the target’s exhaustion level by one, or end one of the following effects on the target:\n\n',
    level: 5,
    school: 'ABJURATION',
    castingTime: '1 action',
    range: 'Touch',
    verbal: true,
    somatic: true,
    material: true,
    materialCost:
      '(diamond dust worth at least 100 gp, which the spell consumes)',
    duration: 'Instantaneous',
    source: "Player's Handbook",
    options: [
      'One effect that charmed or petrified the target',
      'One curse, including the target’s attunement to a cursed magic item',
      'Any reduction to one of the target’s ability scores',
      'One effect reducing the target’s hit point maximum',
    ],
  },
  {
    id: '350',
    name: 'Hallow',
    slug: 'hallow',
    description:
      'You touch a point and infuse an area around it with holy (or unholy) power. The area can have a radius up to 60 feet, and the spell fails if the radius includes an area already under the effect a hallow spell. The affected area is subject to the following effects.\n\nFirst, celestials, elementals, fey, fiends, and undead can’t enter the area, nor can such creatures charm, frighten, or possess creatures within it. Any creature charmed, frightened, or possessed by such a creature is no longer charmed, frightened, or possessed upon entering the area. You can exclude one or more of those types of creatures from this effect.\n\nSecond, you can bind an extra effect to the area. Choose the effect from the following list, or choose an effect offered by the DM. Some of these effects apply to creatures in the area; you can designate whether the effect applies to all creatures, creatures that follow a specific deity or leader, or creatures of a specific sort, such as orcs or trolls. When a creature that would be affected enters the spell’s area for the first time on a turn or starts its turn there, it can make a Charisma saving throw. On a success, the creature ignores the extra effect until it leaves the area.\n\n',
    level: 5,
    school: 'EVOCATION',
    castingTime: '24 hours',
    range: 'Touch',
    verbal: true,
    somatic: true,
    material: true,
    materialCost:
      '(herbs, oils, and incense worth at least 1,000 gp, which the spell consumes)',
    duration: 'Until dispelled',
    source: "Player's Handbook",
    options: [
      'Courage. Affected creatures can’t be frightened while in the area.',
      'Darkness. Darkness fills the area. Normal light, as well as magical light created by spells of a lower level than the slot you used to cast this spell, can’t illuminate the area.',
      'Daylight. Bright light fills the area. Magical darkness created by spells of a lower level than the slot you used to cast this spell can’t extinguish the light.',
      'Energy Protection. Affected creatures in the area have resistance to one damage type of your choice, except for bludgeoning, piercing, or slashing.',
      'Energy Vulnerability. Affected creatures in the area have vulnerability to one damage type of your choice, except for bludgeoning, piercing, or slashing.',
      'Everlasting Rest. Dead bodies interred in the area can’t be turned into undead.',
      'Extradimensional Interference. Affected creatures can’t move or travel using teleportation or by extradimensional or interplanar means.',
      'Fear. Affected creatures are frightened while in the area.',
      'Silence. No sound can emanate from within the area, and no sound can reach into it.',
      'Tongues. Affected creatures can communicate with any other creature in the area, even if they don’t share a common language.',
    ],
  },
  {
    id: '351',
    name: 'Hold Monster',
    slug: 'hold-monster',
    description:
      'Choose a creature that you can see within range. The target must succeed on a Wisdom saving throw or be paralyzed for the duration. This spell has no effect on undead. At the end of each of its turns, the target can make another Wisdom saving throw. On a success, the spell ends on the target.\n\n',
    level: 5,
    school: 'ENCHANTMENT',
    castingTime: '1 action',
    range: '90 feet',
    verbal: true,
    somatic: true,
    material: true,
    materialCost: '(a small, straight piece of iron)',
    duration: 'Concentration, up to 1 minute',
    source: "Player's Handbook",
    upcastInfo:
      'When you cast this spell using a spell slot of 6th level or higher, you can target one additional creature for each slot level above 5th. The creatures must be within 30 feet of each other when you target them.',
  },
  {
    id: '355',
    name: 'Insect Plague',
    slug: 'insect-plague',
    description:
      'Swarming, biting locusts fill a 20-foot-radius sphere centered on a point you choose within range. The sphere spreads around corners. The sphere remains for the duration, and its area is lightly obscured. The sphere’s area is difficult terrain.\n\nWhen the area appears, each creature in it must make a Constitution saving throw. A creature takes 4d10 piercing damage on a failed save, or half as much damage on a successful one. A creature must also make this saving throw when it enters the spell’s area for the first time on a turn or ends its turn there.\n\n',
    level: 5,
    school: 'CONJURATION',
    castingTime: '1 action',
    range: '300 feet',
    verbal: true,
    somatic: true,
    material: true,
    materialCost:
      '(a few grains of sugar, some kernels of grain, and a smear of fat)',
    duration: 'Concentration, up to 10 minutes',
    source: "Player's Handbook",
    upcastInfo:
      'When you cast this spell using a spell slot of 6th level or higher, the damage increases by 1d10 for each slot level above 5th.',
  },
  {
    id: '356',
    name: 'Legend Lore',
    slug: 'legend-lore',
    description:
      'Name or describe a person, place, or object. The spell brings to your mind a brief summary of the significant lore about the thing you named. The lore might consist of current tales, forgotten stories, or even secret lore that has never been widely known. If the thing you named isn’t of legendary importance, you gain no information. The more information you already have about the thing, the more precise and detailed the information you receive is.\n\nThe information you learn is accurate but might be couched in figurative language. For example, if you have a mysterious magic axe on hand, the spell might yield this information: Woe to the evildoer whose hand touches the axe, for even the haft slices the hand of the evil ones. Only a true Child of Stone, lover and beloved of Moradin, may awaken the true powers of the axe, and only with the sacred word Rudnogg on the lips.\n\n',
    level: 5,
    school: 'DIVINATION',
    castingTime: '10 minutes',
    range: 'Self',
    verbal: true,
    somatic: true,
    material: true,
    materialCost:
      '(incense worth at least 250 gp, which the spell consumes, and four ivory strips worth at least 50 gp each)',
    duration: 'Instantaneous',
    source: "Player's Handbook",
  },
  {
    id: '358',
    name: 'Mass Cure Wounds',
    slug: 'mass-cure-wounds',
    description:
      'A wave of healing energy washes out from a point of your choice within range. Choose up to six creatures in a 30-foot-radius sphere centered on that point. Each target regains hit points equal to 3d8 + your spellcasting ability modifier. This spell has no effect on undead or constructs.\n\n',
    level: 5,
    school: 'EVOCATION',
    castingTime: '1 action',
    range: '60 feet',
    verbal: true,
    somatic: true,
    material: false,
    duration: 'Instantaneous',
    source: "Player's Handbook",
    upcastInfo:
      'When you cast this spell using a spell slot of 6th level or higher, the healing increases by 1d8 for each slot level above 5th.',
  },
  {
    id: '359',
    name: 'Mislead',
    slug: 'mislead',
    description:
      'You become invisible at the same time that an illusory double of you appears where you are standing. The double lasts for the duration, but the invisibility ends if you attack or cast a spell.\n\nYou can use your action to move your illusory double up to twice your speed and make it gesture, speak, and behave in whatever way you choose.\n\nYou can see through its eyes and hear through its ears as if you were located where it is. On each of your turns as a bonus action, you can switch from using its senses to using your own, or back again. While you are using its senses, you are blinded and deafened in regard to your own surroundings.\n\n',
    level: 5,
    school: 'ILLUSION',
    castingTime: '1 action',
    range: 'Self',
    verbal: false,
    somatic: true,
    material: false,
    duration: 'Concentration, up to 1 hour',
    source: "Player's Handbook",
  },
  {
    id: '360',
    name: 'Modify Memory',
    slug: 'modify-memory',
    description:
      'You attempt to reshape another creature’s memories. One creature that you can see must make a Wisdom saving throw. If you are fighting the creature, it has advantage on the saving throw. On a failed save, the target becomes charmed by you for the duration. The charmed target is incapacitated and unaware of its surroundings, though it can still hear you. If it takes any damage or is targeted by another spell, this spell ends, and none of the target’s memories are modified.\n\nWhile this charm lasts, you can affect the target’s memory of an event that it experienced within the last 24 hours and that lasted no more than 10 minutes. You can permanently eliminate all memory of the event, allow the target to recall the event with perfect clarity and exacting detail, change its memory of the details of the event, or create a memory of some other event.\n\nYou must speak to the target to describe how its memories are affected, and it must be able to understand your language for the modified memories to take root. Its mind fills in any gaps in the details of your description. If the spell ends before you have finished describing the modified memories, the creature’s memory isn’t altered. Otherwise, the modified memories take hold when the spell ends.\n\nA modified memory doesn’t necessarily affect how a creature behaves, particularly if the memory contradicts the creature’s natural inclinations, alignment, or beliefs. An illogical modified memory, such as implanting a memory of how much the creature enjoyed dousing itself in acid, is dismissed, perhaps as a bad dream. The DM might deem a modified memory too nonsensical to affect a creature in a significant manner.\n\nA Remove Curse or Greater Restoration spell cast on the target restores the creature’s true memory.\n\n',
    level: 5,
    school: 'ENCHANTMENT',
    castingTime: '1 action',
    range: '30 feet',
    verbal: true,
    somatic: true,
    material: false,
    duration: 'Concentration, up to 1 minute',
    source: "Player's Handbook",
    upcastInfo:
      'If you cast this spell using a spell slot of 6th level or higher, you can alter the target’s memories of an event that took place up to 7 days ago (6th level), 30 days ago (7th level), 1 year ago (8th level), or any time in the creature’s past (9th level).',
  },
  {
    id: '362',
    name: 'Passwall',
    slug: 'passwall',
    description:
      'A passage appears at a point of your choice that you can see on a wooden, plaster, or stone surface (such as a wall, a ceiling, or a floor) within range, and lasts for the duration. You choose the opening’s dimensions: up to 5 feet wide, 8 feet tall, and 20 feet deep. The passage creates no instability in a structure surrounding it.\n\nWhen the opening disappears, any creatures or objects still in the passage created by the spell are safely ejected to an unoccupied space nearest to the surface on which you cast the spell.\n\n',
    level: 5,
    school: 'TRANSMUTATION',
    castingTime: '1 action',
    range: '30 feet',
    verbal: true,
    somatic: true,
    material: true,
    materialCost: '(a pinch of sesame seeds)',
    duration: '1 hour',
    source: "Player's Handbook",
  },
  {
    id: '363',
    name: 'Planar Binding',
    slug: 'planar-binding',
    description:
      'With this spell, you attempt to bind a celestial, an elemental, a fey, or a fiend to your service. The creature must be within range for the entire casting of the spell. (Typically, the creature is first summoned into the center of an inverted Magic Circle in order to keep it trapped while this spell is cast.) At the completion of the casting, the target must make a Charisma saving throw. On a failed save, it is bound to serve you for the duration. If the creature was summoned or created by another spell, that spell’s duration is extended to match the duration of this spell.\n\nA bound creature must follow your instructions to the best of its ability. You might command the creature to accompany you on an adventure, to guard a location, or to deliver a message. The creature obeys the letter of your instructions, but if the creature is hostile to you, it strives to twist your words to achieve its own objectives. If the creature carries out your instructions completely before the spell ends, it travels to you to report this fact if you are on the same plane of existence. If you are on a different plane of existence, it returns to the place where you bound it and remains there until the spell ends.\n\n',
    level: 5,
    school: 'ABJURATION',
    castingTime: '1 hour',
    range: '60 feet',
    verbal: true,
    somatic: true,
    material: true,
    materialCost: '(a jewel worth at least 1,000 gp, which the spell consumes)',
    duration: '24 hours',
    source: "Player's Handbook",
    upcastInfo:
      'When you cast this spell using a spell slot of a higher level, the duration increases to 10 days with a 6th-level slot, 30 days with a 7th-level slot, 180 days with an 8th-level slot, or 1 year and 1 day with a 9th-level spell slot.',
  },
  {
    id: '364',
    name: 'Raise Dead',
    slug: 'raise-dead',
    description:
      'You return a dead creature you touch to life, provided that it has been dead no longer than 10 days. If the creature’s soul is both willing and at liberty to rejoin the body, the creature returns to life with 1 hit point.\n\nThis spell also neutralizes any poison and cures nonmagical diseases that affected the creature at the time it died. This spell doesn’t, however, remove magical diseases, curses, or similar effects; if these aren’t first removed prior to casting the spell, they take effect when the creature returns to life. The spell can’t return an undead creature to life.\n\nThis spell closes all mortal wounds, but it doesn’t restore missing body parts. If the creature is lacking body parts or organs integral for its survival – its head, for instance – the spell automatically fails.\n\nComing back from the dead is an ordeal. The target takes a -4 penalty to all attack rolls, saving throws, and ability checks. Every time the target finishes a long rest, the penalty is reduced by 1 until it disappears.\n\n',
    level: 5,
    school: 'NECROMANCY',
    castingTime: '1 hour',
    range: 'Touch',
    verbal: true,
    somatic: true,
    material: true,
    materialCost: '(a diamond worth at least 500 gp, which the spell consumes)',
    duration: 'Instantaneous',
    source: "Player's Handbook",
  },
  {
    id: '366',
    name: 'Reincarnate',
    slug: 'reincarnate',
    description:
      'You touch a dead humanoid or a piece of a dead humanoid. Provided that the creature has been dead no longer than 10 days, the spell forms a new adult body for it and then calls the soul to enter that body. If the target’s soul isn’t free or willing to do so, the spell fails.\n\nThe magic fashions a new body for the creature to inhabit, which likely causes the creature’s species to change. The DM rolls a d100 and consults the following table to determine what form the creature takes when restored to life, or the DM chooses a form.\n\nThe reincarnated creature recalls its former life and experiences. It retains the capabilities it had in its original form, except it exchanges its original species for the new one and changes its racial traits accordingly.\n\n',
    level: 5,
    school: 'TRANSMUTATION',
    castingTime: '1 hour',
    range: 'Touch',
    verbal: true,
    somatic: true,
    material: true,
    materialCost:
      '(rare oils and unguents worth at least 1,000 gp, which the spell consumes)',
    duration: 'Instantaneous',
    source: "Player's Handbook",
    extendedTable: [
      {
        '': {
          headers: ['Reincarnation Table'],
          data: [
            { 'Reincarnation Table': 'd100' },
            { 'Reincarnation Table': '01-04' },
            { 'Reincarnation Table': '05-13' },
            { 'Reincarnation Table': '14-21' },
            { 'Reincarnation Table': '22-25' },
            { 'Reincarnation Table': '26-34' },
            { 'Reincarnation Table': '35-42' },
            { 'Reincarnation Table': '43-46' },
            { 'Reincarnation Table': '47-52' },
            { 'Reincarnation Table': '53-56' },
            { 'Reincarnation Table': '57-60' },
            { 'Reincarnation Table': '61-68' },
            { 'Reincarnation Table': '69-76' },
            { 'Reincarnation Table': '77-96' },
            { 'Reincarnation Table': '97-00' },
          ],
        },
      },
    ],
  },
  {
    id: '367',
    name: 'Scrying',
    slug: 'scrying',
    description:
      'You can see and hear a particular creature you choose that is on the same plane of existence as you. The target must make a Wisdom saving throw, which is modified by how well you know the target and the sort of physical connection you have to it. If a target knows you’re casting this spell, it can fail the saving throw voluntarily if it wants to be observed.\n\nOn a successful save, the target isn’t affected, and you can’t use this spell against it again for 24 hours.\n\nOn a failed save, the spell creates an invisible sensor within 10 feet of the target. You can see and hear through the sensor as if you were there. The sensor moves with the target, remaining within 10 feet of it for the duration. A creature that can see invisible objects sees the sensor as a luminous orb about the size of your fist.\n\nInstead of targeting a creature, you can choose a location you have seen before as the target of this spell. When you do, the sensor appears at that location and doesn’t move.\n\n',
    level: 5,
    school: 'DIVINATION',
    castingTime: '10 minutes',
    range: 'Self',
    verbal: true,
    somatic: true,
    material: true,
    materialCost:
      '(a focus worth at least 1,000 gp, such as a crystal ball, a silver mirror, or a font filled with holy water)',
    duration: 'Concentration, up to 10 minutes',
    source: "Player's Handbook",
    extendedTable: [
      {
        '': {
          headers: ['Knowledge', 'Save Modifier'],
          data: [
            {
              Knowledge: 'Secondhand (you have heard of the target)',
              'Save Modifier': '+5',
            },
            {
              Knowledge: 'Firsthand (you have met the target)',
              'Save Modifier': '+0',
            },
            {
              Knowledge: 'Familiar (you know the target well)',
              'Save Modifier': '-5',
            },
          ],
        },
      },
      {
        '': {
          headers: ['Connection', 'Save Modifier'],
          data: [
            { Connection: 'Likeness or picture', 'Save Modifier': '-2' },
            { Connection: 'Possession or garment', 'Save Modifier': '-4' },
            {
              Connection: 'Body part, lock of hair, bit of nail, or the like ',
              'Save Modifier': '-10',
            },
          ],
        },
      },
    ],
  },
  {
    id: '368',
    name: 'Seeming',
    slug: 'seeming',
    description:
      'This spell allows you to change the appearance of any number of creatures that you can see within range. You give each target you choose a new, illusory appearance. An unwilling target can make a Charisma saving throw, and if it succeeds, it is unaffected by this spell.\n\nThe spell disguises physical appearances as well as clothing, armor, weapons, and equipment. You can make each creature seem 1 foot shorter or taller and appear thin, fat, or in-between. You can’t change a target’s body type, so you must choose a form that has the same basic arrangement of limbs. Otherwise, the extent of the illusion is up to you. The spell lasts for the duration, unless you use your action to dismiss it sooner.\n\nThe changes wrought by this spell fail to hold up to physical inspections. For example, if you use this spell to add a hat to a creature’s outfit, objects pass through the hat, and anyone who touches it would feel nothing or would feel the creature’s head and hair. If you use this spell to appear thinner then you are, the hand of someone who reaches out to touch you would bump into you while it was seemingly still in midair.\n\nA creature can use its action to inspect a target and make an Intelligence (Investigation) check against your spell save DC. If it succeeds, it becomes aware that the target is disguised.\n\n',
    level: 5,
    school: 'ILLUSION',
    castingTime: '1 action',
    range: '30 feet',
    verbal: true,
    somatic: true,
    material: false,
    duration: '8 hours',
    source: "Player's Handbook",
  },

  {
    id: '365',
    name: 'Telepathic Bond',
    slug: 'telepathic-bond',
    description:
      'You forge a telepathic link among up to eight willing creatures of your choice within range, psychically linking each creature to all the others for the duration. Creatures with Intelligence scores of 2 or less aren’t affected by this spell.\n\nUntil the spell ends, the targets can communicate telepathically through the bond whether or not they have a common language. The communication is possible over any distance, though it can’t extend to other planes of existence.\n\n',
    level: 5,
    school: 'DIVINATION',
    castingTime: '1 action',
    range: '30 feet',
    verbal: true,
    somatic: true,
    material: true,
    materialCost: '(pieces of eggshell from two different kinds of creatures)',
    duration: '1 hour',
    source: "Player's Handbook",
  },
  {
    id: '373',
    name: 'Teleportation Circle',
    slug: 'teleportation-circle',
    description:
      'As you cast the spell, you draw a 10-foot-diameter circle on the ground inscribed with sigils that link your location to a permanent teleportation circle of your choice whose sigil sequence you know and that is on the same plane of existence as you.\n\nA shimmering portal opens within the circle you drew and remains open until the end of your next turn. Any creature that enters the portal instantly appears within 5 feet of the destination circle or in the nearest unoccupied space if that space is occupied.\n\nMany major temples, guilds, and other important places have permanent teleportation circles inscribed somewhere within their confines. Each such circle includes a unique sigil sequence – a string of magical runes arranged in a particular pattern. When you first gain the ability to cast this spell, you learn the sigil sequences for two destinations on the Material Plane, determined by the DM. You can learn additional sigil sequences during your adventures. You can commit a new sigil sequence to memory after studying it for 1 minute.\n\nYou can create a permanent teleportation circle by casting this spell in the same location every day for one year. You need not use the circle to teleport when you cast the spell in this way.\n\n',
    level: 5,
    school: 'CONJURATION',
    castingTime: '1 minute',
    range: '10 feet',
    verbal: true,
    somatic: false,
    material: true,
    materialCost:
      '(rare chalks and inks infused with precious gems worth 50 gp, which the spell consumes)',
    duration: '1 round',
    source: "Player's Handbook",
  },
  {
    id: '375',
    name: 'Tree Stride',
    slug: 'tree-stride',
    description:
      'You gain the ability to enter a tree and move from inside it to inside another tree of the same kind within 500 feet.\n\nBoth trees must be living and at least the same size as you. You must use 5 feet of movement to enter a tree. You instantly know the location of all other trees of the same kind within 500 feet and, as part of the move used to enter the tree, can either pass into one of those trees or step out of the tree you’re in. You appear in a spot of your choice within 5 feet of the destination tree, using another 5 feet of movement. If you have no movement left, you appear within 5 feet of the tree you entered.\n\nYou can use this transportation ability once per round for the duration. You must end each turn outside a tree.\n\n',
    level: 5,
    school: 'CONJURATION',
    castingTime: '1 action',
    range: 'Self',
    verbal: true,
    somatic: true,
    material: false,
    duration: 'Concentration, up to 1 minute',
    source: "Player's Handbook",
  },
  {
    id: '320',
    name: 'Wall of Fire',
    slug: 'wall-of-fire',
    description:
      'You create a wall of fire on a solid surface within range. You can make the wall up to 60 feet long, 20 feet high, and 1 foot thick, or a ringed wall up to 20 feet in diameter, 20 feet high, and 1 foot thick. The wall is opaque and lasts for the duration.\n\nWhen the wall appears, each creature within its area must make a Dexterity saving throw. On a failed save, a creature takes 5d8 fire damage, or half as much damage on a successful save.\n\nOne side of the wall, selected by you when you cast this spell, deals 5d8 fire damage to each creature that ends its turn within 10 feet of that side or inside the wall. A creature takes the same damage when it enters the wall for the first time on a turn or ends its turn there. The other side of the wall deals no damage.\n\n',
    level: 4,
    school: 'EVOCATION',
    castingTime: '1 action',
    range: '120 feet',
    verbal: true,
    somatic: true,
    material: true,
    materialCost: '(a small piece of phosphorus)',
    duration: 'Concentration, up to 1 minute',
    source: "Player's Handbook",
    upcastInfo:
      'When you cast this spell using a spell slot of 5th level or higher, the damage increases by 1d8 for each slot level above 4th.',
  },
  {
    id: '376',
    name: 'Wall of Force',
    slug: 'wall-of-force',
    description:
      "An invisible wall of force springs into existence at a point you choose within range.The wall appears in any orientation you choose, as a horizontal or vertical barrier or at an angle. It can be free floating or resting on a solid surface. You can form it into a hemispherical dome or a sphere with a radius of up to 10 feet, or you can shape a flat surface made up of ten 10-foot-by-10-foot panels. Each panel must be contiguous with another panel. In any form, the wall is 1/4 inch thick. It lasts for the duration. If the wall cuts through a creature's space when it appears, the creature is pushed to one side of the wall (your choice which side).\n\nNothing can physically pass through the wall. It is immune to all damage and can't be dispelled by dispel magic. A disintegrate spell destroys the wall instantly, however. The wall also extends into the Ethereal Plane, blocking ethereal travel through the wall.",
    level: 5,
    school: 'EVOCATION',
    castingTime: '1 action',
    range: '120 feet',
    verbal: true,
    somatic: true,
    material: true,
    materialCost: '(a pinch of powder made by crushing a clear gemstone)',
    duration: 'Concentration, up to 10 minutes',
    source: "Player's Handbook",
  },
  {
    id: '378',
    name: 'Wall of Stone',
    slug: 'wall-of-stone',
    description:
      'A nonmagical wall of solid stone springs into existence at a point you choose within range. The wall is 6 inches thick and is composed of ten 10-foot-by-10-foot panels. Each panel must be contiguous with at least on other panel. Alternatively, you can create 10-foot-by-20-foot panels that are only 3 inches thick.\n\nIf the wall cuts through a creature’s space when it appears, the creature is pushed to one side of the wall (your choice). If a creature would be surrounded on all sides by the wall (or the wall and another solid surface), that creature can make a Dexterity saving throw. On a success, it can use its reaction to move up to its speed so that it is no longer enclosed by the wall.\n\nThe wall can have any shape you desire, though it can’t occupy the same space as a creature or object. the wall doesn’t need to be vertical or resting on any firm foundation. It must, however, merge with and be solidly supported by existing stone. Thus you can use this spell to bridge a chasm or create a ramp.\n\nIf you create a span greater than 20 feet in length, you must halve the size of each panel to create supports. You can crudely shape the wall to create crenelations, battlements, and so on.\n\nThe wall is an object made of stone that can be damaged and thus breached. Each panel has AC 15 and 30 hit points per inch of thickness. Reducing a panel to 0 hit points destroys it and might cause connected panels to collapse at the DM’s discretion.\n\nIf you maintain your concentration on this spell for its whole duration, the wall becomes permanent and can’t be dispelled. Otherwise, the wall disappears when the spell ends.\n\n',
    level: 5,
    school: 'EVOCATION',
    castingTime: '1 action',
    range: '120 feet',
    verbal: true,
    somatic: true,
    material: true,
    materialCost: '(a small block of granite)',
    duration: 'Concentration, up to 10 minutes',
    source: "Player's Handbook",
    postTableData: '',
    extendedTable: [],
    options: [],
    upcastInfo: '',
  },
];

export default SpellFifthLevelSeed;
