import { Prisma } from '@prisma/client';

const SpellEighthLevelSeed: Prisma.SpellCreateManyInput[] = [
  {
    id: '450',
    name: 'Animal Shapes',
    slug: 'animal-shapes',
    description:
      'Your magic turns others into beasts. Choose any number of willing creatures that you can see within range. You transform each target into the form of a large or smaller beast with a challenge rating of 4 or lower. On subsequent turns, you can use your actions to transform affected creatures into new forms.\n\nThe transformation lasts for the duration for each target, or until the target drops to 0 hit points or dies. You can choose a different form for each target. A target’s game statistics are replaced by the statistics of the chosen beast, though the target retains its alignment and Intelligence, Wisdom, and Charisma scores. The target assumes the hit points of its new form, and when it reverts to its normal form, it returns to the number of hit point it had before it transformed. If it reverts as a result of dropping to 0 hit points, any excess damage carries over to its normal form. As long as the excess damage doesn’t reduce the creature’s normal form to 0 hit points, it isn’t knocked unconcious. The creature is limited in the actions it can perform by the nature of its new form, and it can’t speak or cast spells.\n\nThe target’s gear melds into the new form. The target can’t activate, wield, or otherwise benefit from any of its equipment.\n\n',
    level: 8,
    school: 'TRANSMUTATION',
    castingTime: '1 action',
    range: '30 feet',
    verbal: true,
    somatic: true,
    material: false,
    duration: 'Concentration, up to 24 hours',
    source: "Player's Handbook",
  },

  {
    id: '451',
    name: 'Antimagic Field',
    slug: 'antimagic-field',
    description:
      "A 10-foot-radius invisible sphere of antimagic surrounds you. This area is divorced from the magical energy that suffuses the multiverse. Within the sphere, spells can't be cast, summoned creatures disappear, and even magic items become mundane. Until the spell ends, the sphere moves with you, centered on you.\n\nSpells and other magical effects, except those created by an artifact or a deity, are suppressed in the sphere and can't protrude into it. A slot expended to cast a suppressed spell is consumed. While an effect is suppressed, it doesn't function, but the time it spends suppressed counts against its duration.\n\n",
    level: 8,
    school: 'ABJURATION',
    castingTime: '1 action',
    range: 'Self (10-foot-radius sphere)',
    verbal: true,
    somatic: true,
    material: true,
    materialCost: '(a pinch of powdered iron or iron filings)',
    duration: 'Concentration, up to 1 hour',
    source: "Player's Handbook",
    postTableData: '',
    extendedTable: [],
    options: [
      'Targeted Effects. Spells and other magical effects, such as magic missile and charm person, that target a creature or an object in the sphere have no effect on that target.',
      "Areas of Magic. The area of another spell or magical effect, such as fireball, can't extend into the sphere. If the sphere overlaps an area of magic, the part of the area that is covered by the sphere is suppressed. For example, the flames created by a wall of fire are suppressed within the sphere, creating a gap in the wall if the overlap is large enough.",
      'Spells. Any active spell or other magical effect on a creature or an object in the sphere is suppressed while the creature or object is in it.',
      "Magic Items. The properties and powers of magic items are suppressed in the sphere. For example, a +1 longsword in the sphere functions as a nonmagical longsword. A magic weapon's properties and powers are suppressed if it is used against a target in the sphere or wielded by an attacker in the sphere. If a magic weapon or piece of magic ammunition fully leaves the sphere (for example, if you fire a magic arrow or throw a magic spear at a target outside the sphere) the magic of the item ceases to be suppressed as soon as it exits.",
      'Magical Travel. Teleportation and planar travel fail to work in the sphere, whether the sphere is the destination or the departure point for such magical travel. A portal to another location, world, or plane of existence, as well as an opening to an extradimensional space such as that created by the rope trick spells, temporarily closes while in the sphere.',
      'Creatures and Objects. A creature or object summoned or created by magic temporarily winks out of existence in the sphere. Such a creature instantly reappears once the space the creature occupied is no longer within the sphere.',
      "Dispel Magic. Spells and magical effects such as dispel magic have no effect on the sphere. Likewise, the spheres created by different antimagic field spells don't nullify each other.",
    ],
    upcastInfo: '',
  },

  {
    id: '452',
    name: 'Antipathy/Sympathy',
    slug: 'antipathy-sympathy',
    description:
      'This spell attracts or repels creatures of your choice. You target something within range, either a Huge or smaller object or creature or an area that is no larger than a 200-foot cube. Then specify a kind of intelligent creature, such as red dragons, goblins, or vampires. You invest the target with an aura that either attracts or repels the specified creatures for the duration. Choose antipathy or sympathy as the aura’s effect.\n\n',
    level: 8,
    school: 'ENCHANTMENT',
    castingTime: '1 hour',
    range: '60 feet',
    verbal: true,
    somatic: true,
    material: true,
    materialCost:
      '(either a lump of alum soaked in vinegar for the antipathy effect or a drop of honey for the sympathy effect)',
    duration: '10 days',
    source: "Player's Handbook",
    postTableData: '',
    extendedTable: [],
    options: [
      'Antipathy. The enchantment causes creatures of the kind you designated to feel an intense urge to leave the area and avoid the target. When such a creature can see the target or comes within 60 feet of it, the creature must succeed on a Wisdom saving throw or become frightened. The creature remains frightened while it can see the target or is within 60 feet of it. While frightened by the target, the creature must use its movement to move to the nearest safe spot from which it can’t see the target. If the creature moves more than 60 feet from the target and can’t see it, the creature is no longer frightened, but the creature becomes frightened again if it regains sight of the target or moves within 60 feet of it.',
      'Sympathy. The enchantment causes the specified creatures to feel an intense urge to approach the target while within 60 feet of it or able to see it. When such a creature can see the target or comes within 60 feet of it, the creature must succeed on a Wisdom saving throw or use its movement on each of its turns to enter the area or move within reach of the target. When the creature has done so, it can’t willingly move away from the target. If the target damages or otherwise harms an affected creature, the affected creature can make a Wisdom saving throw to end the effect, as described below.',
      'Ending the Effect. If an affected creature ends its turn while not within 60 feet of the target or able to see it, the creature makes a Wisdom saving throw. On a successful save, the creature is no longer affected by the target and recognizes the feeling of repugnance or attraction as magical. In addition, a creature affected by the spell is allowed another Wisdom saving throw every 24 hours while the spell persists. A creature that successfully saves against this effect is immune to it for 1 minute, after which time it can be affected again.',
    ],
    upcastInfo: '',
  },

  {
    id: '453',
    name: 'Clone',
    slug: 'clone',
    description:
      "This spell grows an inert duplicate of a living creature as a safeguard against death. This clone forms inside the vessel used in the spell's casting and grows to full size and maturity after 120 days; you can also choose to have the clone be a younger version of the same creature. It remains inert and endures indefinitely, as long as its vessel remains undisturbed.\n\nAt any time after the clone matures, if the original creature dies, its soul transfers to the clone, provided that the soul is free and willing to return. The clone is physically identical to the original and has the same personality, memories, and abilities, but none of the original’s equipment. The original creature’s physical remains, if they still exist, become inert and can’t thereafter be restored to life, since the creature’s soul is elsewhere.\n\n",
    level: 8,
    school: 'NECROMANCY',
    castingTime: '1 hour',
    range: 'Touch',
    verbal: true,
    somatic: true,
    material: true,
    materialCost:
      '(a diamond worth at least 1000 gp and at least 1 cubic inch of flesh of the creature that is to be cloned, which the spell consumes. A vessel worth at least 2000 gp that has a sealable lid and is large enough to hold the creature being cloned, such as a huge urn, coffin, mud-filled cyst in the ground, or crystal container filled with salt water)',
    duration: 'Instantaneous',
    source: "Player's Handbook",
  },

  {
    id: '454',
    name: 'Control Weather',
    slug: 'control-weather',
    description:
      'You take control of the weather within 5 miles of you for the duration. You must be outdoors to cast this spell. Moving to a place where you don’t have a clear path to the sky ends the spell early.\n\nWhen you cast the spell, you change the current weather conditions, which are determined by the DM based on the climate and season. You can change precipitation, temperature, and wind. It takes 1d4 x 10 minutes for the new conditions to take effect. Once they do so, you can change the conditions again. When the spell ends, the weather gradually returns to normal.\n\nWhen you change the weather conditions, find a current condition on the following tables and change its stage by one, up or down. When changing the wind, you can change its direction.\n\n',
    level: 8,
    school: 'TRANSMUTATION',
    castingTime: '10 minutes',
    range: 'Self (5-mile radius)',
    verbal: true,
    somatic: true,
    material: true,
    materialCost: '(burning incense and bits of earth and wood mixed in water)',
    duration: 'Concentration, Up to 8 hours',
    source: "Player's Handbook",
    extendedTable: [
      {
        '': {
          headers: ['Precipitation'],
          data: [
            { Precipitation: 'Stage 1' },
            { Precipitation: 'Stage 2' },
            { Precipitation: 'Stage 3' },
            { Precipitation: 'Stage 4' },
            { Precipitation: 'Stage 5' },
          ],
        },
      },
      {
        '': {
          headers: ['Temperature'],
          data: [
            { Temperature: 'Stage 1' },
            { Temperature: 'Stage 2' },
            { Temperature: 'Stage 3' },
            { Temperature: 'Stage 4' },
            { Temperature: 'Stage 5' },
            { Temperature: 'Stage 6' },
          ],
        },
      },
      {
        '': {
          headers: ['Wind'],
          data: [
            { Wind: 'Stage 1' },
            { Wind: 'Stage 2' },
            { Wind: 'Stage 3' },
            { Wind: 'Stage 4' },
            { Wind: 'Stage 5' },
          ],
        },
      },
    ],
  },
  {
    id: '456',
    name: 'Demiplane',
    slug: 'demiplane',
    description:
      'You create a shadowy door on a flat solid surface that you can see within range. The door is large enough to allow Medium creatures to pass through unhindered. When opened, the door leads to a demiplane that appears to be an empty room 30 feet in each dimension, made of wood or stone. When the spell ends, the door disappears, and any creatures or objects inside the demiplane remain trapped there, as the door also disappears from the other side.\n\nEach time you cast this spell, you can create a new demiplane, or have the shadowy door connect to a demiplane you created with a previous casting of this spell. Additionally, if you know the nature and contents of a demiplane created by a casting of this spell by another creature, you can have the shadowy door connect to its demiplane instead.\n\n',
    level: 8,
    school: 'CONJURATION',
    castingTime: '1 action',
    range: '60 feet',
    verbal: false,
    somatic: true,
    material: false,
    duration: '1 hour',
    source: "Player's Handbook",
  },
  {
    id: '457',
    name: 'Dominate Monster',
    slug: 'dominate-monster',
    description:
      'You attempt to beguile a creature that you can see within range. It must succeed on a Wisdom saving throw or be charmed by you for the duration. If you or creatures that are friendly to you are fighting it, it has advantage on the saving throw.\n\nWhile the creature is charmed, you have a telepathic link with it as long as the two of you are on the same plane of existence. You can use this telepathic link to issue commands to the creature while you are conscious (no action required), which it does its best to obey. You can specify a simple and general course of action, such as "Attack that creature," "Run over there," or "Fetch that object." If the creature completes the order and doesn’t receive further direction from you, it defends and preserves itself to the best of its ability.\n\nYou can use your action to take total and precise control of the target. Until the end of your next turn, the creature takes only the actions you choose, and doesn’t do anything that you don’t allow it to do. During this time, you can also cause the creature to use a reaction, but this requires you to use your own reaction as well.\n\nEach time the target takes damage, it makes a new Wisdom saving throw against the spell. If the saving throw succeeds, the spell ends.\n\n',
    level: 8,
    school: 'ENCHANTMENT',
    castingTime: '1 action',
    range: '60 feet',
    verbal: true,
    somatic: true,
    material: false,
    duration: 'Concentration, up to 1 hour',
    source: "Player's Handbook",
    upcastInfo:
      'When you cast this spell with a 9th-level spell slot, the duration is concentration, up to 8 hours.',
  },
  {
    id: '458',
    name: 'Feeblemind',
    slug: 'feeblemind',
    description:
      'You blast the mind of a creature that you can see within range, attempting to shatter its intellect and personality. The target takes 4d6 psychic damage and must make an Intelligence saving throw.\n\nOn a failed save, the creature’s Intelligence and Charisma scores become 1. The creature can’t cast spells, activate magic items, understand language, or communicate in any intelligible way. The creature can, however, identify its friends, follow them, and even protect them.\n\nAt the end of every 30 days, the creature can repeat its saving throw against this spell. If it succeeds on its saving throw, the spell ends. The spell can also be ended by Greater Restoration, Heal, or Wish.\n\n',
    level: 8,
    school: 'ENCHANTMENT',
    castingTime: '1 action',
    range: '150 feet',
    verbal: true,
    somatic: true,
    material: true,
    materialCost: '(a handful of clay, crystal, glass, or mineral spheres)',
    duration: 'Instantaneous',
    source: "Player's Handbook",
  },
  {
    id: '459',
    name: 'Glibness',
    slug: 'glibness',
    description:
      'Until the spell ends, when you make a Charisma check, you can replace the number you roll with a 15. Additionally, no matter what you say, magic that would determine if you are telling the truth indicates that you are being truthful.\n\n',
    level: 8,
    school: 'TRANSMUTATION',
    castingTime: '1 action',
    range: 'Self',
    verbal: true,
    somatic: false,
    material: false,
    duration: '1 hour',
    source: "Player's Handbook",
  },
  {
    id: '460',
    name: 'Holy Aura',
    slug: 'holy-aura',
    description:
      'Divine light washes out from you and coalesces in a soft radiance in a 30-foot radius around you. Creatures of your choice in that radius when you cast this spell shed dim light in a 5-foot radius and have advantage on all saving throws, and other creatures have disadvantage on attack rolls against them until the spell ends. In addition, when a fiend or an undead hits an affected creature with a melee attack, the aura flashes with brilliant light. The attacker must succeed on a Constitution saving throw or be blinded until the spell ends.\n\n',
    level: 8,
    school: 'ABJURATION',
    castingTime: '1 action',
    range: 'Self',
    verbal: true,
    somatic: true,
    material: true,
    materialCost:
      '(a tiny reliquary worth at least 1,000 gp containing a sacred relic, such as a scrap of cloth from a saint’s robe or a piece of parchment from a religious text)',
    duration: 'Concentration, up to 1 minute',
    source: "Player's Handbook",
  },
  {
    id: '462',
    name: 'Incendiary Cloud',
    slug: 'incendiary-cloud',
    description:
      'A swirling cloud of smoke shot through with white-hot embers appears in a 20-foot-radius sphere centered on a point within range. The cloud spreads around corners and is heavily obscured. It lasts for the duration or until a wind of moderate or greater speed (at least 10 miles per hour) disperses it.\n\nWhen the cloud appears, each creature in it must make a Dexterity saving throw. A creature takes 10d8 fire damage on a failed save, or half as much damage on a successful one. A creature must also make this saving throw when it enters the spell’s area for the first time on a turn or ends its turn there.\n\nThe cloud moves 10 feet directly away from you in a direction that you choose at the start of each of your turns.\n\n',
    level: 8,
    school: 'CONJURATION',
    castingTime: '1 action',
    range: '150 feet',
    verbal: true,
    somatic: true,
    material: false,
    duration: 'Concentration, up to 1 minute',
    source: "Player's Handbook",
  },
  {
    id: '464',
    name: 'Maze',
    slug: 'maze',
    description:
      'You banish a creature that you can see within range into a labyrinthine demiplane. The target remains there for the duration or until it escapes the maze.\n\nThe target can use its action to attempt to escape. When it does so, it makes a DC 20 Intelligence check. If it succeeds, it escapes, and the spell ends (a minotaur or goristro demon automatically succeeds).\n\nWhen the spell ends, the target reappears in the space it left or, if that space is occupied, in the nearest unoccupied space.\n\n',
    level: 8,
    school: 'CONJURATION',
    castingTime: '1 action',
    range: '60 feet',
    verbal: true,
    somatic: true,
    material: false,
    duration: 'Concentration, up to 10 minutes',
    source: "Player's Handbook",
  },
  {
    id: '466',
    name: 'Mind Blank',
    slug: 'mind-blank',
    description:
      "Until the spell ends, one willing creature you touch is immune to psychic damage, any effect that would sense its emotions or read its thoughts, divination spells, and the charmed condition. The spell even foils wish spells and spells or effects of similar power used to affect the target's mind or to gain information about the target.",
    level: 8,
    school: 'ABJURATION',
    castingTime: '1 action',
    range: 'Touch',
    verbal: true,
    somatic: true,
    material: false,
    duration: '24 hours',
    source: "Player's Handbook",
  },
  {
    id: '468',
    name: 'Sunburst',
    slug: 'sunburst',
    description:
      'Brilliant sunlight flashes in a 60-foot radius centered on a point you choose within range. Each creature in that light must make a Constitution saving throw. On a failed save, a creature takes 12d6 radiant damage and is blinded for 1 minute. On a successful save, it takes half as much damage and isn’t blinded by this spell. Undead and oozes have disadvantage on this saving throw.\n\nA creature blinded by this spell makes another Constitution saving throw at the end of each of its turns. On a successful save, it is no longer blinded.\n\nThis spell dispels any darkness in its area that was created by a spell.\n\n',
    level: 8,
    school: 'EVOCATION',
    castingTime: '1 action',
    range: '150 feet',
    verbal: true,
    somatic: true,
    material: true,
    materialCost: '(fire and a piece of sunstone)',
    duration: 'Instantaneous',
    source: "Player's Handbook",
  },
];

export default SpellEighthLevelSeed;
