import { init } from "next/dist/compiled/webpack/webpack";

export const backgroundIds = {
  acolyte: 1,
  anthropologist: 2,
  archaeologist: 3,
  athlete: 4,
  charlatan: 5,
  cityWatch: 6,
  clanCrafter: 7,
  cloisteredScholar: 8,
  courtier: 9,
  criminal: 10,
  entertainer: 11,
  faceless: 12,
  factionAgent: 13,
  farTraveler: 14,
  feyLost: 15,
  fisher: 16,
  folkHero: 17,
  giantFoundling: 18,
  gladiator: 19,
  guildArtisan: 20,
  guildMerchant: 21,
  hauntedOne: 22,
  hermit: 23,
  houseAgent: 24,
  inheritor: 25,
  investigatorSCAG: 26,
  investigatorVRGR: 27,
  knight: 28,
  knightOfTheOrder: 29,
  marine: 30,
  mercenaryVeteran: 31,
  noble: 32,
  outlander: 33,
  pirate: 34,
  rewarded: 35,
  ruined: 36,
  runeCarver: 37,
  sage: 38,
  sailor: 39,
  shipwright: 40,
  smuggler: 41,
  soldier: 42,
  spy: 43,
  urbanBountyHunter: 44,
  urchin: 45,
  uthgardtTribeMember: 46,
  waterdhavianNoble: 47,
  witchlightHand: 48,
  //aquisitionsInc
  celebrityAdventurer: 49,
  failedMerchant: 50,
  gambler: 51,
  plaintiff: 52,
  rivalIntern: 53,
  //curse of strahd
  blackFistDoubleAgent: 54,
  dragonCasualty: 55,
  ironRogueBandit: 56,
  phlanInsurgent: 57,
  stojanowPrisoner: 58,
  ticklebellyNomad: 59,
  //Mulmaster
  caravanSpecialist: 60,
  earthspurMiner: 61,
  harborfolk: 62,
  mulmasterAristocrat: 63,
  phlanRefugee: 64,
  //hillsfar
  cormanthorRefugee: 65,
  gateUrchin: 66,
  hillsfarMerchant: 67,
  hillsfarSmuggler: 68,
  secretIdentity: 69,
  shadeFanatic: 70,
  tradeSheriff: 71,
  //amonkhet
  dissenter: 72,
  initiate: 73,
  vizier: 74,
  //dragonlance
  knightOfSolamnia: 75,
  mageOfHighSorcery: 76,
};
