import { languages } from "@/lib/globalVars";
import { src } from "@/lib/types";
import { Language, Prisma, Skill } from "@prisma/client";

const Backgrounds: Prisma.BackgroundCreateManyInput[] = [
  {
    id: 1,
    name: "Acolyte",
    flavorText:
      "You have spent your life in the service of a temple to a specific god or pantheon of gods.",
    description:
      "You have spent your life in the service of a temple to a specific god or pantheon of gods. You act as an intermediary between the realm of the holy and the mortal world, performing sacred rites and offering sacrifices in order to conduct worshipers into the presence of the divine. You are not necessarily a cleric – performing sacred rites is not the same thing as channeling divine power.\n\nChoose a god, a pantheon of gods, or some other quasi-divine being, and work with your DM to detail the nature of your religious service. Were you a lesser functionary in a temple, raised from childhood to assist the priests in the sacred rites? Or were you a high priest who suddenly experienced a call to serve your god in a different way? Perhaps you were the leader of a small cult outside of any established temple structure, or even an occult group that served a fiendish master that you now deny.",
    source: src.phb,
    skillProficiencies: [Skill.INSIGHT, Skill.RELIGION],
    skillChoiceCount: 2,
    languages: languages,
    languageChoiceCount: 2,
    equipment: [
      "A holy symbol (a gift to you when you entered the priesthood)",
      "A prayer book or prayer wheel",
      "5 sticks of incense",
      "Vestments",
      "A set of common clothes",
      "A pouch containing 15 gp",
    ],
  },
  {
    id: 2,
    name: "Anthropologist",
    flavorText: "You have always been fascinated by other cultures.",
    description:
      "You have always been fascinated by other cultures, from the most ancient and primeval lost lands to the most modern civilizations. By studying other cultures' customs, philosophies, laws, rituals, religious beliefs, languages, and art, you have learned how tribes, empires, and all forms of society in between craft their own destinies and doom. This knowledge came to you not only through books and scrolls, but also through firsthand observation – by visiting far-flung settlements and exploring local histories and customs.",
    source: src.tomb,
    skillProficiencies: [Skill.INSIGHT, Skill.RELIGION],
    skillChoiceCount: 2,
    languages: languages,
    languageChoiceCount: 2,
    equipment: [
      "A leather-bound diary with notes on one of the cultures you have studied",
      "A bottle of ink",
      "An ink pen",
      "A set of traveler's clothes",
      "A pouch containing 10 gp",
    ],
  },
  {
    id: 3,
    name: "Archeologist",
    flavorText: "You love to dig in the dirt and uncover relics of the past.",
    description:
      "An archaeologist learns about the long-lost and fallen cultures of the past by studying their remains – their bones, their ruins, their surviving masterworks, and their tombs. Those who practice archaeology travel to the far corners of the world to root through crumbled cities and lost dungeons, digging in search of artifacts that might tell the stories of monarchs and high priests, wars and cataclysms.",
    source: src.tomb,
    skillProficiencies: [Skill.HISTORY, Skill.SURVIVAL],
    skillChoiceCount: 2,
    languages: languages,
    languageChoiceCount: 1,
    toolProficiencies: ["Cartographer's tools or navigator's tools"],
    equipment: [
      "A wooden case containing a map to a ruin or dungeon",
      "A bullseye lantern",
      "A miner's pick",
      "A set of traveler's clothes",
      "A two-person tent",
      "A trinket recovered from a dig site",
      "A pouch containing 25 gp",
    ],
  },
  {
    id: 4,
    name: "Athlete",
    flavorText:
      "You strive to perfect yourself physically and in execution of everything you do.",
    description:
      "You strive to perfect yourself physically and in execution of everything you do. The thrill of competition lights fire in your blood, and the roar of the crowd drives you forward. Tales of your exploits precede you and might open doors or loosen tongues.\n\nWhether in one of the poleis, between them, or among the nonhuman peoples of Theros, physical contests and those who pursue them command respect bordering on reverence. Athletes arise from all walks of life and all cultures and quite often cross paths with one another.",
    source: src.theros,
    skillProficiencies: [Skill.ACROBATICS, Skill.ATHLETICS],
    skillChoiceCount: 2,
    languages: languages,
    languageChoiceCount: 1,
    toolProficiencies: ["Vehicles (land)"],
    equipment: [
      "A bronze discus or leather ball",
      "A lucky charm or past trophy",
      "A set of traveler's clothes",
      "A pouch containing 10 gp",
    ],
  },
  {
    id: 5,
    name: "Charlatan",
    flavorText:
      "You have always had a way with people. You know what makes them tick, you can tease out their hearts' desires after a few minutes of conversation.",
    description:
      "You have always had a way with people. You know what makes them tick, you can tease out their hearts' desires after a few minutes of conversation, and with a few leading questions you can read them like they were children's books. It's a useful talent, and one that you're perfectly willing to use for your advantage.\n\nYou know what people want and you deliver, or rather, you promise to deliver. Common sense should steer people away from things that sound too good to be true, but common sense seems to be in short supply when you're around. The bottle of pink colored liquid will surely cure that unseemly rash, this ointment – nothing more than a bit of fat with a sprinkle of silver dust can restore youth and vigor, and there's a bridge in the city that just happens to be for sale. These marvels sound implausible, but you make them sound like the real deal.",
    source: src.phb,
    skillProficiencies: [Skill.DECEPTION, Skill.SLEIGHT_OF_HAND],
    skillChoiceCount: 2,
    languages: [],
    languageChoiceCount: 0,
    toolProficiencies: ["Disguise kit", "Forgery kit"],
    equipment: [
      "A set of fine clothes",
      "A disguise kit",
      "Tools of the con of your choice (ten stoppered bottles filled with colored liquid, a set of weighted dice, a deck of marked cards, or a signet ring of an imaginary duke)",
      "A pouch containing 15 gp",
    ],
  },
  {
    id: 6,
    name: "City Watch",
    flavorText: "You have served the community where you grew up.",
    description:
      "You have served the community where you grew up, standing as its first line of defense against crime. You aren't a soldier, directing your gaze outward at possible enemies. Instead, your service to your hometown was to help police its populace, protecting the citizenry from lawbreakers and malefactors of every stripe.\n\nYou might have been part of the City Watch of Waterdeep, the baton-wielding police force of the City of Splendors, protecting the common folk from thieves and rowdy nobility alike. Or you might have been one of the valiant defenders of Silverymoon, a member of the Silverwatch or even one of the magic-wielding Spellguard.\n\nPerhaps you hail from Neverwinter and have served as one of its Wintershield watchmen, the newly founded branch of guards who vow to keep safe the City of Skilled Hands.\n\nEven if you're not city-born or city-bred, this background can describe your early years as a member of law enforcement. Most settlements of any size have their own constables and police forces, and even smaller communities have sheriffs and bailiffs who stand ready to protect their community.",
    source: src.sword,
    skillProficiencies: [Skill.ATHLETICS, Skill.PERCEPTION],
    skillChoiceCount: 2,
    languages: languages,
    languageChoiceCount: 2,
    equipment: [
      "A uniform in the style of your unit and indicative of your rank",
      "A horn with which to summon help",
      "A set of manacles",
      "A pouch containing 10 gp",
    ],
  },
  {
    id: 7,
    name: "Clan Crafter",
    flavorText: "You are a member of a dwarven clan of crafters.",
    description:
      "The Stout Folk are well known for their artisanship and the worth of their handiworks, and you have been trained in that ancient tradition. For years you labored under a dwarf master of the craft, enduring long hours and dismissive, sour-tempered treatment in order to gain the fine skills you possess today.\n\nYou are most likely a dwarf, but not necessarily- particularly in the North, the shield dwarf clans learned long ago that only proud fools who are more concerned for their egos than their craft turn away promising apprentices, even those of other races. If you aren't a dwarf, however, you have taken a solemn oath never to take on an apprentice in the craft: it is not for non-dwarves to pass on the skills of Moradin's favored children. You would have no difficulty, however, finding a dwarf master who was willing to receive potential apprentices who came with your recommendation.",
    source: src.sword,
    skillProficiencies: [Skill.HISTORY, Skill.INSIGHT],
    skillChoiceCount: 2,
    languages: [Language.DWARVISH],
    languageChoiceCount: 1,
    toolProficiencies: ["Artisan's tools (one of your choice)"],
    equipment: [
      "A set of artisan's tools with which you are proficient",
      "A maker's mark chisel used to mark your handiwork with the symbol of the clan of crafters you learned your skill from",
      "A set of traveler's clothes",
      "A pouch containing 5 gp and a gem worth 10 gp",
    ],
  },
  {
    id: 8,
    name: "Cloistered Scholar",
    flavorText: "You have worked in a library or scriptorium.",
    description:
      "As a child, you were inquisitive when your playmates were possessive or raucous. In your formative years, you found your way to one of Faerûn's great institutes of learning, where you were apprenticed and taught that knowledge is a more valuable treasure than gold or gems. Now you are ready to leave your home – not to abandon it, but to quest for new lore to add to its storehouse of knowledge.\n\nThe most well-known of Faerûn's fonts of knowledge is Candlekeep. The great library is always in need of workers and attendants, some of whom rise through the ranks to assume roles of greater responsibility and prominence. You might be one of Candlekeep's own, dedicated to the curatorship of what is likely the most complete body of lore and history in all the world.\n\nPerhaps instead you were taken in by the scholars of the Vault of the Sages or the Map House in Silverymoon, and now you have struck out to increase your knowledge and to make yourself available to help those in other places who seek your expertise. You might be one of the few who aid Herald's Holdfast, helping to catalogue and maintain records of the information that arrives daily from across Faerûn.",
    source: src.sword,
    skillProficiencies: [
      Skill.HISTORY,
      Skill.RELIGION,
      Skill.ARCANA,
      Skill.NATURE,
    ],
    skillChoiceCount: 2,
    languages: languages,
    languageChoiceCount: 2,
    equipment: [
      "The scholar's robes of your cloister",
      "A writing kit (small pouch with a quill, ink, folded parchment, and a small penknife)",
      "A borrowed book on the subject of your current study",
      "A pouch containing 10 gp",
    ],
  },
  {
    id: 9,
    name: "Courtier",
    flavorText: "You are a personage of some significance in a noble court.",
    description:
      "In your earlier days, you were a personage of some significance in a noble court or a bureaucratic organization. You might or might not come from an upper-class family; your talents, rather than the circumstances of your birth, could have secured you this position.\n\nYou might have been one of the many functionaries, attendants, and other hangers-on in the Court of Silverymoon, or perhaps you traveled in Waterdeep's baroque and sometimes cutthroat conglomeration of guilds, nobles, adventurers, and secret societies. You might have been one of the behind-the-scenes law-keepers or functionaries in Baldur's Gate or Neverwinter, or you might have grown up in and around the castle of Daggerford.\n\nEven if you are no longer a full-fledged member of the group that gave you your start in life, your relationships with your former fellows can be an advantage for you and your adventuring comrades. You might undertake missions with your new companions that further the interest of the organization that gave you your start in life. In any event, the abilities that you honed while serving as a courtier will stand you in good stead as an adventurer.",
    source: src.sword,
    skillProficiencies: [Skill.PERSUASION, Skill.INSIGHT],
    skillChoiceCount: 2,
    languages: languages,
    languageChoiceCount: 2,
    equipment: ["A set of fine clothes", "A pouch containing 5 gp"],
  },
  {
    id: 10,
    name: "Criminal",
    flavorText: "You have a history of breaking the law.",
    description:
      "You are an experienced criminal with a history of breaking the law. You have spent a lot of time among other criminals and still have contacts within the criminal underworld. You're far closer than most people to the world of murder, theft, and violence that pervades the underbelly of civilization, and you have survived up to this point by flouting the rules and regulations of society.",
    source: src.phb,
    skillProficiencies: [Skill.DECEPTION, Skill.STEALTH],
    skillChoiceCount: 2,
    toolProficiencies: ["One type of gaming set", "Theives tools"],
    languages: [],
    equipment: [
      "A crowbar",
      "A set of dark common clothes including a hood",
      "A pouch containing 15 gp",
    ],
    languageChoiceCount: 0,
  },
  {
    id: 11,
    name: "Entertainer",
    flavorText:
      "You thrive in front of an audience. You know how to entrance them, entertain them, and even inspire them.",
    description:
      "You thrive in front of an audience. You know how to entrance them, entertain them, and even inspire them. Your poetics can stir the hearts of those who hear you, awakening grief or joy, laughter or anger. Your music raises their spirits or captures their sorrow. Your dance steps captivate, your humor cuts to the quick. Whatever techniques you use, your art is your life.",
    source: src.phb,
    toolProficiencies: ["Disguise kit", "One type of musical instrument"],
    skillProficiencies: [Skill.ACROBATICS, Skill.PERFORMANCE],
    skillChoiceCount: 2,
    languages: [],
    languageChoiceCount: 0,
    equipment: [
      "A musical instrument (one of your choice)",
      "The favor of an admirer (love letter, lock of hair, or trinket)",
      "A costume",
      "A pouch containing 15 gp",
    ],
  },
  {
    id: 12,
    name: "Faceless",
    flavorText: "You are a hero behind a mask.",
    description:
      "Being who you are, you could never be a hero. Whether due to your class, your people, your family, or your sins, something about you prevents you from effectively pursuing the path you've chosen. Even so, that doesn't stop you. You've left your old face behind, taking on a new persona, becoming something more.\n\nCharacters with the faceless background don a disguise—literally or otherwise—as they adventure. This persona might be dramatic or subtle. In a way, though, many characters have such larger than life personalities. Therefore, this background largely focuses on detailing the hero behind the mask.",
    source: src.descent,

    skillProficiencies: [Skill.DECEPTION, Skill.STEALTH],
    skillChoiceCount: 2,
    toolProficiencies: ["Disguise kit"],
    languages: languages,
    languageChoiceCount: 1,
    equipment: [
      "A disguise kit",
      "A set of common clothes",
      "A pouch containing 10 gp",
    ],
  },
  {
    id: 13,
    name: "Faction Agent",
    flavorText: "You are a member of a faction.",
    description:
      "Many organizations active in the North and across the face of Faerûn aren't bound by strictures of geography. These factions pursue their agendas without regard for political boundaries, and their members operate anywhere the organization deems necessary. These groups employ listeners, rumormongers, smugglers, sellswords, cache-holders (people who guard caches of wealth or magic for use by the faction's operatives), haven keepers, and message drop minders, to name a few. At the core of every faction are those who don't merely fulfill a small function for that organization, but who serve as its hands, head, and heart.\n\nAs a prelude to your adventuring career (and in preparation for it), you served as an agent of a particular faction in Faerûn. You might have operated openly or secretly, depending on the faction and its goals, as well as how those goals mesh with your own. Becoming an adventurer doesn't necessarily require you to relinquish membership in your faction (though you can choose to do so), and it might enhance your status in the faction.",
    source: src.sword,
    skillProficiencies: [
      Skill.INSIGHT,
      Skill.PERCEPTION,
      Skill.PERFORMANCE,
      Skill.PERSUASION,
      Skill.DECEPTION,
      Skill.MEDICINE,
      Skill.INVESTIGATION,
      Skill.ARCANA,
      Skill.RELIGION,
      Skill.HISTORY,
      Skill.NATURE,
      Skill.SURVIVAL,
      Skill.ANIMAL_HANDLING,
      Skill.INTIMIDATION,
    ],
    skillChoiceCount: 2,
    languages: languages,
    languageChoiceCount: 2,
    equipment: [
      "A badge or emblem of your faction",
      "A copy of a seminal faction text",
      "A set of common clothes",
      "A pouch containing 15 gp",
    ],
  },
  {
    id: 14,
    name: "Far Traveler",
    flavorText: "You are from a distant place.",
    description:
      "Almost all of the common people and other folk that one might encounter along the Sword Coast or in the North have one thing in common: they live out their lives without ever traveling more than a few miles from where they were born.\n\nYou aren't one of those folk.\n\nYou are from a distant place, one so remote that few of the common folk in the North realize that it exists, and chances are good that even if some people you meet have heard of your homeland, they know merely the name and perhaps a few outrageous stories. You have come to this part of Faerûn for your own reasons, which you might or might not choose to share.\n\nAlthough you will undoubtedly find some of this land's ways to be strange and discomfiting, you can also be sure that some things its people take for granted will be to you new wonders that you've never laid eyes on before. By the same token, you're a person of interest, for good or ill, to those around you almost anywhere you go.",
    source: src.sword,
    skillProficiencies: [Skill.INSIGHT, Skill.PERCEPTION],
    toolProficiencies: ["One musical instrument or gaming set of your choice"],
    skillChoiceCount: 2,
    languages: languages,
    languageChoiceCount: 1,
    equipment: [
      "A set of traveler's clothes",
      "Any one musical instrument or gaming set you are proficient with",
      "Poorly wrought maps from your homeland that depict where you are in Faerûn",
      "A small piece of jewelry worth 10gp in the style of your homeland's craftsmanship",
      "A pouch containing 5 gp",
    ],
  },
  {
    id: 15,
    name: "Feylost",
    flavorText:
      "You grew up in the Feywild after disappearing from your home plane as a child.",
    description:
      "You grew up in the Feywild after disappearing from your home plane as a child. Perhaps you were spirited away by kindly Fey who thought you were destined for great things. Perhaps you stumbled through a Fey crossing by chance during a twilight stroll in the woods. Perhaps you were kidnapped by evil Fey but escaped from their clutches. Whatever the manner of your disappearance, you gradually fell under the Feywild's spell and learned a little about the nature of the mercurial tricksters that dwell there.\n\nWhen you finally returned to your home plane, you did not come back unchanged. You are haunted by the fact the Feywild-a mirror world hidden behind a mere twist of perception-is only a hair's breadth away. Although your memories of the Feywild grow fainter with each passing day, your heart swells with a mixture of fear and joy at the prospect of one day venturing back to the Plane of Faerie-your home away from home.",
    source: src.witchlight,
    skillProficiencies: [Skill.DECEPTION, Skill.SURVIVAL],
    skillChoiceCount: 2,
    languages: [
      Language.ELVISH,
      Language.SYLVAN,
      Language.GNOMISH,
      Language.GOBLIN,
    ],
    languageChoiceCount: 1,
    equipment: [
      "A musical instrument (one of your choice)",
      "A set of traveler's clothes",
      "Three trinkets (each determind by rolling on the Feywild Trinkets table)",
      "A pouch containing 8 gp",
    ],
  },
];

export default Backgrounds;
