import { Ability, ArmorTypes, Class, Prisma, Skill } from "@prisma/client";

const Classes: Prisma.ClassCreateManyInput[] = [
  {
    name: "Fighter",
    hitDie: 10,
    savingThrows: [Ability.STR, Ability.CON],
    skills: [
      Skill.ACROBATICS,
      Skill.ANIMAL_HANDLING,
      Skill.ATHLETICS,
      Skill.HISTORY,
      Skill.INSIGHT,
      Skill.INTIMIDATION,
      Skill.PERCEPTION,
      Skill.SURVIVAL,
    ],
    skillChoiceCount: 2,
    weapons: ["Simple", "Martial"],
    armor: [
      ArmorTypes.LIGHT,
      ArmorTypes.MEDIUM,
      ArmorTypes.HEAVY,
      ArmorTypes.SHIELDS,
    ],
    tools: [],
    equipment: [
      "Chain Mail or leather armor, longbow, and 20 arrows",
      "A martial weapon and a shield or two martial weapons",
      "A light crossbow and 20 bolts or two handaxes",
      "A dungeoneer's pack or an explorer's pack",
    ],
    ASILevels: [4, 6, 8, 12, 14, 16, 19],
    subClassName: "Martial Archetype",
    subClassDesc:
      "you choose an archetype that you strive to emulate in your combat styles and techniques. ",
    subfeatLevels: [3, 7, 10, 15, 18],
  },

  {
    name: "Wizard",
    hitDie: 6,
    savingThrows: [Ability.INT, Ability.WIS],
    skills: [
      Skill.ARCANA,
      Skill.HISTORY,
      Skill.INSIGHT,
      Skill.INVESTIGATION,
      Skill.MEDICINE,
      Skill.RELIGION,
    ],
    skillChoiceCount: 2,
    weapons: ["Daggers", "Darts", "Slings", "Quarterstaffs", "Light Crossbows"],
    armor: [],
    tools: [],
    equipment: [
      "A quarterstaff or a dagger",
      "A component pouch or an arcane focus",
      "A scholar's pack or an explorer's pack",
      "A spellbook",
    ],
    ASILevels: [4, 8, 12, 16, 19],
    subClassName: "Arcane Tradition",
    subClassDesc: "you choose an arcane tradition that you specialize in. ",
    subfeatLevels: [2, 6, 10, 14],
  },
  {
    name: "Cleric",
    hitDie: 8,
    savingThrows: [Ability.WIS, Ability.CHA],
    skills: [
      Skill.HISTORY,
      Skill.INSIGHT,
      Skill.MEDICINE,
      Skill.PERSUASION,
      Skill.RELIGION,
    ],
    skillChoiceCount: 2,
    weapons: ["All Simple Weapons"],
    armor: [ArmorTypes.LIGHT, ArmorTypes.MEDIUM, ArmorTypes.SHIELDS],
    tools: [],
    equipment: [
      "A mace or a warhammer",
      "Scale mail, chain mail, or leather armor",
      "A light crossbow and 20 bolts or any simple weapon",
      "A priest's pack or an explorer's pack",
      "A shield and a holy symbol",
    ],
    ASILevels: [4, 8, 12, 16, 19],
    subClassName: "Divine Domain",
    subClassDesc: "you choose a divine domain that you dedicate yourself to. ",
    subfeatLevels: [1, 2, 6, 8, 17],
  },
  {
    name: "Rogue",
    hitDie: 8,
    savingThrows: [Ability.DEX, Ability.INT],
    skills: [
      Skill.ACROBATICS,
      Skill.ATHLETICS,
      Skill.DECEPTION,
      Skill.INSIGHT,
      Skill.INTIMIDATION,
      Skill.INVESTIGATION,
      Skill.PERCEPTION,
      Skill.PERFORMANCE,
      Skill.PERSUASION,
      Skill.SLEIGHT_OF_HAND,
      Skill.STEALTH,
    ],
    skillChoiceCount: 4,
    weapons: [
      "Simple",
      "Hand Crossbows",
      "Longswords",
      "Rapiers",
      "Shortswords",
    ],
    armor: [ArmorTypes.LIGHT],
    tools: [],
    equipment: [
      "A rapier or a shortsword",
      "A shortbow and a quiver of 20 arrows or a shortsword",
      "A burglar's pack, a dungeoneer's pack, or an explorer's pack",
      "Leather armor, two daggers, and thieves' tools",
    ],
    ASILevels: [4, 8, 10, 12, 16, 19],
    subClassName: "Roguish Archetype",
    subClassDesc:
      "you choose a roguish archetype that you emulate in your adventuring career. ",
  },
  {
    name: "Barbarian",
    hitDie: 12,
    savingThrows: [Ability.STR, Ability.CON],
    skills: [
      Skill.ANIMAL_HANDLING,
      Skill.ATHLETICS,
      Skill.INTIMIDATION,
      Skill.NATURE,
      Skill.PERCEPTION,
      Skill.SURVIVAL,
    ],
    skillChoiceCount: 2,
    weapons: ["Simple", "Martial"],
    armor: [ArmorTypes.LIGHT, ArmorTypes.MEDIUM, ArmorTypes.SHIELDS],
    tools: [],
    equipment: [
      "A greataxe or any martial melee weapon",
      "Two handaxes or any simple weapon",
      "An explorer's pack or a dungeoneer's pack",
      "Four javelins",
    ],
    ASILevels: [4, 6, 8, 12, 14, 16, 19],
    subClassName: "Primal Path",
    subClassDesc: "you choose a path that shapes the nature of your rage. ",
    subfeatLevels: [3, 6, 10, 14],
  },
  {
    name: "Bard",
    hitDie: 8,
    savingThrows: [Ability.DEX, Ability.CHA],
    skills: [
      Skill.ACROBATICS,
      Skill.ANIMAL_HANDLING,
      Skill.ARCANA,
      Skill.ATHLETICS,
      Skill.DECEPTION,
      Skill.HISTORY,
      Skill.INSIGHT,
      Skill.INTIMIDATION,
      Skill.INVESTIGATION,
      Skill.MEDICINE,
      Skill.NATURE,
      Skill.PERCEPTION,
      Skill.PERFORMANCE,
      Skill.PERSUASION,
      Skill.RELIGION,
      Skill.SLEIGHT_OF_HAND,
      Skill.STEALTH,
      Skill.SURVIVAL,
    ],
    skillChoiceCount: 3,
    weapons: [
      "Simple",
      "Hand Crossbows",
      "Longswords",
      "Rapiers",
      "Shortswords",
    ],
    armor: [ArmorTypes.LIGHT],
    tools: ["Three musical instruments of your choice"],
    equipment: [
      "A rapier, a longsword, or any simple weapon",
      "A diplomat's pack or an entertainer's pack",
      "A lute or any other musical instrument",
      "Leather armor and a dagger",
    ],
    ASILevels: [4, 8, 12, 16, 19],
    subfeatLevels: [3, 6, 14],
    subClassName: "Bardic College",
    subClassDesc: "you choose a college that you dedicate yourself to. ",
  },
  {
    name: "Druid",
    hitDie: 8,
    savingThrows: [Ability.INT, Ability.WIS],
    skills: [
      Skill.ARCANA,
      Skill.ANIMAL_HANDLING,
      Skill.INSIGHT,
      Skill.MEDICINE,
      Skill.NATURE,
      Skill.PERCEPTION,
      Skill.RELIGION,
      Skill.SURVIVAL,
    ],
    skillChoiceCount: 2,
    weapons: [
      "Clubs",
      "Daggers",
      "Darts",
      "Javelins",
      "Maces",
      "Quarterstaffs",
      "Scimitars",
      "Sickles",
      "Slings",
      "Spears",
    ],
    armor: [ArmorTypes.LIGHT, ArmorTypes.MEDIUM, ArmorTypes.SHIELDS],
    tools: ["Herbalism Kit"],
    equipment: [
      "A wooden shield or any simple weapon",
      "A scimitar or any simple melee weapon",
      "Leather armor, an explorer's pack, and a druidic focus",
    ],
    ASILevels: [4, 8, 12, 16, 19],
    subClassName: "Druidic Circle",
    subClassDesc: "you choose a circle that you dedicate yourself to. ",
    subfeatLevels: [2, 6, 10, 14],
  },
  {
    name: "Monk",
    hitDie: 8,
    savingThrows: [Ability.STR, Ability.DEX],
    skills: [
      Skill.ACROBATICS,
      Skill.ATHLETICS,
      Skill.HISTORY,
      Skill.INSIGHT,
      Skill.RELIGION,
      Skill.STEALTH,
    ],
    skillChoiceCount: 2,
    weapons: ["Simple", "Shortswords"],
    armor: [],
    tools: ["Choose one type of artisan's tools or one musical instrument"],
    equipment: [
      "A shortsword or any simple weapon",
      "A dungeoneer's pack or an explorer's pack",
      "10 darts",
    ],
    ASILevels: [4, 6, 8, 10, 12, 14, 16, 19],
    subClassName: "Monastic Tradition",
    subClassDesc:
      "you choose a monastic tradition that you dedicate yourself to. ",
    subfeatLevels: [3, 6, 11, 17],
  },
  {
    name: "Paladin",
    hitDie: 10,
    savingThrows: [Ability.WIS, Ability.CHA],
    skills: [
      Skill.ATHLETICS,
      Skill.INSIGHT,
      Skill.INTIMIDATION,
      Skill.MEDICINE,
      Skill.PERSUASION,
      Skill.RELIGION,
    ],
    skillChoiceCount: 2,
    weapons: ["Simple", "Martial"],
    armor: [
      ArmorTypes.LIGHT,
      ArmorTypes.MEDIUM,
      ArmorTypes.HEAVY,
      ArmorTypes.SHIELDS,
    ],
    tools: [],
    equipment: [
      "A martial weapon and a shield or two martial weapons",
      "Five javelins or any simple melee weapon",
      "Chain mail or leather armor, a longbow, and 20 arrows",
      "A priest's pack or an explorer's pack",
      "A holy symbol",
    ],
    ASILevels: [4, 8, 12, 16, 19],
    subClassName: "Sacred Oath",
    subClassDesc: "you choose a sacred oath that you dedicate yourself to. ",
    subfeatLevels: [3, 7, 15, 20],
  },
  {
    name: "Ranger",
    hitDie: 10,
    savingThrows: [Ability.STR, Ability.DEX],
    skills: [
      Skill.ANIMAL_HANDLING,
      Skill.ATHLETICS,
      Skill.INSIGHT,
      Skill.INVESTIGATION,
      Skill.NATURE,
      Skill.PERCEPTION,
      Skill.STEALTH,
      Skill.SURVIVAL,
    ],
    skillChoiceCount: 3,
    weapons: ["Simple", "Martial"],
    armor: [ArmorTypes.LIGHT, ArmorTypes.MEDIUM, ArmorTypes.SHIELDS],
    tools: [],
    equipment: [
      "Scale mail or leather armor",
      "Two shortswords or two simple melee weapons",
      "A dungeoneer's pack or an explorer's pack",
      "A longbow and a quiver of 20 arrows",
    ],
    ASILevels: [4, 8, 12, 16, 19],
    subClassName: "Ranger Conclave",
    subClassDesc:
      "you choose to emulate the ideals and training of a ranger conclave.",
    subfeatLevels: [3, 7, 11, 15, 18],
  },
  {
    name: "Sorcerer",
    hitDie: 6,
    savingThrows: [Ability.CON, Ability.CHA],
    skills: [
      Skill.ARCANA,
      Skill.DECEPTION,
      Skill.INSIGHT,
      Skill.INTIMIDATION,
      Skill.PERSUASION,
      Skill.RELIGION,
    ],
    skillChoiceCount: 2,
    weapons: ["Daggers", "Darts", "Slings", "Quarterstaffs", "Light Crossbows"],
    armor: [],
    tools: [],
    equipment: [
      "A light crossbow and 20 bolts or any simple weapon",
      "A component pouch or an arcane focus",
      "A dungeoneer's pack or an explorer's pack",
      "Two daggers",
    ],
    ASILevels: [4, 8, 12, 16, 19],
    subClassName: "Sorcerous Origin",
    subClassDesc:
      "you choose a sorcerous origin that you dedicate yourself to. ",
    subfeatLevels: [1, 6, 14, 18],
  },
  {
    name: "Warlock",
    hitDie: 8,
    savingThrows: [Ability.WIS, Ability.CHA],
    skills: [
      Skill.ARCANA,
      Skill.DECEPTION,
      Skill.HISTORY,
      Skill.INTIMIDATION,
      Skill.INVESTIGATION,
      Skill.NATURE,
      Skill.RELIGION,
    ],
    skillChoiceCount: 2,
    weapons: ["Simple"],
    armor: [],
    tools: [],
    equipment: [
      "A light crossbow and 20 bolts or any simple weapon",
      "A component pouch or an arcane focus",
      "Leather armor, any simple weapon, and two daggers",
      "A scholar's pack or a dungeoneer's pack",
    ],
    ASILevels: [4, 8, 12, 16, 19],
    subClassName: "Otherworldly Patron",
    subClassDesc:
      "you struck a bargain with an otherworldly being of your choice. ",
    subfeatLevels: [1, 6, 10, 14],
  },
];
export default Classes;
