-- AlterTable
ALTER TABLE "Class" ALTER COLUMN "subClassDesc" SET NOT NULL,
ALTER COLUMN "subClassDesc" SET DATA TYPE TEXT,
ALTER COLUMN "subClassName" SET NOT NULL,
ALTER COLUMN "subClassName" SET DATA TYPE TEXT;
