import { DamageTypes, Prisma } from "@prisma/client";

const Weapons: Prisma.WeaponCreateManyInput[] = [
  {
    name: "Club",
    cost: "1 sp",
    weight: "2 lb.",
    damage: "1d4",
    damageType: DamageTypes.BLUDGEONING,
    isRanged: false,
    isSimple: true,
  },
  {
    name: "Dagger",
    cost: "2 gp",
    weight: "1 lb.",
    damage: "1d4",
    damageType: DamageTypes.PIERCING,
    isRanged: true,
    isSimple: true,
  },
  {
    name: "Greatclub",
    cost: "2 sp",
    weight: "10 lb.",
    damage: "1d8",
    damageType: DamageTypes.BLUDGEONING,
    isRanged: false,
    isSimple: true,
  },
  {
    name: "Handaxe",
    cost: "5 gp",
    weight: "2 lb.",
    damage: "1d6",
    damageType: DamageTypes.SLASHING,
    isRanged: true,
    isSimple: true,
  },
  {
    name: "Javelin",
    cost: "5 sp",
    weight: "2 lb.",
    damage: "1d6",
    damageType: DamageTypes.PIERCING,
    isRanged: true,
    isSimple: true,
  },
  {
    name: "Light Hammer",
    cost: "2 gp",
    weight: "2 lb.",
    damage: "1d4",
    damageType: DamageTypes.BLUDGEONING,
    isRanged: true,
    isSimple: true,
  },
  {
    name: "Mace",
    cost: "5 gp",
    weight: "4 lb.",
    damage: "1d6",
    damageType: DamageTypes.BLUDGEONING,
    isRanged: false,
    isSimple: true,
  },
  {
    name: "Quarterstaff",
    cost: "2 sp",
    weight: "4 lb.",
    damage: "1d6",
    damageType: DamageTypes.BLUDGEONING,
    isRanged: false,
    isSimple: true,
  },
  {
    name: "Sickle",
    cost: "1 gp",
    weight: "2 lb.",
    damage: "1d4",
    damageType: DamageTypes.SLASHING,
    isRanged: false,
    isSimple: true,
  },
  {
    name: "Spear",
    cost: "1 gp",
    weight: "3 lb.",
    damage: "1d6",
    damageType: DamageTypes.PIERCING,
    isRanged: false,
    isSimple: true,
  },
  {
    name: "Crossbow, Light",
    cost: "25 gp",
    weight: "5 lb.",
    damage: "1d8",
    damageType: DamageTypes.PIERCING,
    isRanged: true,
    isSimple: false,
  },
  {
    name: "Dart",
    cost: "5 cp",
    weight: "1/4 lb.",
    damage: "1d4",
    damageType: DamageTypes.PIERCING,
    isRanged: true,
    isSimple: false,
  },
  {
    name: "Shortbow",
    cost: "25 gp",
    weight: "2 lb.",
    damage: "1d6",
    damageType: DamageTypes.PIERCING,
    isRanged: true,
    isSimple: false,
  },
  {
    name: "Sling",
    cost: "1 sp",
    weight: "-",
    damage: "1d4",
    damageType: DamageTypes.BLUDGEONING,
    isRanged: true,
    isSimple: false,
  },
  {
    name: "Battleaxe",
    cost: "10 gp",
    weight: "4 lb.",
    damage: "1d8",
    damageType: DamageTypes.SLASHING,
    isRanged: false,
    isSimple: false,
  },
  {
    name: "Flail",
    cost: "10 gp",
    weight: "2 lb.",
    damage: "1d8",
    damageType: DamageTypes.BLUDGEONING,
    isRanged: false,
    isSimple: false,
  },
  {
    name: "Glaive",
    cost: "20 gp",
    weight: "6 lb.",
    damage: "1d10",
    damageType: DamageTypes.SLASHING,
    isRanged: false,
    isSimple: false,
  },
  {
    name: "Greataxe",
    cost: "30 gp",
    weight: "7 lb.",
    damage: "1d12",
    damageType: DamageTypes.SLASHING,
    isRanged: false,
    isSimple: false,
  },
  {
    name: "Greatsword",
    cost: "50 gp",
    weight: "6 lb.",
    damage: "2d6",
    damageType: DamageTypes.SLASHING,
    isRanged: false,
    isSimple: false,
  },
  {
    name: "Halberd",
    cost: "20 gp",
    weight: "6 lb.",
    damage: "1d10",
    damageType: DamageTypes.SLASHING,
    isRanged: false,
    isSimple: false,
  },
  {
    name: "Lance",
    cost: "10 gp",
    weight: "6 lb.",
    damage: "1d12",
    damageType: DamageTypes.PIERCING,
    isRanged: false,
    isSimple: false,
  },
  {
    name: "Longsword",
    cost: "15 gp",
    weight: "3 lb.",
    damage: "1d8",
    damageType: DamageTypes.SLASHING,
    isRanged: false,
    isSimple: false,
  },
  {
    name: "Maul",
    cost: "10 gp",
    weight: "10 lb.",
    damage: "2d6",
    damageType: DamageTypes.BLUDGEONING,
    isRanged: false,
    isSimple: false,
  },
  {
    name: "Morningstar",
    cost: "15 gp",
    weight: "4 lb.",
    damage: "1d8",
    damageType: DamageTypes.PIERCING,
    isRanged: false,
    isSimple: false,
  },
  {
    name: "Pike",
    cost: "5 gp",
    weight: "18 lb.",
    damage: "1d10",
    damageType: DamageTypes.PIERCING,
    isRanged: false,
    isSimple: false,
  },
  {
    name: "Rapier",
    cost: "25 gp",
    weight: "2 lb.",
    damage: "1d8",
    damageType: DamageTypes.PIERCING,
    isRanged: false,
    isSimple: false,
  },
  {
    name: "Scimitar",
    cost: "25 gp",
    weight: "3 lb.",
    damage: "1d6",
    damageType: DamageTypes.SLASHING,
    isRanged: false,
    isSimple: false,
  },
  {
    name: "Shortsword",
    cost: "10 gp",
    weight: "2 lb.",
    damage: "1d6",
    damageType: DamageTypes.PIERCING,
    isRanged: false,
    isSimple: false,
  },
  {
    name: "Trident",
    cost: "5 gp",
    weight: "4 lb.",
    damage: "1d6",
    damageType: DamageTypes.PIERCING,
    isRanged: false,
    isSimple: false,
  },
  {
    name: "War Pick",
    cost: "5 gp",
    weight: "2 lb.",
    damage: "1d8",
    damageType: DamageTypes.PIERCING,
    isRanged: false,
    isSimple: false,
  },
  {
    name: "Warhammer",
    cost: "15 gp",
    weight: "2 lb.",
    damage: "1d8",
    damageType: DamageTypes.BLUDGEONING,
    isRanged: false,
    isSimple: false,
  },
  {
    name: "Whip",
    cost: "2 gp",
    weight: "3 lb.",
    damage: "1d4",
    damageType: DamageTypes.SLASHING,
    isRanged: false,
    isSimple: false,
  },
  {
    name: "Blowgun",
    cost: "10 gp",
    weight: "1 lb.",
    damage: "1",
    damageType: DamageTypes.PIERCING,
    isRanged: true,
    isSimple: false,
  },
  {
    name: "Crossbow, Hand",
    cost: "75 gp",
    weight: "3 lb.",
    damage: "1d6",
    damageType: DamageTypes.PIERCING,
    isRanged: true,
    isSimple: false,
  },
  {
    name: "Crossbow, Heavy",
    cost: "50 gp",
    weight: "18 lb.",
    damage: "1d10",
    damageType: DamageTypes.PIERCING,
    isRanged: true,
    isSimple: false,
  },
  {
    name: "Longbow",
    cost: "50 gp",
    weight: "2 lb.",
    damage: "1d8",
    damageType: DamageTypes.PIERCING,
    isRanged: true,
    isSimple: false,
  },
  {
    name: "Net",
    cost: "1 gp",
    weight: "3 lb.",
    damage: "-",
    damageType: DamageTypes.NONE,
    isRanged: true,
    isSimple: false,
  },
];

export default Weapons;
