// Path: scripts/generateTopPages.ts
// This file was generated by a script. Do not edit this file directly.

export const topPages = {
  item: [
    {
      page: '/item/Scroll-of-Dimension-Door',
      visits: 34,
    },
    {
      page: '/item/chain-mail',
      visits: 5,
    },
    {
      page: '/item/Animated-Shield',
      visits: 4,
    },
    {
      page: '/item/scale-mail',
      visits: 4,
    },
    {
      page: '/item/Ladder-(10-foot)',
      visits: 3,
    },
    {
      page: '/item/battleaxe',
      visits: 3,
    },
    {
      page: '/item/studded-leather-armor',
      visits: 3,
    },
    {
      page: '/item/Javelin',
      visits: 2,
    },
    {
      page: '/item/Piton',
      visits: 2,
    },
    {
      page: '/item/Scroll-of-Identify',
      visits: 2,
    },
    {
      page: '/item/scroll-of-magic-weapon',
      visits: 2,
    },
    {
      page: '/item/Scroll-of-Alter-Self',
      visits: 2,
    },
    {
      page: '/item/maxy:mace-of-necrotic-smiting',
      visits: 2,
    },
    {
      page: '/item/Handaxe',
      visits: 1,
    },
    {
      page: "/item/Scroll-of-Dragon's-Breath",
      visits: 1,
    },
    {
      page: '/item/Scroll-of-Hold-Monster',
      visits: 1,
    },
    {
      page: '/item/Scroll-of-Meteor-Swarm',
      visits: 1,
    },
    {
      page: '/item/Scroll-of-Seeming',
      visits: 1,
    },
    {
      page: "/item/Weaver's-Tools",
      visits: 1,
    },
    {
      page: '/item/boots-of-elvenkind',
      visits: 1,
    },
    {
      page: '/item/caltrops-bag-of-20',
      visits: 1,
    },
    {
      page: '/item/cloak-of-elvenkind',
      visits: 1,
    },
    {
      page: '/item/club',
      visits: 1,
    },
    {
      page: '/item/crossbow-bolt',
      visits: 1,
    },
    {
      page: '/item/crossbow-light',
      visits: 1,
    },
    {
      page: '/item/explorers-pack',
      visits: 1,
    },
    {
      page: '/item/greatclub',
      visits: 1,
    },
    {
      page: '/item/handaxe',
      visits: 1,
    },
    {
      page: '/item/lance',
      visits: 1,
    },
    {
      page: '/item/light-hammer',
      visits: 1,
    },
    {
      page: '/item/longbow',
      visits: 1,
    },
    {
      page: '/item/maxy:glaive-of-the-feywild',
      visits: 1,
    },
    {
      page: '/item/monster-hunter-pack',
      visits: 1,
    },
    {
      page: '/item/scroll-of-bless',
      visits: 1,
    },
    {
      page: '/item/scroll-of-invulnerability',
      visits: 1,
    },
    {
      page: '/item/scroll-of-magic-jar',
      visits: 1,
    },
    {
      page: '/item/scroll-of-polymorph',
      visits: 1,
    },
    {
      page: '/item/shortbow',
      visits: 1,
    },
    {
      page: '/item/smiths-tools',
      visits: 1,
    },
    {
      page: '/item/tinkers-tools',
      visits: 1,
    },
  ],
  subclass: [
    {
      page: '/subclass/storm-herald',
      visits: 3,
    },
    {
      page: '/subclass/Twilight-Domain',
      visits: 2,
    },
    {
      page: '/subclass/Path-of-the-Berserker',
      visits: 2,
    },
    {
      page: '/subclass/Lunar-Sorcery',
      visits: 1,
    },
    {
      page: '/subclass/School-of-Abjuration',
      visits: 1,
    },
    {
      page: '/subclass/armorer',
      visits: 1,
    },
    {
      page: '/subclass/artillerist',
      visits: 1,
    },
    {
      page: '/subclass/assassin',
      visits: 1,
    },
    {
      page: '/subclass/battle-smith',
      visits: 1,
    },
    {
      page: '/subclass/chronurgy-magic',
      visits: 1,
    },
    {
      page: '/subclass/circle-of-the-land',
      visits: 1,
    },
  ],
  background: [
    {
      page: '/background/haunted-one',
      visits: 4,
    },
    {
      page: '/background/outlander',
      visits: 3,
    },
    {
      page: '/background/athlete',
      visits: 2,
    },
    {
      page: '/background/courtier',
      visits: 2,
    },
    {
      page: '/background/Investigator-(VRGR)',
      visits: 1,
    },
    {
      page: '/background/Rewarded',
      visits: 1,
    },
    {
      page: '/background/Shipwright',
      visits: 1,
    },
    {
      page: '/background/guild-artisan',
      visits: 1,
    },
    {
      page: '/background/hermit',
      visits: 1,
    },
    {
      page: '/background/urban-bounty-hunter',
      visits: 1,
    },
    {
      page: '/background/vizier',
      visits: 1,
    },
  ],
  species: [
    {
      page: '/species/kender',
      visits: 6,
    },
    {
      page: '/species/shifter-mmom',
      visits: 4,
    },
    {
      page: '/species/centaur-moot',
      visits: 3,
    },
    {
      page: '/species/aarakocra-mmom',
      visits: 2,
    },
    {
      page: '/species/aetherborn',
      visits: 2,
    },
    {
      page: '/species/goblin-psi',
      visits: 2,
    },
    {
      page: '/species/tabaxi-mmom',
      visits: 2,
    },
    {
      page: '/species/verdan',
      visits: 2,
    },
    {
      page: '/species/centaur-ggr',
      visits: 1,
    },
    {
      page: '/species/centaur-mmom',
      visits: 1,
    },
    {
      page: '/species/duergar-scag',
      visits: 1,
    },
    {
      page: '/species/elf',
      visits: 1,
    },
    {
      page: '/species/goliath-mmom',
      visits: 1,
    },
    {
      page: '/species/half-elf',
      visits: 1,
    },
    {
      page: '/species/human',
      visits: 1,
    },
    {
      page: '/species/kenku-mmom',
      visits: 1,
    },
    {
      page: '/species/kenku-vgm',
      visits: 1,
    },
    {
      page: '/species/shifter-erlw',
      visits: 1,
    },
    {
      page: '/species/tabaxi-vgm',
      visits: 1,
    },
    {
      page: '/species/vampire-psz',
      visits: 1,
    },
  ],
  class: [
    {
      page: '/class/artificer',
      visits: 8,
    },
    {
      page: '/class/barbarian',
      visits: 8,
    },
    {
      page: '/class/ranger',
      visits: 5,
    },
    {
      page: '/class/monk',
      visits: 2,
    },
    {
      page: '/class/druid',
      visits: 1,
    },
    {
      page: '/class/fighter',
      visits: 1,
    },
    {
      page: '/class/paladin',
      visits: 1,
    },
    {
      page: '/class/wizard',
      visits: 1,
    },
  ],
  spells: [
    {
      page: '/spells/gift-of-alacrity',
      visits: 34,
    },
    {
      page: '/spells/compelled-duel',
      visits: 31,
    },
    {
      page: '/spells/magic-weapon',
      visits: 15,
    },
    {
      page: '/spells/entangle',
      visits: 12,
    },
    {
      page: '/spells/Scrying',
      visits: 6,
    },
    {
      page: '/spells/hypnotic-pattern',
      visits: 6,
    },
    {
      page: "/spells/Snilloc's-Snowball-Storm",
      visits: 5,
    },
    {
      page: '/spells/longstrider',
      visits: 4,
    },
    {
      page: '/spells/Animate-Objects',
      visits: 3,
    },
    {
      page: '/spells/Stoneskin',
      visits: 3,
    },
    {
      page: '/spells/healing-word',
      visits: 3,
    },
    {
      page: '/spells/jump',
      visits: 3,
    },
    {
      page: '/spells/spike-growth',
      visits: 3,
    },
    {
      page: '/spells/druidcraft',
      visits: 3,
    },
    {
      page: '/spells/thorn-whip',
      visits: 3,
    },
    {
      page: '/spells/Alter-Self',
      visits: 2,
    },
    {
      page: '/spells/Burning-Hands',
      visits: 2,
    },
    {
      page: '/spells/Catapult',
      visits: 2,
    },
    {
      page: '/spells/Chromatic-Orb',
      visits: 2,
    },
    {
      page: '/spells/Disintegrate',
      visits: 2,
    },
    {
      page: '/spells/Forbiddance',
      visits: 2,
    },
    {
      page: '/spells/animal-messenger',
      visits: 2,
    },
    {
      page: '/spells/color-spray',
      visits: 2,
    },
    {
      page: '/spells/fire-shield',
      visits: 2,
    },
    {
      page: '/spells/mental-prison',
      visits: 2,
    },
    {
      page: '/spells/motivational-speech',
      visits: 2,
    },
    {
      page: '/spells/slow',
      visits: 2,
    },
    {
      page: '/spells/speak-with-animals',
      visits: 2,
    },
    {
      page: '/spells/create-bonfire',
      visits: 2,
    },
    {
      page: '/spells/detect-magic',
      visits: 2,
    },
    {
      page: '/spells/vicious-mockery',
      visits: 2,
    },
    {
      page: "/spells/Aganazzar's-Scorcher",
      visits: 1,
    },
    {
      page: '/spells/Fireball',
      visits: 1,
    },
    {
      page: '/spells/Glyph-of-Warding',
      visits: 1,
    },
    {
      page: '/spells/Investiture-of-Flame',
      visits: 1,
    },
    {
      page: '/spells/Maelstrom',
      visits: 1,
    },
    {
      page: '/spells/Shadow-Of-Moil',
      visits: 1,
    },
    {
      page: '/spells/Synaptic-Static',
      visits: 1,
    },
    {
      page: '/spells/aganazzars-scorcher',
      visits: 1,
    },
    {
      page: '/spells/aid',
      visits: 1,
    },
    {
      page: '/spells/animal-friendship',
      visits: 1,
    },
    {
      page: '/spells/arcane-lock',
      visits: 1,
    },
    {
      page: '/spells/ashardalons-stride',
      visits: 1,
    },
    {
      page: '/spells/beast-sense',
      visits: 1,
    },
    {
      page: '/spells/bestow-curse',
      visits: 1,
    },
    {
      page: '/spells/branding-smite',
      visits: 1,
    },
    {
      page: '/spells/catnap',
      visits: 1,
    },
    {
      page: '/spells/confusion',
      visits: 1,
    },
    {
      page: '/spells/cordon-of-arrows',
      visits: 1,
    },
    {
      page: '/spells/create-homunculus',
      visits: 1,
    },
    {
      page: '/spells/dancing-lights',
      visits: 1,
    },
    {
      page: '/spells/dissonant-whispers',
      visits: 1,
    },
    {
      page: '/spells/divination',
      visits: 1,
    },
    {
      page: '/spells/earth-tremor',
      visits: 1,
    },
    {
      page: '/spells/earthbind',
      visits: 1,
    },
    {
      page: '/spells/enhance-ability',
      visits: 1,
    },
    {
      page: '/spells/freedom-of-movement',
      visits: 1,
    },
    {
      page: '/spells/giant-insect',
      visits: 1,
    },
    {
      page: '/spells/goodberry',
      visits: 1,
    },
    {
      page: '/spells/grasping-vine',
      visits: 1,
    },
    {
      page: '/spells/healing-spirit',
      visits: 1,
    },
    {
      page: '/spells/invisibility',
      visits: 1,
    },
    {
      page: '/spells/kinetic-jaunt',
      visits: 1,
    },
    {
      page: '/spells/locate-creature',
      visits: 1,
    },
    {
      page: '/spells/mold-earth',
      visits: 1,
    },
    {
      page: '/spells/pass-without-trace',
      visits: 1,
    },
    {
      page: '/spells/polymorph',
      visits: 1,
    },
    {
      page: '/spells/primal-savagery',
      visits: 1,
    },
    {
      page: '/spells/protection-from-evil-and-good',
      visits: 1,
    },
    {
      page: '/spells/shatter',
      visits: 1,
    },
    {
      page: '/spells/shillelagh',
      visits: 1,
    },
    {
      page: '/spells/stone-shape',
      visits: 1,
    },
    {
      page: '/spells/stoneskin',
      visits: 1,
    },
    {
      page: '/spells/thunderclap',
      visits: 1,
    },
    {
      page: '/spells/toll-the-dead',
      visits: 1,
    },
    {
      page: '/spells/watery-sphere',
      visits: 1,
    },
  ],
  subspecies: [
    {
      page: '/subspecies/beasthide-shifter',
      visits: 11,
    },
    {
      page: '/subspecies/High-Elf-Descent',
      visits: 2,
    },
  ],
  creature: [
    {
      page: '/creature/giant-wolf-spider',
      visits: 6,
    },
    {
      page: '/creature/adult-blue-dragon',
      visits: 4,
    },
    {
      page: '/creature/archmage',
      visits: 3,
    },
    {
      page: '/creature/giant-boar',
      visits: 3,
    },
    {
      page: '/creature/cult-fanatic',
      visits: 2,
    },
    {
      page: '/creature/gladiator',
      visits: 2,
    },
    {
      page: '/creature/polar-bear',
      visits: 2,
    },
    {
      page: '/creature/red-dragon-wyrmling',
      visits: 2,
    },
    {
      page: '/creature/giant-toad',
      visits: 2,
    },
    {
      page: '/creature/Giant-Ape',
      visits: 1,
    },
    {
      page: '/creature/Octopus',
      visits: 1,
    },
    {
      page: '/creature/acolyte',
      visits: 1,
    },
    {
      page: '/creature/ancient-black-dragon',
      visits: 1,
    },
    {
      page: '/creature/ape',
      visits: 1,
    },
    {
      page: '/creature/chuul',
      visits: 1,
    },
    {
      page: '/creature/crab',
      visits: 1,
    },
    {
      page: '/creature/doppelganger',
      visits: 1,
    },
    {
      page: '/creature/draft-horse',
      visits: 1,
    },
    {
      page: '/creature/dretch',
      visits: 1,
    },
    {
      page: '/creature/giant-constrictor-snake',
      visits: 1,
    },
    {
      page: '/creature/giant-goat',
      visits: 1,
    },
    {
      page: '/creature/hunter-shark',
      visits: 1,
    },
    {
      page: '/creature/lizard',
      visits: 1,
    },
    {
      page: '/creature/panther',
      visits: 1,
    },
    {
      page: '/creature/plesiosaurus',
      visits: 1,
    },
    {
      page: '/creature/quipper',
      visits: 1,
    },
    {
      page: '/creature/rhinoceros',
      visits: 1,
    },
    {
      page: '/creature/saber-toothed-tiger',
      visits: 1,
    },
    {
      page: '/creature/tribal-warrior',
      visits: 1,
    },
    {
      page: '/creature/worg',
      visits: 1,
    },
  ],
  feats: [
    {
      page: '/feats/gunner',
      visits: 14,
    },
    {
      page: '/feats/mobile',
      visits: 3,
    },
    {
      page: '/feats/Bountiful-Luck',
      visits: 2,
    },
    {
      page: '/feats/Dragon-Hide',
      visits: 2,
    },
    {
      page: '/feats/Strixhaven-Initiate',
      visits: 2,
    },
    {
      page: '/feats/crusher',
      visits: 2,
    },
    {
      page: '/feats/Adept-of-the-Black-Robes',
      visits: 1,
    },
    {
      page: '/feats/Adept-of-the-Red-Robes',
      visits: 1,
    },
    {
      page: '/feats/alert',
      visits: 1,
    },
    {
      page: '/feats/athlete',
      visits: 1,
    },
    {
      page: '/feats/baleful-scion',
      visits: 1,
    },
    {
      page: '/feats/defensive-duelist',
      visits: 1,
    },
    {
      page: '/feats/lucky',
      visits: 1,
    },
    {
      page: '/feats/rob:vape',
      visits: 1,
    },
    {
      page: '/feats/sentinel',
      visits: 1,
    },
    {
      page: '/feats/tavern-brawler',
      visits: 1,
    },
  ],
};
