// Path: scripts/generateTopPages.ts
// This file was generated by a script. Do not edit this file directly.

export const topPages = {
  item: [
    {
      page: '/item/Spiked-Armor',
      visits: 11,
    },
    {
      page: '/item/Chain-Mail',
      visits: 11,
    },
    {
      page: '/item/Scroll-of-Sunbeam',
      visits: 10,
    },
    {
      page: '/item/Scroll-of-Skill-Empowerment',
      visits: 9,
    },
    {
      page: '/item/Crowbar',
      visits: 8,
    },
    {
      page: '/item/Blue-Spinel',
      visits: 6,
    },
    {
      page: '/item/Scroll-of-Plane-Shift',
      visits: 6,
    },
    {
      page: '/item/Scroll-of-Sequester',
      visits: 5,
    },
    {
      page: '/item/Block-of-Incense',
      visits: 3,
    },
    {
      page: '/item/Crossbow-(Hand)',
      visits: 3,
    },
    {
      page: "/item/Explorer's-Pack",
      visits: 3,
    },
    {
      page: '/item/Prayer-Book',
      visits: 3,
    },
    {
      page: "/item/Thieves'-Tools",
      visits: 3,
    },
    {
      page: "/item/Diplomat's-Pack",
      visits: 3,
    },
    {
      page: '/item/Leather-Armor',
      visits: 3,
    },
    {
      page: '/item/Dagger',
      visits: 2,
    },
    {
      page: "/item/Entertainer's-Pack",
      visits: 2,
    },
    {
      page: '/item/Grappling-Hook',
      visits: 2,
    },
    {
      page: '/item/Scale-Mail',
      visits: 2,
    },
    {
      page: '/item/Scroll-of-Vortex-Warp',
      visits: 2,
    },
    {
      page: "/item/Tinker's-Tools",
      visits: 2,
    },
  ],
  subclass: [
    {
      page: '/subclass/Path-of-the-Giant',
      visits: 9,
    },
    {
      page: '/subclass/Drakewarden',
      visits: 9,
    },
    {
      page: '/subclass/Storm-Herald',
      visits: 5,
    },
    {
      page: '/subclass/Battle-Smith',
      visits: 4,
    },
    {
      page: '/subclass/Oath-of-the-Ancients',
      visits: 4,
    },
    {
      page: '/subclass/The-Hexblade',
      visits: 3,
    },
    {
      page: '/subclass/Arcana-Domain',
      visits: 2,
    },
    {
      page: '/subclass/Arcane-Archer',
      visits: 2,
    },
    {
      page: '/subclass/Banneret',
      visits: 2,
    },
    {
      page: '/subclass/Circle-of-the-Land',
      visits: 2,
    },
    {
      page: '/subclass/Circle-of-the-Moon',
      visits: 2,
    },
    {
      page: '/subclass/College-of-Spirits',
      visits: 2,
    },
    {
      page: '/subclass/Death-Domain',
      visits: 2,
    },
    {
      page: '/subclass/Lunar-Sorcery',
      visits: 2,
    },
    {
      page: '/subclass/School-of-Divination',
      visits: 2,
    },
    {
      page: '/subclass/Swarmkeeper',
      visits: 2,
    },
    {
      page: '/subclass/War-Magic',
      visits: 2,
    },
    {
      page: '/subclass/Way-of-the-Astral-Self',
      visits: 2,
    },
    {
      page: '/subclass/Way-of-the-Long-Death',
      visits: 2,
    },
  ],
  background: [
    {
      page: '/background/Urban-Bounty-Hunter',
      visits: 13,
    },
    {
      page: '/background/Sailor',
      visits: 7,
    },
    {
      page: '/background/Investigator-(VRGR)',
      visits: 6,
    },
    {
      page: '/background/Faction-Agent',
      visits: 5,
    },
    {
      page: '/background/Investigator-(VRGR',
      visits: 5,
    },
    {
      page: '/background/Guild-Artisan',
      visits: 4,
    },
    {
      page: '/background/Haunted-One',
      visits: 3,
    },
    {
      page: '/background/Ruined',
      visits: 3,
    },
    {
      page: '/background/Investigator',
      visits: 2,
    },
    {
      page: '/background/Cloistered-Scholar',
      visits: 2,
    },
    {
      page: '/background/Acolyte',
      visits: 1,
    },
    {
      page: '/background/Anthropologist',
      visits: 1,
    },
    {
      page: '/background/Criminal',
      visits: 1,
    },
    {
      page: '/background/Faceless',
      visits: 1,
    },
    {
      page: '/background/Knight',
      visits: 1,
    },
    {
      page: '/background/Mage-of-High-Sorcery',
      visits: 1,
    },
    {
      page: '/background/Outlander',
      visits: 1,
    },
    {
      page: '/background/Rune-Carver',
      visits: 1,
    },
    {
      page: '/background/Shipwright',
      visits: 1,
    },
  ],
  species: [
    {
      page: '/species/Air-Genasi-(EEPC)',
      visits: 7,
    },
    {
      page: '/species/Warforged',
      visits: 7,
    },
    {
      page: '/species/Air-Genasi-(MMOM)',
      visits: 6,
    },
    {
      page: '/species/Water-Genasi-(MMOM)',
      visits: 4,
    },
    {
      page: '/species/Elf',
      visits: 4,
    },
    {
      page: '/species/Aarakocra-(MMOM)',
      visits: 3,
    },
    {
      page: '/species/Dwarf',
      visits: 3,
    },
    {
      page: '/species/Verdan',
      visits: 3,
    },
    {
      page: '/species/Dragonborn',
      visits: 2,
    },
    {
      page: '/species/Eladrin-(MToF)',
      visits: 2,
    },
  ],
  class: [
    {
      page: '/class/ranger',
      visits: 36,
    },
    {
      page: '/class/barbarian',
      visits: 19,
    },
    {
      page: '/class/artificer',
      visits: 14,
    },
    {
      page: '/class/bard',
      visits: 12,
    },
    {
      page: '/class/druid',
      visits: 9,
    },
    {
      page: '/class/sorcerer',
      visits: 9,
    },
    {
      page: '/class/wizard',
      visits: 8,
    },
    {
      page: '/class/monk',
      visits: 7,
    },
    {
      page: '/class/cleric',
      visits: 6,
    },
    {
      page: '/class/fighter',
      visits: 6,
    },
    {
      page: '/class/paladin',
      visits: 3,
    },
    {
      page: '/class/rogue',
      visits: 3,
    },
    {
      page: '/class/warlock',
      visits: 1,
    },
  ],
  spells: [
    {
      page: '/spells/Longstrider',
      visits: 17,
    },
    {
      page: '/spells/Dancing-Lights',
      visits: 17,
    },
    {
      page: '/spells/Detect-Magic',
      visits: 13,
    },
    {
      page: '/spells/Enhance-Ability',
      visits: 13,
    },
    {
      page: '/spells/Dark-Star',
      visits: 11,
    },
    {
      page: '/spells/Mending',
      visits: 11,
    },
    {
      page: "/spells/Tasha's-Mind-Whip",
      visits: 10,
    },
    {
      page: '/spells/Chromatic-Orb',
      visits: 10,
    },
    {
      page: '/spells/Prestidigitation',
      visits: 9,
    },
    {
      page: '/spells/Booming-Blade',
      visits: 9,
    },
    {
      page: '/spells/Hold-Monster',
      visits: 8,
    },
    {
      page: '/spells/Charm-Person',
      visits: 8,
    },
    {
      page: '/spells/Produce-Flame',
      visits: 7,
    },
    {
      page: '/spells/Toll-the-Dead',
      visits: 7,
    },
    {
      page: '/spells/Vortex-Warp',
      visits: 7,
    },
    {
      page: '/spells/Dissonant-Whispers',
      visits: 7,
    },
    {
      page: '/spells/Absorb-Elements',
      visits: 7,
    },
    {
      page: '/spells/Expeditious-Retreat',
      visits: 7,
    },
    {
      page: '/spells/Burning-Hands',
      visits: 7,
    },
    {
      page: '/spells/Protection-from-Evil-and-Good',
      visits: 6,
    },
    {
      page: '/spells/Light',
      visits: 6,
    },
    {
      page: '/spells/Chill-Touch',
      visits: 6,
    },
    {
      page: '/spells/Minor-Illusion',
      visits: 6,
    },
    {
      page: '/spells/Feather-Fall',
      visits: 5,
    },
    {
      page: '/spells/Shocking-Grasp',
      visits: 5,
    },
    {
      page: '/spells/Aid',
      visits: 5,
    },
    {
      page: '/spells/Calm-Emotions',
      visits: 5,
    },
    {
      page: '/spells/Comprehend-Languages',
      visits: 5,
    },
    {
      page: '/spells/Cure-Wounds',
      visits: 5,
    },
    {
      page: '/spells/Fire-Bolt',
      visits: 5,
    },
    {
      page: '/spells/Green-Flame-Blade',
      visits: 5,
    },
    {
      page: '/spells/Blade-Ward',
      visits: 5,
    },
    {
      page: '/spells/Encode-Thoughts',
      visits: 4,
    },
    {
      page: '/spells/Mind-Sliver',
      visits: 4,
    },
    {
      page: '/spells/Entangle',
      visits: 4,
    },
    {
      page: '/spells/Friends',
      visits: 4,
    },
    {
      page: '/spells/Identify',
      visits: 4,
    },
    {
      page: '/spells/Detect-Thoughts',
      visits: 4,
    },
    {
      page: '/spells/Chaos-Bolt',
      visits: 3,
    },
    {
      page: '/spells/Conjure-Animals',
      visits: 3,
    },
    {
      page: '/spells/False-Life',
      visits: 3,
    },
    {
      page: '/spells/Hail-of-Thorns',
      visits: 3,
    },
    {
      page: '/spells/Locate-Object',
      visits: 3,
    },
    {
      page: '/spells/Mage-Hand',
      visits: 3,
    },
    {
      page: '/spells/Magic-Mouth',
      visits: 3,
    },
    {
      page: '/spells/Summon-Lesser-Demons',
      visits: 3,
    },
    {
      page: '/spells/Thaumaturgy',
      visits: 3,
    },
    {
      page: '/spells/Thunderclap',
      visits: 3,
    },
    {
      page: '/spells/Gust',
      visits: 3,
    },
    {
      page: '/spells/Healing-Word',
      visits: 3,
    },
    {
      page: '/spells/Kinetic-Jaunt',
      visits: 3,
    },
    {
      page: '/spells/Sword-Burst',
      visits: 3,
    },
    {
      page: '/spells/Thunderwave',
      visits: 3,
    },
    {
      page: '/spells/Arms-of-Hadar',
      visits: 2,
    },
    {
      page: '/spells/Bless',
      visits: 2,
    },
    {
      page: '/spells/Control-Flames',
      visits: 2,
    },
    {
      page: "/spells/Hunter's-Mark",
      visits: 2,
    },
    {
      page: '/spells/Invisibility',
      visits: 2,
    },
    {
      page: '/spells/Jump',
      visits: 2,
    },
    {
      page: '/spells/Message',
      visits: 2,
    },
    {
      page: '/spells/Mirror-Image',
      visits: 2,
    },
    {
      page: '/spells/Mold-Earth',
      visits: 2,
    },
    {
      page: "/spells/Mordenkainen's-Magnificent-Mansion",
      visits: 2,
    },
    {
      page: '/spells/Poison-Spray',
      visits: 2,
    },
    {
      page: '/spells/Ray-of-Frost',
      visits: 2,
    },
    {
      page: '/spells/Silent-Image',
      visits: 2,
    },
    {
      page: '/spells/True-Strike',
      visits: 2,
    },
  ],
  subspecies: [
    {
      page: '/subspecies/Bronze-Dragonborn',
      visits: 14,
    },
    {
      page: '/subspecies/Protector-Aasimar',
      visits: 9,
    },
    {
      page: '/subspecies/Rock-Gnome',
      visits: 7,
    },
    {
      page: '/subspecies/Stout-Halfling',
      visits: 4,
    },
    {
      page: '/subspecies/High-Elf',
      visits: 2,
    },
    {
      page: '/subspecies/Variant-Human',
      visits: 2,
    },
  ],
  creature: [
    {
      page: '/creature/Giant-Ape',
      visits: 9,
    },
    {
      page: '/creature/Tiger',
      visits: 5,
    },
    {
      page: '/creature/Bulette',
      visits: 4,
    },
    {
      page: '/creature/Giant-Toad',
      visits: 4,
    },
    {
      page: '/creature/Black-Bear',
      visits: 3,
    },
    {
      page: '/creature/Brown-Bear',
      visits: 3,
    },
    {
      page: '/creature/Bandit',
      visits: 2,
    },
    {
      page: '/creature/Cult-Fanatic',
      visits: 2,
    },
    {
      page: '/creature/Balor',
      visits: 2,
    },
    {
      page: '/creature/Archmage',
      visits: 1,
    },
    {
      page: '/creature/Assassin',
      visits: 1,
    },
    {
      page: '/creature/Bandit-Captain',
      visits: 1,
    },
    {
      page: '/creature/Berserker',
      visits: 1,
    },
    {
      page: '/creature/Boar',
      visits: 1,
    },
    {
      page: '/creature/Bugbear',
      visits: 1,
    },
    {
      page: '/creature/Constrictor-Snake',
      visits: 1,
    },
    {
      page: '/creature/Crocodile',
      visits: 1,
    },
    {
      page: '/creature/Giant-Badger',
      visits: 1,
    },
    {
      page: '/creature/Giant-Frog',
      visits: 1,
    },
    {
      page: '/creature/Giant-Octopus',
      visits: 1,
    },
    {
      page: '/creature/Imp',
      visits: 1,
    },
    {
      page: '/creature/Marilith',
      visits: 1,
    },
    {
      page: '/creature/Nalfeshnee',
      visits: 1,
    },
    {
      page: '/creature/Pit-Fiend',
      visits: 1,
    },
  ],
  feats: [
    {
      page: '/feats/Cartomancer',
      visits: 3,
    },
    {
      page: '/feats/Gift-of-the-Chromatic-Dragon',
      visits: 3,
    },
  ],
};
