import { Prisma } from '@prisma/client';
import generateId from '../_helpers/generateId';
import { classIds } from './ClassIds';

const ColumnedFeatureSeed: Prisma.ColumnedFeatureCreateManyInput[] = [
  {
    id: '1',
    featureId: generateId('class', 'Cantrips', 'Bard', 1),
    classId: classIds.bard,
    name: 'Cantrips Known',
    rows: [
      '2',
      '2',
      '2',
      '3',
      '3',
      '3',
      '3',
      '3',
      '3',
      '4',
      '4',
      '4',
      '4',
      '4',
      '4',
      '4',
      '4',
      '4',
      '4',
      '4',
    ],
  },
  {
    id: '2',
    featureId: generateId('class', 'Spells Known', 'Bard', 2),
    classId: classIds.bard,
    name: 'Spells Known',
    rows: [
      '4',
      '5',
      '6',
      '7',
      '8',
      '9',
      '10',
      '11',
      '12',
      '14',
      '15',
      '15',
      '16',
      '18',
      '19',
      '19',
      '20',
      '22',
      '22',
      '22',
    ],
  },
  {
    id: '2',
    featureId: generateId('class', 'Sneak Attack', 'Rogue', 2),
    classId: classIds.rogue,
    name: 'Sneak Attack',
    rows: [
      '1d6',
      '1d6',
      '2d6',
      '2d6',
      '3d6',
      '3d6',
      '4d6',
      '4d6',
      '5d6',
      '5d6',
      '6d6',
      '6d6',
      '7d6',
      '7d6',
      '8d6',
      '8d6',
      '9d6',
      '9d6',
      '10d6',
      '10d6',
    ],
  },
  {
    id: '3',
    featureId: generateId('class', 'Rage', 'Barbarian', 1),
    classId: classIds.barbarian,
    name: 'Rages',
    rows: [
      '2',
      '2',
      '3',
      '3',
      '3',
      '4',
      '4',
      '4',
      '4',
      '4',
      '4',
      '5',
      '5',
      '5',
      '5',
      '5',
      '6',
      '6',
      '6',
      'Unlimited',
    ],
  },
  {
    id: '4',
    featureId: generateId('class', 'Rage', 'Barbarian', 1),
    classId: classIds.barbarian,
    name: 'Rage Damage',
    rows: [
      '+2',
      '+2',
      '+2',
      '+2',
      '+2',
      '+2',
      '+2',
      '+2',
      '+3',
      '+3',
      '+3',
      '+3',
      '+3',
      '+3',
      '+3',
      '+4',
      '+4',
      '+4',
      '+4',
      '+4',
    ],
  },
  {
    id: '5',
    featureId: generateId('class', 'Cantrips', 'Druid', 1),
    classId: classIds.druid,
    name: 'Cantrips Known',
    rows: [
      '2',
      '2',
      '2',
      '3',
      '3',
      '3',
      '3',
      '3',
      '3',
      '4',
      '4',
      '4',
      '4',
      '4',
      '4',
      '4',
      '4',
      '4',
      '4',
      '4',
    ],
  },
  {
    id: '6',
    featureId: generateId('class', 'Martial Arts', 'Monk', 2),
    classId: classIds.monk,
    name: 'Martial Arts',
    rows: [
      '1d4',
      '1d4',
      '1d4',
      '1d4',
      '1d6',
      '1d6',
      '1d6',
      '1d6',
      '1d8',
      '1d8',
      '1d8',
      '1d8',
      '1d8',
      '1d8',
      '1d8',
      '1d8',
      '1d10',
      '1d10',
      '1d10',
      '1d10',
    ],
  },
  {
    id: '7',
    featureId: generateId('class', 'Ki', 'Monk', 3),
    classId: classIds.monk,
    name: 'Ki Points',
    rows: [
      '-',
      '2',
      '3',
      '4',
      '5',
      '6',
      '7',
      '8',
      '9',
      '10',
      '11',
      '12',
      '13',
      '14',
      '15',
      '16',
      '17',
      '18',
      '19',
      '20',
    ],
  },
  {
    id: '8',
    featureId: generateId('class', 'Unarmored Movement', 'Monk', 4),
    classId: classIds.monk,
    name: 'Unarmored Movement',
    rows: [
      '-',
      '+10 ft.',
      '+10 ft.',
      '+10 ft.',
      '+10 ft.',
      '+15 ft.',
      '+15 ft.',
      '+15 ft.',
      '+15 ft.',
      '+20 ft.',
      '+20 ft.',
      '+20 ft.',
      '+20 ft.',
      '+25 ft.',
      '+25 ft.',
      '+25 ft.',
      '+25 ft.',
      '+30 ft.',
      '+30 ft.',
      '+30 ft.',
    ],
  },
  {
    id: '9',
    featureId: generateId('class', 'Cantrips', 'Sorcerer', 1),
    classId: classIds.sorcerer,
    name: 'Cantrips Known',
    rows: [
      '4',
      '4',
      '4',
      '5',
      '5',
      '5',
      '5',
      '5',
      '5',
      '6',
      '6',
      '6',
      '6',
      '6',
      '6',
      '6',
      '6',
      '6',
      '6',
      '6',
    ],
  },
  {
    id: '10',
    featureId: generateId('class', 'Spells Known', 'Sorcerer', 2),
    classId: classIds.sorcerer,
    name: 'Spells Known',
    rows: [
      '2',
      '3',
      '4',
      '5',
      '6',
      '7',
      '8',
      '9',
      '10',
      '11',
      '12',
      '12',
      '13',
      '13',
      '14',
      '14',
      '15',
      '15',
      '15',
      '15',
    ],
  },
  {
    id: '11',
    featureId: generateId('class', 'Font of Magic', 'Sorcerer', 1),
    classId: classIds.sorcerer,
    name: 'Sorcery Points',
    rows: [
      '-',
      '2',
      '3',
      '4',
      '5',
      '6',
      '7',
      '8',
      '9',
      '10',
      '11',
      '12',
      '13',
      '14',
      '15',
      '16',
      '17',
      '18',
      '19',
      '20',
    ],
  },
  {
    id: '12',
    featureId: generateId('class', 'Cantrips', 'Warlock', 1),
    classId: classIds.warlock,
    name: 'Cantrips Known',
    rows: [
      '2',
      '2',
      '2',
      '3',
      '3',
      '3',
      '3',
      '3',
      '3',
      '4',
      '4',
      '4',
      '4',
      '4',
      '4',
      '4',
      '4',
      '4',
      '4',
      '4',
    ],
  },
  {
    id: '13',
    featureId: generateId('class', 'Spells Known', 'Warlock', 2),
    classId: classIds.warlock,
    name: 'Spells Known',
    rows: [
      '2',
      '3',
      '4',
      '5',
      '6',
      '7',
      '8',
      '9',
      '10',
      '10',
      '11',
      '11',
      '12',
      '12',
      '13',
      '13',
      '14',
      '14',
      '15',
      '15',
    ],
  },
  {
    id: '14',
    featureId: generateId('class', 'Spells Known', 'Warlock', 2),
    classId: classIds.warlock,
    name: 'Slot Level',
    rows: [
      '1st',
      '1st',
      '2nd',
      '2nd',
      '3rd',
      '3rd',
      '4th',
      '4th',
      '5th',
      '5th',
      '5th',
      '5th',
      '5th',
      '5th',
      '5th',
      '5th',
      '5th',
      '5th',
      '5th',
      '5th',
    ],
  },
  {
    id: '15',
    featureId: generateId('class', 'Eldritch Invocations', 'Warlock', 1),
    classId: classIds.warlock,
    name: 'Invocations Known',
    rows: [
      '-',
      '2',
      '2',
      '2',
      '3',
      '3',
      '4',
      '4',
      '5',
      '5',
      '5',
      '6',
      '6',
      '6',
      '7',
      '7',
      '7',
      '8',
      '8',
      '8',
    ],
  },
  {
    id: '16',
    featureId: generateId('class', 'Spells Known', 'Ranger', 1),
    classId: classIds.ranger,
    name: 'Spells Known',
    rows: [
      '-',
      '2',
      '3',
      '4',
      '4',
      '4',
      '5',
      '5',
      '6',
      '6',
      '7',
      '7',
      '8',
      '8',
      '9',
      '9',
      '10',
      '10',
      '11',
      '11',
    ],
  },
  {
    id: '17',
    featureId: generateId('class', 'Infuse Item', 'Artificer', 2),
    classId: classIds.artificer,
    name: 'Infusions Known',
    rows: [
      '-',
      '4',
      '4',
      '4',
      '4',
      '6',
      '6',
      '6',
      '6',
      '8',
      '8',
      '8',
      '8',
      '10',
      '10',
      '10',
      '10',
      '12',
      '12',
      '12',
    ],
  },
  {
    id: '18',
    featureId: generateId('class', 'Infuse Item', 'Artificer', 2),
    classId: classIds.artificer,
    name: 'Infused Items',
    rows: [
      '-',
      '2',
      '2',
      '2',
      '2',
      '3',
      '3',
      '3',
      '3',
      '4',
      '4',
      '4',
      '4',
      '5',
      '5',
      '5',
      '5',
      '6',
      '6',
      '6',
    ],
  },
];

export default ColumnedFeatureSeed;
