import { Prisma } from '@prisma/client';
import { classIds } from './ClassIds';
import { ClassFeatureIds } from './Features.seed';

const ColumnedFeatureSeed: Prisma.ColumnedFeatureCreateManyInput[] = [
  {
    featureId: ClassFeatureIds.bardCantrips,
    classId: classIds.bard,
    name: 'Cantrips Known',
    rows: [
      '2',
      '2',
      '2',
      '3',
      '3',
      '3',
      '3',
      '3',
      '3',
      '4',
      '4',
      '4',
      '4',
      '4',
      '4',
      '4',
      '4',
      '4',
      '4',
      '4',
    ],
  },
  {
    featureId: ClassFeatureIds.bardSpellsKnown,
    classId: classIds.bard,
    name: 'Spells Known',
    rows: [
      '4',
      '5',
      '6',
      '7',
      '8',
      '9',
      '10',
      '11',
      '12',
      '14',
      '15',
      '15',
      '16',
      '18',
      '19',
      '19',
      '20',
      '22',
      '22',
      '22',
    ],
  },
  // {
  //   featureId: ClassFeatureIds.sneakAttack,
  //   classId: classIds.rogue,
  //   name: 'Sneak Attack',
  //   rows: [
  //     '1d6',
  //     '1d6',
  //     '2d6',
  //     '2d6',
  //     '3d6',
  //     '3d6',
  //     '4d6',
  //     '4d6',
  //     '5d6',
  //     '5d6',
  //     '6d6',
  //     '6d6',
  //     '7d6',
  //     '7d6',
  //     '8d6',
  //     '8d6',
  //     '9d6',
  //     '9d6',
  //     '10d6',
  //     '10d6',
  //   ],
  // },
  // {
  //   featureId: ClassFeatureIds.rage,
  //   classId: classIds.barbarian,
  //   name: 'Rages',
  //   rows: [
  //     '2',
  //     '2',
  //     '3',
  //     '3',
  //     '3',
  //     '4',
  //     '4',
  //     '4',
  //     '4',
  //     '4',
  //     '4',
  //     '5',
  //     '5',
  //     '5',
  //     '5',
  //     '5',
  //     '6',
  //     '6',
  //     '6',
  //     'Unlimited',
  //   ],
  // },
  // {
  //   featureId: ClassFeatureIds.rage,
  //   classId: classIds.barbarian,
  //   name: 'Rage Damage',
  //   rows: [
  //     '+2',
  //     '+2',
  //     '+2',
  //     '+2',
  //     '+2',
  //     '+2',
  //     '+2',
  //     '+2',
  //     '+3',
  //     '+3',
  //     '+3',
  //     '+3',
  //     '+3',
  //     '+3',
  //     '+3',
  //     '+4',
  //     '+4',
  //     '+4',
  //     '+4',
  //     '+4',
  //   ],
  // },
  // {
  //   featureId: ClassFeatureIds.druidCantrips,
  //   classId: classIds.druid,
  //   name: 'Cantrips Known',
  //   rows: [
  //     '2',
  //     '2',
  //     '2',
  //     '3',
  //     '3',
  //     '3',
  //     '3',
  //     '3',
  //     '3',
  //     '4',
  //     '4',
  //     '4',
  //     '4',
  //     '4',
  //     '4',
  //     '4',
  //     '4',
  //     '4',
  //     '4',
  //     '4',
  //   ],
  // },
  {
    featureId: ClassFeatureIds.martialArts,
    classId: classIds.monk,
    name: 'Martial Arts',
    rows: [
      '1d4',
      '1d4',
      '1d4',
      '1d4',
      '1d6',
      '1d6',
      '1d6',
      '1d6',
      '1d8',
      '1d8',
      '1d8',
      '1d8',
      '1d8',
      '1d8',
      '1d8',
      '1d8',
      '1d10',
      '1d10',
      '1d10',
      '1d10',
    ],
  },
  {
    featureId: ClassFeatureIds.ki,
    classId: classIds.monk,
    name: 'Ki Points',
    rows: [
      '-',
      '2',
      '3',
      '4',
      '5',
      '6',
      '7',
      '8',
      '9',
      '10',
      '11',
      '12',
      '13',
      '14',
      '15',
      '16',
      '17',
      '18',
      '19',
      '20',
    ],
  },
  {
    featureId: ClassFeatureIds.unarmoredMovement,
    classId: classIds.monk,
    name: 'Unarmored Movement',
    rows: [
      '-',
      '+10 ft.',
      '+10 ft.',
      '+10 ft.',
      '+10 ft.',
      '+15 ft.',
      '+15 ft.',
      '+15 ft.',
      '+15 ft.',
      '+20 ft.',
      '+20 ft.',
      '+20 ft.',
      '+20 ft.',
      '+25 ft.',
      '+25 ft.',
      '+25 ft.',
      '+25 ft.',
      '+30 ft.',
      '+30 ft.',
      '+30 ft.',
    ],
  },
  // {
  //   featureId: ClassFeatureIds.sorcererCantrips,
  //   classId: classIds.sorcerer,
  //   name: 'Cantrips Known',
  //   rows: [
  //     '4',
  //     '4',
  //     '4',
  //     '5',
  //     '5',
  //     '5',
  //     '5',
  //     '5',
  //     '5',
  //     '6',
  //     '6',
  //     '6',
  //     '6',
  //     '6',
  //     '6',
  //     '6',
  //     '6',
  //     '6',
  //     '6',
  //     '6',
  //   ],
  // },
  // {
  //   featureId: ClassFeatureIds.sorcererSpellsKnown,
  //   classId: classIds.sorcerer,
  //   name: 'Spells Known',
  //   rows: [
  //     '2',
  //     '3',
  //     '4',
  //     '5',
  //     '6',
  //     '7',
  //     '8',
  //     '9',
  //     '10',
  //     '11',
  //     '12',
  //     '12',
  //     '13',
  //     '13',
  //     '14',
  //     '14',
  //     '15',
  //     '15',
  //     '15',
  //     '15',
  //   ],
  // },
  // {
  //   featureId: ClassFeatureIds.fontOfMagic,
  //   classId: classIds.sorcerer,
  //   name: 'Sorcery Points',
  //   rows: [
  //     '-',
  //     '2',
  //     '3',
  //     '4',
  //     '5',
  //     '6',
  //     '7',
  //     '8',
  //     '9',
  //     '10',
  //     '11',
  //     '12',
  //     '13',
  //     '14',
  //     '15',
  //     '16',
  //     '17',
  //     '18',
  //     '19',
  //     '20',
  //   ],
  // },
  // {
  //   featureId: ClassFeatureIds.warlockCantrips,
  //   classId: classIds.warlock,
  //   name: 'Cantrips Known',
  //   rows: [
  //     '2',
  //     '2',
  //     '2',
  //     '3',
  //     '3',
  //     '3',
  //     '3',
  //     '3',
  //     '3',
  //     '4',
  //     '4',
  //     '4',
  //     '4',
  //     '4',
  //     '4',
  //     '4',
  //     '4',
  //     '4',
  //     '4',
  //     '4',
  //   ],
  // },
  // {
  //   featureId: ClassFeatureIds.warlockSpellsKnown,
  //   classId: classIds.warlock,
  //   name: 'Spells Known',
  //   rows: [
  //     '2',
  //     '3',
  //     '4',
  //     '5',
  //     '6',
  //     '7',
  //     '8',
  //     '9',
  //     '10',
  //     '10',
  //     '11',
  //     '11',
  //     '12',
  //     '12',
  //     '13',
  //     '13',
  //     '14',
  //     '14',
  //     '15',
  //     '15',
  //   ],
  // },
  // {
  //   featureId: ClassFeatureIds.warlockSpellsKnown,
  //   classId: classIds.warlock,
  //   name: 'Slot Level',
  //   rows: [
  //     '1st',
  //     '1st',
  //     '2nd',
  //     '2nd',
  //     '3rd',
  //     '3rd',
  //     '4th',
  //     '4th',
  //     '5th',
  //     '5th',
  //     '5th',
  //     '5th',
  //     '5th',
  //     '5th',
  //     '5th',
  //     '5th',
  //     '5th',
  //     '5th',
  //     '5th',
  //     '5th',
  //   ],
  // },
  // {
  //   featureId: ClassFeatureIds.warlockSpellsKnown,
  //   classId: classIds.warlock,
  //   name: 'Spell Slots',
  //   rows: [
  //     '1',
  //     '2',
  //     '2',
  //     '2',
  //     '2',
  //     '2',
  //     '2',
  //     '2',
  //     '2',
  //     '2',
  //     '3',
  //     '3',
  //     '3',
  //     '3',
  //     '3',
  //     '3',
  //     '4',
  //     '4',
  //     '4',
  //     '4',
  //   ],
  // },
  // {
  //   featureId: ClassFeatureIds.eldritchInvocations,
  //   classId: classIds.warlock,
  //   name: 'Invocations Known',
  //   rows: [
  //     '-',
  //     '2',
  //     '2',
  //     '2',
  //     '3',
  //     '3',
  //     '4',
  //     '4',
  //     '5',
  //     '5',
  //     '5',
  //     '6',
  //     '6',
  //     '6',
  //     '7',
  //     '7',
  //     '7',
  //     '8',
  //     '8',
  //     '8',
  //   ],
  // },

  {
    featureId: ClassFeatureIds.rangerSpellsKnown,
    classId: classIds.ranger,
    name: 'Spells Known',
    rows: [
      '-',
      '2',
      '3',
      '4',
      '4',
      '4',
      '5',
      '5',
      '6',
      '6',
      '7',
      '7',
      '8',
      '8',
      '9',
      '9',
      '10',
      '10',
      '11',
      '11',
    ],
  },
  // {
  //   featureId: ClassFeatureIds.artificerInfuseItem,
  //   classId: classIds.artificer,
  //   name: 'Infusions Known',
  //   rows: [
  //     '-',
  //     '4',
  //     '4',
  //     '4',
  //     '4',
  //     '6',
  //     '6',
  //     '6',
  //     '6',
  //     '8',
  //     '8',
  //     '8',
  //     '8',
  //     '10',
  //     '10',
  //     '10',
  //     '10',
  //     '12',
  //     '12',
  //     '12',
  //   ],
  // },
  // {
  //   featureId: ClassFeatureIds.artificerInfuseItem,
  //   classId: classIds.artificer,
  //   name: 'Infused Items',
  //   rows: [
  //     '-',
  //     '2',
  //     '2',
  //     '2',
  //     '2',
  //     '3',
  //     '3',
  //     '3',
  //     '3',
  //     '4',
  //     '4',
  //     '4',
  //     '4',
  //     '5',
  //     '5',
  //     '5',
  //     '5',
  //     '6',
  //     '6',
  //     '6',
  //   ],
  // },
  // {
  //   featureId: ClassFeatureIds.artificerCantrips,
  //   classId: classIds.artificer,
  //   name: 'Cantrips Known',
  //   rows: [
  //     '2',
  //     '2',
  //     '2',
  //     '2',
  //     '2',
  //     '2',
  //     '2',
  //     '2',
  //     '2',
  //     '3',
  //     '3',
  //     '3',
  //     '3',
  //     '4',
  //     '4',
  //     '4',
  //     '4',
  //     '4',
  //     '4',
  //     '4',
  //   ],
  // },
  {
    featureId: ClassFeatureIds.clericCantrips,
    classId: classIds.cleric,
    name: 'Cantrips Known',
    rows: [
      '3',
      '3',
      '3',
      '4',
      '4',
      '4',
      '4',
      '4',
      '4',
      '5',
      '5',
      '5',
      '5',
      '5',
      '5',
      '5',
      '5',
      '5',
      '5',
      '5',
    ],
  },
  // {
  //   featureId: ClassFeatureIds.wizardCantrips,
  //   classId: classIds.wizard,
  //   name: 'Cantrips Known',
  //   rows: [
  //     '3',
  //     '3',
  //     '3',
  //     '4',
  //     '4',
  //     '4',
  //     '4',
  //     '4',
  //     '4',
  //     '5',
  //     '5',
  //     '5',
  //     '5',
  //     '5',
  //     '5',
  //     '5',
  //     '5',
  //     '5',
  //     '5',
  //     '5',
  //   ],
  // },
];

export default ColumnedFeatureSeed;
