import { Prisma } from '@prisma/client';
import generateId from '../_helpers/generateId';

const SubclassColumnedFeaturesSeed: Prisma.SubClassColumnedFeatureCreateManyInput[] =
  [
    {
      id: '1',
      featureId: generateId('subclass', 'Cantrips', 'Eldritch Knight', 1),
      subClassId: '7', //eldritch knight
      name: 'Cantrips Known',
      rows: [
        '-',
        '-',
        '2',
        '2',
        '2',
        '2',
        '2',
        '2',
        '2',
        '3',
        '3',
        '3',
        '3',
        '3',
        '3',
        '3',
        '3',
        '3',
        '3',
        '3',
      ],
    },
    {
      id: '2',
      featureId: generateId('subclass', 'Spells Known', 'Eldritch Knight', 2),
      subClassId: '7', //eldritch knight
      name: 'Spells Known',
      rows: [
        '-',
        '-',
        '3',
        '4',
        '4',
        '4',
        '5',
        '6',
        '6',
        '7',
        '8',
        '8',
        '9',
        '10',
        '10',
        '11',
        '11',
        '11',
        '12',
        '13',
      ],
    },
    {
      id: '3',
      featureId: generateId('subclass', 'Cantrips', 'Arcane Trickster', 1),
      subClassId: '89', //arcane trickster
      name: 'Cantrips Known',
      rows: [
        '-',
        '-',
        'Mage Hand + 2',
        'Mage Hand + 2',
        'Mage Hand + 2',
        'Mage Hand + 2',
        'Mage Hand + 2',
        'Mage Hand + 2',
        'Mage Hand + 2',
        'Mage Hand + 3',
        'Mage Hand + 3',
        'Mage Hand + 3',
        'Mage Hand + 3',
        'Mage Hand + 3',
        'Mage Hand + 3',
        'Mage Hand + 3',
        'Mage Hand + 3',
        'Mage Hand + 3',
        'Mage Hand + 3',
        'Mage Hand + 3',
      ],
    },
    {
      id: '4',
      featureId: generateId('subclass', 'Spells Known', 'Arcane Trickster', 2),
      subClassId: '89', //arcane trickster
      name: 'Spells Known',
      rows: [
        '-',
        '-',
        '3',
        '4',
        '4',
        '4',
        '5',
        '6',
        '6',
        '7',
        '8',
        '8',
        '9',
        '10',
        '10',
        '11',
        '11',
        '11',
        '12',
        '13',
      ],
    },
  ];

export default SubclassColumnedFeaturesSeed;
